### ISSUE TITLE
Remote action not resolving version as github

### ISSUE THREAD

**Issue by fennecdjay** [nektos/act#101]
I not quite sure the title is clear, however I hope the example does a better jib at explaining the problem.
In some of my workflows, I have
```
use: fennecdjay/gwion-action@v1
```
It works fine on github, but when running with act, it complains about not finding the reference (it this case, ther is no v1, but github resolves it to the existing v1.0).

I looked at the code to see if I could find something helpful, but didn't find anything.

Looks like (this go library)[https://github.com/hashicorp/go-version] could do name resolving if we feed it the list of releases.

**Comment by cplee** [comment]
I see that repo has a v1 branch and a v1.0 tag.   Which are you expecting to be picked up, the tag or the branch?

**Comment by fennecdjay** [comment]
Github picks `v1.0`, and would pick `v1.1` if found.

**Comment by cplee** [comment]
Looks like GitHub has some code to pick defaults based on the situation you have here...but that isn't documented.  The way they recommend versioning [here](https://help.github.com/en/actions/building-actions/about-actions#versioning-your-action) is to use semver for each release, and UPDATE your major version tag (e.g. `v1`) to point to the new semver release.

So, in this case you ought to update your releases to be semver (e.g. `v1.0.1`) and update your action to NOT have a `v1` branch and instead to have a `v1` tag that points to the commit of `v1.0.1`.  

See [setup-python](https://github.com/actions/setup-python/releases) as a good example

**Comment by fennecdjay** [comment]
Thank you for the clarification!
Sorry it was my bad and not an act issue.

I'm closing this issue.

**Comment by wagenet** [comment]
@cplee While this definitely seems to be the recommendation, it seems like act should follow what GitHub actually does. ruby/setup-ruby doesn't follow the recommendations, but it does work with GitHub Actions and not with act. I've filed an issue, but I don't control the repo so I have no timeline on when/if it will be resolved. https://github.com/ruby/setup-ruby/issues/55

**Comment by eregon** [comment]
I think a moving tag is a `git` anti-pattern, and so I would recommend to handle `v1` being either a branch or a tag (they are both `git` refs, and they both work with `git clone --branch REF`).

**Comment by eregon** [comment]
I opened a new issue since this one was closed and the early discussion wasn't clear: https://github.com/nektos/act/issues/234
