### ISSUE TITLE
is act available for Windows? Error: cannot remove '/usr/local/bin/act'

### ISSUE THREAD

**Issue by zeshanchoudhary** [nektos/act#102]
just tried to installed in my windows machine, but I'm unable to installed it!
Thanks in advance!

**Comment by cplee** [comment]
Just added support on master.  Will be creating a release soon...

**Comment by KingDarBoja** [comment]
Was going to ask the same thing, glad to know about Windows support coming on next release.

**Comment by cplee** [comment]
@KingDarBoja I added a small note on the README.md.  Just download latest release and add to PATH.

If you'd prefer something like choco or scoop and are willing to contribute the work, i'd love to add those.  However, I dont use windows so i'm unable to add those packages.
