### ISSUE TITLE
Issue: runner.workspace context is empty

### ISSUE THREAD

**Issue by JulianGro** [nektos/act#1031]
## System information

    - Operating System: Linux
    - Architecture: x86_64
    - Docker version: 20.10.7
    - Docker image used in `act`: `ghcr.io/catthehacker/ubuntu:full-18.04`
    - `act` version: 0.2.25

## Expected behaviour

`${{runner.workspace}}` should return the current runner workspace.

## Actual behaviour

`${{runner.workspace}}` returns nothing

## Steps to reproduce

Add `${{runner.workspace}}` to a workflow file. (For example `echo "${{runner.workspace}}/test"`)
Run the workflow
Observe

## Additional info

Apparently runner.workspace is not documented. See https://docs.github.com/en/actions/learn-github-actions/contexts#runner-context

**Comment by KnisterPeter** [comment]
@JulianGro As it is not documented it might be not 'officially' supported. As a workaround you should be able to use `${{ env.GITHUB_WORKSPACE }}` to get the workflow folder.

I will close this, unless github officially documents this behavior.
