### ISSUE TITLE
Issue: cache busting does not work for actions pointing to branch

### ISSUE THREAD

**Issue by robertkowalski** [nektos/act#1044]
## System information

- Operating System: macOS 
- Architecture: x64 (64-bit)
- Apple M1: no
- Docker version: 20.10.7
- Docker image used in `act`: node:12-buster-slim
- `act` version: [4d71071](https://github.com/nektos/act/commit/4d7107161e231406bee856258ec847844623224e)

## Expected behaviour

Developing a with an action from the main or master branch should use the latest version from that branch

## Actual behaviour

When you develop an action, and it points to a certain branch, e.g. `main`, you have to delete `~/.cache/act/` manually in between each push to the branch. If not, act will use an outdated version of the action for the run

## Workflow and/or repository

<details>
  <summary>workflow</summary>

https://github.com/robertkowalski/act-issue

Rename a required argument in the code, then rerun act. 

```none
name: Deploy app

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14.x

      - uses: robertkowalski/act-issue@main
        with:
          # The environment, should be "production" or "preview"
          environment: preview
```

The change between the act runs can be found in this diff: https://github.com/robertkowalski/act-issue/commit/f6ca756b730bd4ccde7508846a299ca9bd1b6a8f

</details>

## Steps to reproduce

1. create action with required inputs, push to github
2. reference the file in your workflow with the branchname, run act
3. then update the name of the required field, push to main again
4. run act, it will fail that the old field is not set
5. delete `~/.cache/act/` - it works

## `act` output

<details>
  <summary>Log</summary>

```none
[Deploy app/tests]   ❗  ::error::Input required and not supplied: env
```

</details>

**Comment by ChristopherHX** [comment]
This issue appeared again https://github.com/nektos/act/issues/785? Or it was never fixed...
