### ISSUE TITLE
turn this toolset into a SaaS website

### ISSUE THREAD

**Issue by staabm** [nektos/act#105]
hey guys,

just read the readme of this tool, and got some inspiration of it.

I think it adresses a major pain point of the GithubActions tooling.

After reading it I got the impression that the tool would be even more helpfull, when it would be published as a website (like a online GitHub Actions REPL).

so a website which contains a single big textarea and allow to fill into that the actual workflow the user is trying to debug/develop.

the website could then simulate events so the workflow gets started and one can immediately see the output of it on the website.

would this be feasible? wdyt?

**Comment by fwilhe** [comment]
How would this be different from editing a workflow directly in github's web-based editor? You even get syntax completion/docs there.

**Comment by staabm** [comment]
thanks for your response.

IMO differences would be...
- you don't need to commit to see the changes work
- you don't need to pollute your master branch with trial and error commits
- you don't need to 'wait' for a actual event to happen which triggers the workflow (e.g. for workflows which listen to the creation of a release or on a git tag beeing pushed) -> because the tool would 'simulate' a event by e.g. toggling the workflow with example data
- one could immediately see the action beeing run (and therefore easily can debug the workflow regarding env-vars and `jq`'transformed values

**Comment by cplee** [comment]
Closing... if interested in web interface, check out https://github.com/phishy/wflow
