### ISSUE TITLE
Issue: GITHUB_ACTIONS is always true

### ISSUE THREAD

**Issue by KnisterPeter** [nektos/act#1090]
Not sure if we should changes this behavior, but I think it might be good to follow githubs recommendation for this variable.

## Expected behaviour

According to the [docs](https://docs.github.com/en/actions/learn-github-actions/environment-variables#default-environment-variables) the environment variable `GITHUB_ACTIONS` is set to true if the workflow is run by `GITHUB_ACTIONS` and it should be used to distinguish between local and non-local execution.

## Actual behaviour

In the `act` codebase this variables is statically set to `true`.

https://github.com/nektos/act/blob/11c3fb39dd5d3907baf8f13ef6953d0a21321cc2/pkg/runner/run_context.go#L604

**Comment by catthehacker** [comment]
https://github.com/actions/runner/blob/408d6c579c36f0eb318acfdafdcbafc872696501/src/Runner.Worker/Container/DockerCommandManager.cs#L143
https://github.com/actions/runner/blob/408d6c579c36f0eb318acfdafdcbafc872696501/src/Runner.Worker/Container/DockerCommandManager.cs#L209
https://github.com/actions/runner/blob/408d6c579c36f0eb318acfdafdcbafc872696501/src/Runner.Sdk/ProcessInvoker.cs#L272

**Comment by KnisterPeter** [comment]
Yes, that's what I've meant. It is true if it is executed in a runner.
From the docs linked above:

> Always set to true when GitHub Actions is running the workflow. You can use this variable to differentiate when tests are being run locally or by GitHub Actions.

**Comment by kevcube** [comment]
@KnisterPeter IMO setting this to `true` makes sense.

`act` is for simulating GitHub Actions workflow runs. If someone is checking `$GITHUB_ACTIONS` in an if-statement, `act` will want them to take the path for if it were `true`, in order to properly simulate GitHub actions.

**Comment by KnisterPeter** [comment]
So then. I'll close this.
