### ISSUE TITLE
Issue: Cannot start a Windows container

### ISSUE THREAD

**Issue by ThomasSowders** [nektos/act#1096]
## System information

    - Operating System: Windows
    - Architecture: x64 (64-bit)
    - Apple M1: N/A
    - Docker version: 20.10.13
    - Docker image used in `act`: A non-public Windows Docker image
    - `act` version 0.2.26

Docker is setup to run Windows containers

## Expected behaviour

act creates a Windows container and runs the workflow

## Actual behaviour

`act` does not seem to understand that this in a Windows container, and tries to mount a volume to `/toolcache`, resulting in the error "Error response from daemon: invalid mount config for type "volume": invalid mount path: '/toolcache'"

<details>
  <summary>Log</summary>
Some internal identifiers have been replaced with ▮ characters

```none

> act --container-architecture windows/amd64 --job build-and-deploy -P self-hosted=us.gcr.io/▮/buildagent-windows:latest -v

[ci-shared/build-and-deploy]    docker pull image=us.gcr.io/▮/buildagent-windows:latest platform=windows/amd64 username= forcePull=false
[ci-shared/build-and-deploy]    docker pull us.gcr.io/▮/buildagent-windows:latest
time="2022-03-30T15:17:27-04:00" level=debug msg="Image exists? true"
[ci-shared/build-and-deploy]    docker create image=us.gcr.io/▮/buildagent-windows:latest platform=windows/amd64 entrypoint=["/usr/bin/tail" "-f" "/dev/null"] cmd=[]
time="2022-03-30T15:17:27-04:00" level=debug msg="Loading slug from git directory 'C:\\▮\\.git'"
time="2022-03-30T15:17:27-04:00" level=debug msg="Loading revision from git directory 'C:\\▮\\.git'"
time="2022-03-30T15:17:27-04:00" level=debug msg="Found revision: 21▮d3\n"
time="2022-03-30T15:17:27-04:00" level=debug msg="HEAD points to '21▮d3'"
time="2022-03-30T15:17:38-04:00" level=debug msg="using github ref: refs/heads/▮"
time="2022-03-30T15:17:38-04:00" level=debug msg="Found revision: 21▮d3\n"
time="2022-03-30T15:17:38-04:00" level=debug msg="using github ref: refs/heads/▮"
time="2022-03-30T15:17:38-04:00" level=debug msg="Found revision: 21▮d3\n"
Error: Error response from daemon: invalid mount config for type "volume": invalid mount path: '/toolcache'
```

</details>

**Comment by catthehacker** [comment]
Windows containers are not supported

**Comment by ChristopherHX** [comment]
If you want windows container => https://github.com/ChristopherHX/runner.server, should be similar enough to act.
