### ISSUE TITLE
Issue: Workflows without a `push` trigger are hidden

### ISSUE THREAD

**Issue by davfsa** [nektos/act#1097]
## System information

- Operating System: Linux
- Architecture: x64
- Apple M1: no
- Docker version: 20.10.14
- Docker image used in `act`: middle
- `act` version: 0.2.26

## Expected behaviour
When running `act -l` or `act --graph`, all workflows are shown

## Actual behaviour

Only workflows which are triggered by `push` (can be alone or along with other events) are shown.

## Workflow and/or repository

Look in logs

## Steps to reproduce

Look at logs

<details>
  <summary>Log</summary>

```console
$ cat .github/workflows/ci.yml
name: CI

on:
  workflow_dispatch:
  pull_request:

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3


$ act -l
Stage  Job ID  Job name  Workflow name  Workflow file  Events

# Edit to add push trigger

$ cat .github/workflows/ci.yml
name: CI

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
$ act -l
Stage  Job ID   Job name  Workflow name  Workflow file  Events           
0      linting  linting   CI             ci.yml         workflow_dispatch,pull_request,push
```

</details>

**Comment by KnisterPeter** [comment]
You have to run `act -l <event-name>`. The default is `push` if no even name is given.
