### ISSUE TITLE
Enhancement: Running `act` on `HPC`/`without admin rights`

### ISSUE THREAD

**Issue by sudomaze** [nektos/act#1125]
## Describe feature

I am developing on an `HPC` server where I don't have admin rights to install `go` and `docker`. Although I might be able to ask the sysadmin to install `go`, we can't install `docker` on the `HPC` server due to security reasons. However, the `HPC`  server has a replacement for `docker`, which is [`singularity`](https://apptainer.org/).

I was wondering whether is enable `act` to work with `singularity` as it will enable researchers and engineers who are developing on `HPC` servers to run `GitHub Actions` on the `HPC` server.

If there is a replacement to `act` that does this, please let me know as I have been doing a lot of research and couldn't find something as powerful as `act` or even something that does the running of `GitHub Actions` on `HPC` servers.

**Comment by catthehacker** [comment]
you can specify socket with `DOCKER_HOST` environment variable and point it to singularity socket

**Comment by KevinSayers** [comment]
I just was pointed to Act and I am interested in the exact same application (so great timing!) of testing on an HPC system. Perhaps I am missing something but does the Singularity socket solution mentioned by @catthehacker require Singularity-CRI to be installed first?

**Comment by Linux-cpp-lisp** [comment]
Can someone elaborate on how one would set up `DOCKER_HOST` with `singularity`? I am also on an academic cluster that will not support docker for security reasons (https://docs.rc.fas.harvard.edu/kb/singularity-on-the-cluster/) and would like to be able to run CI workflows on that hardware.

**Comment by magland** [comment]
I would also love to use act with singularity, but I don't understand the solution from @catthehacker . Could someone elaborate a bit on how this would be done?
