### ISSUE TITLE
Issue: libnss3.so: cannot open shared object file

### ISSUE THREAD

**Issue by unional** [nektos/act#1130]
## System information

- Operating System: Windows
- Architecture: x64
- Apple M1: no
- Docker version: 20.10.14
- Docker image used in `act`: ghcr.io/catthehacker/ubuntu:act-latest
- `act` version: 0.2.26

## Expected behaviour

Able to run vscode test

## Actual behaviour

```sh
/.../.vscode-test/vscode-linux-x64-1.66.2/VSCode-linux-x64/code: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory| Failed to run tests
```

## Workflow and/or repository

I'm using shared workflow from here:

https://github.com/unional/.github/blob/main/.github/workflows/web-rush-verify.yml

Since `act` doesn't support it, I copied the workflow to the local repo to test it out.

It is running vscode test and working on `ubuntu-latest` on github action.

But the `ghcr.io/catthehacker/ubuntu:act-latest` docker seems to be missing this `libnss3.so`.

My guess is adding `apt update & apt install libnss3-dev` could fix it.

**Comment by catthehacker** [comment]
Those images intentionally are not shipped with dev libraries as they would increase size heavily.
