### ISSUE TITLE
Issue: "docker-credential-desktop": executable file not found in $PATH

### ISSUE THREAD

**Issue by sammcj** [nektos/act#1132]
## System information

- Operating System: macOS
- Architecture: arm (m1)
- Apple M1: yes
- Docker version: colima 0.3.4, docker 20.10.11
- Docker image used in `act`:ghcr.io/catthehacker/ubuntu:act-latest
- `act` version: act version 0.2.26

## Expected behaviour

Act to work with Colima, as Colima runs Docker CE (but not desktop).

## Actual behaviour

Fails to start, it looks like it relies on a binary `docker-credential-desktop` that only exists with Docker desktop (which you're not allowed to use if you're on a business machine due to licensing).

```
🚀  Start image=ghcr.io/catthehacker/ubuntu:act-latest
🚀  Start image=ghcr.io/catthehacker/ubuntu:act-latest
🐳  docker pull image=ghcr.io/catthehacker/ubuntu:act-latest platform= username= forcePull=false
🐳  docker pull image=ghcr.io/catthehacker/ubuntu:act-latest platform= username= forcePull=false

WARN[0000] Could not get auth config from docker config: error getting credentials - err: exec: "docker-credential-desktop": executable file not found in $PATH, out: ``
WARN[0000] Could not get auth config from docker config: error getting credentials - err: exec: "docker-credential-desktop": executable file not found in $PATH, out: ``

ERRO[0000] Unable to interpolate expression 'format('{0}', steps.build_version.outputs.build_version)': Unable to dereference 'outputs' on non-struct 'invalid'
ERRO[0000] Unable to interpolate expression 'format('{0}', steps.container_tag_name.outputs.container_tag_name)': Unable to dereference 'outputs' on non-struct 'invalid'

Error: error getting credentials - err: exec: "docker-credential-desktop": executable file not found in $PATH, out: ``
```

**Comment by catthehacker** [comment]
It looks like colima doesn't provide executable for interfacing with credential store, so it should be fixed by them.

**Comment by ZauberNerd** [comment]
Could it be that you have a credential store set in your docker config: `~/.docker/config.json`:
```json
"credsStore": "desktop"
```
But since you switched to colima it is not used anymore? See also: https://github.com/abiosoft/colima/issues/52

**Comment by sammcj** [comment]
That was it @ZauberNerd ! Thank you so much!
