### ISSUE TITLE
Enhancement: support for setting working directory in container

### ISSUE THREAD

**Issue by jacob-carlborg** [nektos/act#1134]
## Describe feature

I would like to be able to set the working directory inside the container which is running the workflows. Currently Act is using the full path of the working directory where the `act` command is run, as the working directory inside the container. This usually does not match the working directory when a workflow is run on github.com. I would like the environment Act is using to run the workflows to be as similar as possible to the environment on github.com.

**Comment by catthehacker** [comment]
We don't use same path due to some issues we had, but you shouldn't hard-code GitHub runner paths. It's recommended to always use contexts and environment variables. Other than that, initial working directory doesn't really matter.
