### ISSUE TITLE
Enhancement: Ability to install act package into Windows OS (via winget for example).

### ISSUE THREAD

**Issue by omonimus1** [nektos/act#1146]
## Describe feature
It would be great to download and use this package into Windows OS. 
Distribute it via winget (official windows package manager) will allow more developers to use act. 

In terms of advertisement, it would be great also from the https://formulae.brew.sh/formula/act#default redirect to winget for windows user (as many tutorials about act already redirect directly to brew page).

**Comment by alanlivio** [comment]
It is a very interesting feature.

**Comment by alanlivio** [comment]
It is a very interesting feature.

**Comment by phillip-haydon** [comment]
@catthehacker it looks like issue 140 was merged and closed in September. Could this now be added to winget?

**Comment by Arthapz** [comment]
https://github.com/Arthapz/winget-pkgs/pull/1 i've done a PR, maybe need some reviewing (for publishers URLs)

**Comment by Arthapz** [comment]
ah the package is done, but they can't merge it because of https://github.com/microsoft/winget-pkgs/issues/87300

**Comment by sitiom** [comment]
> [microsoft/winget-pkgs#93675](https://github.com/microsoft/winget-pkgs/pull/93675) i've done a PR, maybe need some reviewing (for publishers URLs)

@Arthapz Please check my review on your PR.

Also, once the PR is merged, [Winget Releaser](https://github.com/vedantmgoyal2009/winget-releaser) would have to be set up in this repo for automatic package updates.

**Comment by Arthapz** [comment]
done

**Comment by Arthapz** [comment]
My PR cas merge onto winget, act should be be installable by winget now

**Comment by sitiom** [comment]
The Winget package is currently outdated, and there is a blocking issue for Winget Releaser: https://github.com/vedantmgoyal2009/winget-releaser/issues/82. Will PR the releaser workflow once that is resolved.
