### ISSUE TITLE
Issue: `make install` runs into `Permission denied`

### ISSUE THREAD

**Issue by barrettj12** [nektos/act#1149]
## System information

- Operating System: Ubuntu 20.04 LTS
- Architecture: x64 (amd64)
- Apple M1: no
- `act` version: dfca2c5
- Go version: go1.18.1 linux/amd64

## Expected behaviour

Run `make install` on the source code, and `act` is installed by Go.

## Actual behaviour

`make install` returns the error:
```
cp: cannot create regular file '/usr/local/bin/act': Permission denied
```
`sudo env "PATH=$PATH" make install` still gives me silly errors, but it does install `act`. I'm not sure if using `sudo` with `make` is recommended, though.

I can see two solutions:
- change the `Makefile` so that it has permissions to create the binary
- change the README so that users know to use sudo.

**Comment by larry0x** [comment]
Same issue

- Operating System: Ubuntu 22.04.4 LTS
- Architecture: x64 (amd64)
- Apple M1: no
- act version: v0.2.64
- Go version: go1.22.5 linux/amd64
