### ISSUE TITLE
provide a more comprehensive example of  .actrc

### ISSUE THREAD

**Issue by shelper** [nektos/act#1209]
### Details

i am trying to use act with my custom docker.sock path, how to config that in .actrc? i tried all the combination i can think of, but none worked. the documentation is not clear to me how to config it and googling does not give answer either
things i tried:
```
--container-daemon-socket /mnt/wsl/shared-docker/docker.sock
-b --container-daemon-socket /mnt/wsl/shared-docker/docker.sock
-b --container-daemon-socket=/mnt/wsl/shared-docker/docker.sock
-b socket=/mnt/wsl/shared-docker/docker.sock
socket=/mnt/wsl/shared-docker/docker.sock
```
I think it would be really helpful to provide a comprehensive `.actrc` example file as the configuration and the command line option seems not identical, or i might miss anything here?

**Comment by shelper** [comment]
well, i figured i can do this to solve my problem
`export DOCKER_HOST="unix:///mnt/wsl/shared-docker/docker.sock"`
but the qeustion then is: why we have this `--container-daemon-socket` if it does not work....

**Comment by ChristopherHX** [comment]
I hope this will help you to understand it better

|`DOCKER_HOST`|`--container-daemon-socket path/to/socket`|`--env DOCKER_HOST=path/to/socket`|
---|---|---
|Act uses this environment variable to connect to non default docker sockets|Act bind mounts this socket into the docker container, e.g. if you want to do docker in docker|You may need this if you want to call a docker in the docker container|

Act doesn't allow to configure the `DOCKER_HOST` env variable in a `.actrc` file. It would be better to add it if act may switch to yaml configs, `.actrc` doesn't seem to be great.

```
<flag> [<parameter can include spaces>]
--my-flag /path/with/ space
 --my-flag /path/with/ space 
-P ubuntu-latest=ubuntu:latest
```
This is correct:
```
--container-daemon-socket /mnt/wsl/shared-docker/docker.sock
```

In recent versions of act preceeding and trailing spaces are ignored on each line
