### ISSUE TITLE
Providing large secrets (json format)

### ISSUE THREAD

**Issue by thijslimmen** [nektos/act#121]
What do you recommend for providing large secrets like the AZURE_CREDENTIALS secret json format?

The following doesn't work. This secret does work in github secrets.
`
-s AZURE_CREDENTIALS="{"clientId":"<redacted>","clientSecret":"<redacted>","subscriptionId":"<redacted>","tenantId":"<redacted>","activeDirectoryEndpointUrl":"https://login.microsoftonline.com","resourceManagerEndpointUrl":"https://management.azure.com/","activeDirectoryGraphResourceId":"https://graph.windows.net/","sqlManagementEndpointUrl":"https://management.core.windows.net:8443/","galleryEndpointUrl":"https://gallery.azure.com/","managementEndpointUrl":"https://management.core.windows.net/"}"
`

I replaced the guids with generated guids.

**Comment by cplee** [comment]
@thijslimmen I think the `"` needs to be escaped, or surround the value with `'` instead of `"`

**Comment by cplee** [comment]
One other option @thijslimmen ... you can set the `AZURE_CREDENTIALS` environment variable in your shell and then just run `act -s AZURE_CREDENTIALS` and it will pull the secret from your env
