### ISSUE TITLE
Use multiline secrets

### ISSUE THREAD

**Issue by Applelo** [nektos/act#123]
I would like to pass a multi-lines secrets like a SSH KEY but it seems impossible currently with the .act file or with the prompt.

Can you consider to add this feature or maybe a workaround to this issue ?

**Comment by cplee** [comment]
I believe a workaround is to put the secret in a file and use:

```
act -s MY_SECRET="$(< secret.txt)"
```

**Comment by cplee** [comment]
Here's a thought @Applelo.  Would you want act to support a config file in `~/.config/act/secrets.yml` that you define your secrets in?

**Comment by Applelo** [comment]
Thanks for you quick answer. So I have try your workaround but it seems to not working. Act return nothing and stop.

Also when I tried to add more secrets, your program return `Error: accepts at most 1 arg(s), received 4`

My .act file
```
-s SSH_PRIVATE_KEY="$(< ~/.config/act/ssh.txt)" GITHUB_PACKAGES_TOKEN="🤫" CONFIG_FILE="$(< ~/.config/act/config.js)"
```

Yeah, I am ok to have an act folder with a `secrets.yml`.  It would be nice to store some files also in this folder 👍 (like an ssh key for example ^^).

**Comment by cplee** [comment]
fixed in #133

**Comment by FirzenYogesh** [comment]
Hi, @cplee 
does the multiline secret work only on the prompt?
I have been trying to use it from file i have declared the secret in .actrc and a value in .env for that secret

eg: 
.actrc
`-s SECRET_VAR="$(< $SECRET_VAR)"`
.env
`SECRET_VAR=/path/to/file`

this does not work

but on command line prompt it works if i feed the value directly or through environment variable

**Comment by slmingol** [comment]
@FirzenYogesh prob. should open a new question/issue since this one was closed.

**Comment by leonardorrodrigues** [comment]
## 🤖 AutoQA Results

### 📁 Task: `example_task`

- **Setup Only**: ✅ FAILED (expected)
- **Setup + Solution**: ✅ PASSED
- **Overall**: ✅ PASSED

**Status**: ✅ ALL TESTS PASSED

🎉 All 1 tasks passed verification!

---
*🤖 AutoQA Bot - Ensuring task quality and compliance*

**Comment by leonardorrodrigues** [comment]
## 🤖 AutoQA Results

### 📁 Task: `example_task`

- **Setup Only**: ✅ FAILED (expected)
- **Setup + Solution**: ✅ PASSED
- **Overall**: ✅ PASSED

**Status**: ✅ ALL TESTS PASSED

🎉 All 1 modified task(s) passed verification!

---
*🤖 AutoQA Bot - Ensuring task quality and compliance*

**Comment by makeavish** [comment]
🤖 Hi @nektos/act, I've received your request, and I'm working on it now! You can track my progress [in the logs](https://github.com/nektos/act/actions/runs/1) for more details.

**Comment by makeavish** [comment]
🤖 Hi @nektos/act, I've received your request, and I'm working on it now! You can track my progress [in the logs](https://github.com/nektos/act/actions/runs/1) for more details.

**Comment by makeavish** [comment]
🤖 Hi @nektos/act, I've received your request, and I'm working on it now! You can track my progress [in the logs](https://github.com/nektos/act/actions/runs/1) for more details.

**Comment by makeavish** [comment]
🤖 Hi @nektos/act, I've received your request, and I'm working on it now! You can track my progress [in the logs](https://github.com/nektos/act/actions/runs/1) for more details.

**Comment by makeavish** [comment]
🤖 Hi @nektos/act, I've received your request, and I'm working on it now! You can track my progress [in the logs](https://github.com/nektos/act/actions/runs/1) for more details.

**Comment by makeavish** [comment]
🤖 Hi @nektos/act, I've received your request, and I'm working on it now! You can track my progress [in the logs](https://github.com/nektos/act/actions/runs/1) for more details.

**Comment by makeavish** [comment]
🤖 Hi @nektos/act, I've received your request, and I'm working on it now! You can track my progress [in the logs](https://github.com/nektos/act/actions/runs/1) for more details.

**Comment by makeavish** [comment]
🤖 Hi @nektos/act, I've received your request, and I'm working on it now! You can track my progress [in the logs](https://github.com/nektos/act/actions/runs/1) for more details.

**Comment by makeavish** [comment]
🤖 Hi @nektos/act, I've received your request, and I'm working on it now! You can track my progress [in the logs](https://github.com/nektos/act/actions/runs/1) for more details.
