### ISSUE TITLE
Choose workflow

### ISSUE THREAD

**Issue by airtonix** [nektos/act#1253]
### Act version

act version 0.2.26

### Feature description

We can choose the job, but not the workflow,
We can point to other folders of workflow files, but not a specific workflow file.

So when i have a workflow (among many others) that contains a complex fan out fan in flow, how can i run all the jobs in just that workflow file? 

We should talk about a flag that controls which workflow file to run: 

```sh
act --workflow="pathname to workflow file"
```

**Comment by KnisterPeter** [comment]
Just use
act -W file
