### ISSUE TITLE
Running an action in its own repository results in an empty action name

### ISSUE THREAD

**Issue by cedrickring** [nektos/act#128]
act Version: 0.2.5
OS: macOS & Windows 10

When starting act in [cedrickring/golang-action](https://github.com/cedrickring/golang-action) the Docker build fails with `Error: invalid reference format` (Command: `docker build -t act-:latest <workdir>`).

On [this line](https://github.com/nektos/act/blob/1f9f3b826e9cf56ddbfb4ad0c796b5a4da4b32a1/pkg/runner/step_context.go#L244) the action name is becoming an empty string.

### Steps to reproduce
1. Clone [cedrickring/golang-action](https://github.com/cedrickring/golang-action)
2. Enter the repostory directory
3. Run `act`

**Comment by cplee** [comment]
Hey @cedrickring - i don't see that branch, can you push it up?

**Comment by cedrickring** [comment]
Sorry, it's already into master.

**Comment by cplee** [comment]
I see the problem, should be a quick fix

https://github.com/cedrickring/golang-action/blob/master/.github/workflows/push.yml#L10

**Comment by cplee** [comment]
fixed on `master`.  will cut a new release later today.
