### ISSUE TITLE
Invalid repository name when running a local docker action

### ISSUE THREAD

**Issue by cedrickring** [nektos/act#129]
act Version: 0.2.5
OS: macOS & Windows

When running a local docker action from a different directory, the docker build command receives an invalid repository name:

Command: `docker build -t act-Users-cedrickring-golang-action:latest /Users/cedrickring/golang-action`
Output: `Error: invalid reference format: repository name must be lowercase`

### Steps to reproduce
1. Clone [cedrickring/golang-action](https://github.com/cedrickring/golang-action)
2. Create a different directory with a `.github/workflows/workflow.yaml` and reference the action with `../relative/path/to/golang-action`
3. Run `act`

**Comment by cedrickring** [comment]
I don't really know if Github allows this but this happened to me while trying to create a workaround for #128.

**Comment by cplee** [comment]
fixed on `master`.  will cut a new release later today.
