### ISSUE TITLE
Provide a way to install this thru Chocolatey

### ISSUE THREAD

**Issue by azchohfi** [nektos/act#132]
It would be so much easier to install this thru a simple "choco install act"

**Comment by cplee** [comment]
Cool idea @azchohfi - I don't know much about Chocolately, is this something you'd be able to help with?

**Comment by azchohfi** [comment]
I'll try to spend some cycles! The only thing we'll need from you, so you own the package on chocolatey, is to create an account an add the API Key. I'll let you know here.

**Comment by cplee** [comment]
Cool, i just signed up.  I can add the key as a secret whenever you're ready

**Comment by azchohfi** [comment]
It's being hard to build the whole thing, since, I think, building on Windows is not supported. I have WSL (Ubuntu) and it did build after I installed the dependencies (go, etc), but simply running the release task is not actually building anything:
⨯ release failed after 0.02s error=failed to generate snapshot name: template: tmpl:1:7: executing "tmpl" at <.Env.SNAPSHOT_VERSION>: map has no entry for key "SNAPSHOT_VERSION"
[push/release]   ❗  ::error::The process '/home/actions/temp/1639e947-6824-4220-a837-ff98db1aecb1/goreleaser' failed with exit code 1
[push/release]   ❌  Failure - GoReleaser
Error: exit with `FAILURE`: 1

I'll just build the nuspec file. Could you integrate it with the gorelease? The chocolatey command line tool needs to run on linux, but it does work on mono.

**Comment by cplee** [comment]
I'll give it a shot!  Send me what you have

**Comment by azchohfi** [comment]
https://github.com/nektos/act/pull/139
Running choco on linux:
https://www.onitato.com/post/running-chocolatey-on-linux/
Once you can run it, then a simple:
choco pack act.nuspec --version 0.2.6
choco apiKey $(SECRET)
choco push act.0.2.6.nupkg

The only missing piece is the integration with the build system.

**Comment by azchohfi** [comment]
Nice! Thanks!
