### ISSUE TITLE
[Question] is act container with hostNetwork supported?

### ISSUE THREAD

**Issue by aledbf** [nektos/act#141]
Hi, I'm trying to use an [action](https://github.com/engineerd/setup-kind) that creates a [kind](https://kind.sigs.k8s.io/) cluster, which works just fine but this action opens a port in 127.0.0.1, which is not possible to reach from any step. Is it possible to use hostNetwork or what is the suggestion for this scenario?
Thanks

**Comment by cplee** [comment]
This is currently not supported, but could be solved by either switching to hostNetwork (as suggested) or with container links.  Thanks for the suggestion!
