### ISSUE TITLE
Allow GITHUB_REPOSITORY to be overridden

### ISSUE THREAD

**Issue by emmjohnson** [nektos/act#1424]
### Act version

0.2.33

### Feature description

When developing a github action, it would be cool to be able to write end to end tests with act. We would need the ability to override GITHUB_REPOSITORY (and SHA) to emulate a user using our action in their repo.

Currently GITHUB_REPOSITORY is automatically set to the action we are developing the action in.

**Comment by KnisterPeter** [comment]
You can do with an event json file

**Comment by emmjohnson** [comment]
I'm having a hard time finding any simple examples of this, do you know of any?

**Comment by KnisterPeter** [comment]
The payloads (link on each event) does contain examples per event:
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows

**Comment by KnisterPeter** [comment]
After some more thoughts I'm not sure if all props could be set by the event file.
I'll reopen the request. Maybe someone is willing to implement it

**Comment by emmjohnson** [comment]
Okay, I tried a few things with the events and inputs and was unable to achieve setting the GITHUB_REPOSITORY

**Comment by emmjohnson** [comment]
What tool did you add @ChristopherHX ?

**Comment by KnisterPeter** [comment]
Yes, from my point of view it's fine.
