### ISSUE TITLE
Array of runs-on runners fails

### ISSUE THREAD

**Issue by aidansteele** [nektos/act#146]
Using `act` 0.2.6. An array of runners (even if only one element) fails like so:

```
Error: yaml: unmarshal errors:
  line 9: cannot unmarshal !!seq into string
  line 70: cannot unmarshal !!seq into string
  line 100: cannot unmarshal !!seq into string
  line 184: cannot unmarshal !!seq into string
```

Submitting a PR to accept an array and use only the first runner would be trivial, but probably not super helpful. A PR to actually run all `runs-on` runners would probably be more substantial and worth discussion first. What do you think?

**Comment by cplee** [comment]
I like the idea of supporting multiple `runs-on`...could be implemented pretty easily using the same model as the `matrix:` support.

**Comment by aidansteele** [comment]
I'll take a look into that approach and try submit a PR. If I get stuck, I'll let you know so you're not waiting forever.

**Comment by aidansteele** [comment]
So I just looked into this a bit more and it seems I've personally misunderstood and misused the array form of `runs-on`. Quoting from the [self-hosted runner docs](https://help.github.com/en/actions/hosting-your-own-runners/using-self-hosted-runners-in-a-workflow)

> you can use self-hosted in an array with additional labels, such as labels for a specific operating system or system architecture, to select only the runner types you specify.

So it's not actually a different syntax for matrix builds (as I had assumed) but a way of specifying a logical `AND` on labels when choosing an applicable self-hosted runner.

What do you want to do in this case? I think a sensible approach for `act` to take would be to use the *first* label in the array that corresponds to a platform it recognises and then run on that platform. Does that sound right to you?

**Comment by cplee** [comment]
I like that plan.  2 tasks:
* update `RunsOn` in [workflow.go](https://github.com/nektos/act/blob/master/pkg/model/workflow.go) to behave like `Needs` which supports list or string forms
* update `run_context.go` to use the first recognized  platform
