### ISSUE TITLE
Step working-directory currently isn't used

### ISSUE THREAD

**Issue by aidansteele** [nektos/act#149]
https://github.com/nektos/act/blob/f6b761378af17296aba8ff3be54e26d56acfeae5/pkg/model/workflow.go#L190

This field appears not to be referenced anywhere

**Comment by cplee** [comment]
Good catch!

**Comment by aidansteele** [comment]
I’m happy to submit a PR for this if you want?

**Comment by cplee** [comment]
That'd be much appreciated.
