### ISSUE TITLE
Can't find `action.yml` file for action actions/setup-ruby

### ISSUE THREAD

**Issue by mrcasals** [nektos/act#150]
hi!

I just installed the latest version of `act` published in Homebrew (0.2.6), and tried to run it against this workflow file:

https://github.com/diputaciodegirona/decidim-diputacio-girona/blob/master/.github/workflows/decidim_ci.yml

When running it with `act -n` it ives me this output:

```
*DRYRUN* [[CI] Decidim/Tests] 🚀  Start image=node:12.6-buster-slim
*DRYRUN* [[CI] Decidim/Tests]   🐳  docker run image=node:12.6-buster-slim entrypoint=["/usr/bin/tail" "-f" "/dev/null"] cmd=[]
*DRYRUN* [[CI] Decidim/Tests] ⭐  Run actions/checkout@v2.0.0
*DRYRUN* [[CI] Decidim/Tests]   ✅  Success - actions/checkout@v2.0.0
*DRYRUN* [[CI] Decidim/Tests] ⭐  Run actions/setup-ruby@master
*DRYRUN* [[CI] Decidim/Tests]   ☁  git clone 'https://github.com/actions/setup-ruby' # ref=master
*DRYRUN* [[CI] Decidim/Tests]   ❌  Failure - actions/setup-ruby@master
Error: open /Users/marc/.cache/act/actions-setup-ruby@master/action.yaml: no such file or directory
```

I checked the action repo and it has an `action.yml` file (not the `action.yaml` that it's looking for, not the `a` missing in the repo file).

I'm not sure how to fix it, I've never written any Go :(

**Comment by KingDarBoja** [comment]
Have same issue but with `actions/setup-python@v1` in my case. The issue seems to be related to the action not being available locally 🤔

**Comment by cplee** [comment]
This one isn't related to #107.  The problem is that in dryrun mode the action isn't cloned from the remote repo.  Will look at a fix...

**Comment by KingDarBoja** [comment]
Apologies for the response, I thought it was the cause. Anyway, glad we got a fix so quick! 💯
