### ISSUE TITLE
Env context is not being replaced using expressions

### ISSUE THREAD

**Issue by davidlj95** [nektos/act#151]
Act does not replace the `env` context when using expressions in workflow files

## Issue
When using ``${{ env.WHATEVER }}`` in a workflow file, `act` does not replace it by the actual environment variable and returns undefined

## Reproducing
I've created a repo where this is easily reproducible 

https://github.com/davidlj95/act-bug

You can see in the Actions tab that GitHub is replacing the env var though when running `act` locally it does not and returns `undefined` 

Thanks!

**Comment by cplee** [comment]
dup of https://github.com/nektos/act/issues/134

fixed on master and will be in next release
