### ISSUE TITLE
Installable via go install github.com/nektos/act ?

### ISSUE THREAD

**Issue by ydnar** [nektos/act#153]
I tried to add `act` to our monorepo’s tools.go file and when installing, I got this error:

```sh
❯ go generate --tags tools ./internal/tools
go: finding module for package github.com/Sirupsen/logrus
go: found github.com/Sirupsen/logrus in github.com/Sirupsen/logrus v1.4.2
go: alta.software/p1/internal/tools imports
	github.com/nektos/act imports
	github.com/nektos/act/cmd imports
	github.com/nektos/act/pkg/runner imports
	github.com/nektos/act/pkg/container imports
	github.com/docker/docker/pkg/archive imports
	github.com/Sirupsen/logrus: github.com/Sirupsen/logrus@v1.4.2: parsing go.mod:
	module declares its path as: github.com/sirupsen/logrus
	        but was required as: github.com/Sirupsen/logrus
```

**Comment by cplee** [comment]
@ydnar - where is the `Sirupsen` (with upper-case `S`) coming from?  That is the old invalid name for that logging framework.

For history, see here: https://github.com/sirupsen/logrus/issues/570#issuecomment-313933276

**Comment by ydnar** [comment]
That’s a great question. Go says from docker/docker/pkg/archive but A) it was renamed, B) they fixed their vendored copy and C) that package isn’t module-aware.

Remapping via `replace` didn’t work either.
