### ISSUE TITLE
Add support for `>> $GITHUB_STEP_SUMMARY`

### ISSUE THREAD

**Issue by jontze** [nektos/act#1533]
### Act version

0.2.34

### Feature description

With the usage of `$GITHUB_STEP_SUMMARY` in workflows it's possible to generate markdown files as a summary of a job like this:
```bash
echo "{markdown content}" >> $GITHUB_STEP_SUMMARY
``` 
The usage is pretty similar to `$GITHUB_ENV` or `$GITHUB_OUTPUT`.
Ref.: https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#adding-a-job-summary

However, act fails on this point, because the `$GITHUB_STEP_SUMMARY` variable is not set:
```txt
/var/run/act/workflow/3: line 14: $GITHUB_STEP_SUMMARY: ambiguous redirect
```
I don't think that `act` should actually generate a markdown file as well, IMO it's enough to just ensure that the workflow doesn't fail if the syntax is used.

Thanks for the cool project :heart:

**Comment by mottet** [comment]
Looks like `$GITHUB_STEP_SUMMARY` is unset so the redirection points to nothing and fails.

I use a workaround to have the summary working in Github Action and not crashing in Act :

``` sh
[ -w "$GITHUB_STEP_SUMMARY" ] && echo "{markdown content}" >> $GITHUB_STEP_SUMMARY
```

With the `-w` I check if `$GITHUB_STEP_SUMMARY` value is the path to a writable file and only if it is true the right part of `&&` whould be executed.

I think manually setting the value `$GITHUB_STEP_SUMMARY` could also work but I didn't tried.

**Comment by shubhbapna** [comment]
You should be able to simply set this using the env flag. This way you will have control as to where you want the summary to be written to. For eg:
```
# when you just want your workflow to run without crashing and you don't care about the summary
act push --env GITHUB_STEP_SUMMARY="/dev/null"

# when you want to see whats being written
act push --env GITHUB_STEP_SUMMARY="/dev/stdout"
```

**Comment by sarthak77** [comment]
What is the fix for this? I'm still getting the same error. Should we explicitly set the `$GITHUB_STEP_SUMMARY` variable?

**Comment by sarthak77** [comment]
> What is the fix for this? I'm still getting the same error. Should we explicitly set the $GITHUB_STEP_SUMMARY variable?

@catthehacker @cplee can you respond on this?

**Comment by jsoref** [comment]
If you run with `act -r` , then you can use something like:
```sh
(act_docker_pid=$(docker ps|perl -ne 'next unless s{\s.*"tail -f /dev/null".*act-.*}{};print'|tail -1); docker exec $act_docker_pid cat /var/run/act/workflow/SUMMARY.md; do
cker rm -f $act_docker_pid)
```
