### ISSUE TITLE
Github Security Lab: GHSL-2023-004

### ISSUE THREAD

**Issue by Kwstubbs** [nektos/act#1553]
### Bug report info

The GitHub Security Lab team has identified a potential security vulnerability in act.
We have sent a security report to cplee@nektos.com on January 9, 2023 as there was no published security contact. 
Please let us know if there is a better point of contact for security issues. We highly recommend sending security reports over a private communication channel.

### Command used with act

```sh
Private
```

### Describe issue

Private

### Workflow content

```yml
Private
```

### Relevant log output

```sh
Private
```

**Comment by cplee** [comment]
@Kwstubbs - i received your email and will follow up over private channel.

**Comment by cplee** [comment]
Created PR with fix: https://github.com/nektos/act/pull/1565

**Comment by cplee** [comment]
Fixed in #1565
