### ISSUE TITLE
Unable to use Proxy in act - Containers

### ISSUE THREAD

**Issue by Vaitheesh-SS** [nektos/act#1578]
### Discussed in https://github.com/nektos/act/discussions/1570

<div type='discussions-op-text'>

<sup>Originally posted by **Vaitheesh-SS** January 22, 2023</sup>
Hello!,

I'm trying to run a local test actions on my VM using nektos/act and I'm facing issues in reaching internet especially `Failed to fetch http://archive.ubuntu.com/ubuntu/dists/focal/InRelease Could not resolve 'archive.ubuntu.com` through my Proxy configured on my Ubuntu VM. The docker containers spin from act is unable to inject the Proxy Env's which I defined in `~/.docker/config.json` but this works well when creating containers using docker cli

`HTTPS_PROXY=http://localhost:3128
HTTP_PROXY=http://localhost:3128` -- also tried with VM IP {ex: http://10.2.0.100:3128}

Also tried with `act -j deploy --env HTTP_PROXY=http://localhost:3128/ --env HTTPS_PROXY=http://localhost:3128/` - no luck !</div>

**Comment by shubhbapna** [comment]
I had a similar issue. Turns out a lot of services use the lower case version of these variables. Setting `http_proxy` instead of `HTTP_PROXY` worked for me

**Comment by sysid** [comment]
For me on mac this is working:
`act --env https_proxy=http://host.docker.internal:3128 --env http_proxy=http://host.docker.internal:3128`

**Comment by Wenzel** [comment]
Hi,

I'm facing the same issue as @Vaitheesh-SS today.
When I started a container myself: `docker run -ti --rm ubuntu:22.04`

my proxy settings defined in `~/.docker/config.json` are injected into the environment

but when I use `act`, they have disappeared ?

Could we avoid specifying the proxy values on the command-line, and rely on Docker configuration standards ?

**Comment by Vaitheesh-SS** [comment]
> Hi,
> 
> I'm facing the same issue as @Vaitheesh-SS today. When I started a container myself: `docker run -ti --rm ubuntu:22.04`
> 
> my proxy settings defined in `~/.docker/config.json` are injected into the environment
> 
> but when I use `act`, they have disappeared ?
> 
> Could we avoid specifying the proxy values on the command-line, and rely on Docker configuration standards ?

Hi, I don't think that is currently possible with act cli.

**Comment by Wenzel** [comment]
@Vaitheesh-SS just found the solution yesterday, using `--container-options`:

`act --container-options '--mount type=bind,source=/home/mtarral/.docker/config.json,target=/root/.docker/config.json'`

**Comment by Vaitheesh-SS** [comment]
Thanks for posting here, I quit using act cli now, are there any good improvements from the community now? or did you come across better tools to run GitHub actions workflows locally in Linux environment?
