### ISSUE TITLE
Support for ssh remote workflows (and actions) or using git config

### ISSUE THREAD

**Issue by mbrancato** [nektos/act#1588]
### Act version

act version 0.2.40-14-g932863b

### Feature description

I'm using a build from `master` that contains the [new feature for remote workflows](https://github.com/nektos/act/pull/1525). The remote workflows are hard coded to use HTTPS, and I need SSH support.

https://github.com/nektos/act/blob/82a8c1e80dfcd73842bc0359ca8447303b6fcc08/pkg/runner/reusable_workflow.go#L109

Normally I would use the `insteadOf` config to fix this but it didn't seem to work.

```shell
git config --global url."ssh://git@github.com/".insteadOf "https://github.com/"
```

```shell
% act pull_request
[build-test-release.yaml/MyWorkflow]   ☁  git clone 'https://github.com/myorg/reusable-workflows' # ref=my_branch
[build-test-release.yaml/MyWorkflow] Unable to clone https://github.com/myorg/reusable-workflows refs/heads/my_branch: authentication required
Error: authentication required
```

However, if I manually clone it, the `insteadOf` config works fine. I noticed the clone is not run in a container, so I'm not sure if it is otherwise ignoring the global git config.

```shell
% git clone 'https://github.com/myorg/reusable-workflows'
Cloning into 'reusable-workflows'...
remote: Enumerating objects: 1183, done.
remote: Counting objects: 100% (360/360), done.
...
```

**Comment by mbrancato** [comment]
a workaround for this is to manually checkout the repo, then checkout the ref. 

```shell
git clone https://github.com/{{org}}/{{repo}} ~/.cache/act/{{org}-{{repo}}-.github-workflows-{{workflow_filename}}@{{ ref | replace("/", "-")}}/
cd ~/.cache/act/{{org}-{{repo}}-.github-workflows-{{workflow_filename}}.yaml@{{ ref | replace("/", "-")}}/
git checkout {{ref}}
```

**Comment by mbrancato** [comment]
I noticed this is lacking for remote actions as well that require SSH. The workaround does not work for the remote actions.

**Comment by qbx2** [comment]
Why not clone using `GITHUB_TOKEN` ? `gh-cli` already supports to clone using `GITHUB_TOKEN`. https://cli.github.com/manual/gh_repo_clone

**Comment by marcelarie** [comment]
act -s GITHUB_TOKEN=$GITHUB_TOKEN does not work for me.

It returns:
```
WARN  ⚠ You are using Apple M-series chip and you have not specified container architecture, you might encounter issues while running act. If so, try running it with '--container-architecture linux/amd64'. ⚠
[qa/🕵️ Quality Assurance/🕵️ Quality Assurance          ]   ☁  git clone 'https://github.com/stuartapp/mc-gh-actions' # ref=main
[qa/🕵️ Quality Assurance/🕵️ Quality Assurance          ] Unable to clone https://github.com/stuartapp/mc-gh-actions refs/heads/main: authorization failed
Error: authorization failed```
