### ISSUE TITLE
Add support for variable GITHUB_RUN_ATTEMPT

### ISSUE THREAD

**Issue by fabienmazieres** [nektos/act#1615]
### Act version

act version 0.2.42

### Feature description

Please add support for the default environment variable GITHUB_RUN_ATTEMPT as it can be used to generate build numbers
<html>
<body>

GITHUB_RUN_ATTEMPT | A unique number for each attempt of a particular workflow run in a repository. This number begins at 1 for the workflow run's first attempt, and increments with each re-run. For example, 3.
-- | --

</body>
</html>

**Comment by KnisterPeter** [comment]
You can define the value by yourself with calling act like this:

`act --env GITHUB_RUN_ATTEMPT=123 ...`
