### ISSUE TITLE
[Proposal] Support cache

### ISSUE THREAD

**Issue by wolfogre** [nektos/act#1652]
Support using `actions-cache@v3`.

There's a basic implementation for cache in act_runner(the CICD runner of Gitea, based on act). See https://gitea.com/gitea/act_runner/pulls/25 .  And it seems to be working well so far. 

It's an independent module, so I think it's not difficult to port it to act. However, I'm not sure if act really needs it, so I need some feedback from the maintainers before I do anything.

Related to https://github.com/nektos/act/issues/1513 .

**Comment by AgentEnder** [comment]
This would be pretty cool! I use the cache as a sort of ephemeral storage so it would be neat to use act with it

**Comment by IvanRibakov** [comment]
Definitely need this feature. Without it workflows building projects with a lot of dependencies of with slow compilation times become unusable locally which breaks one of the key ideas behind Act to provide shorter feedback cycle. 

From the looks of https://github.com/nektos/act/issues/1513 it seems people are having issues with 3rd party workarounds, so it would be nice if Act supported caching natively.

**Comment by smerschjohann** [comment]
I extracted the gitea implementation from their act_runner and put them in a standalone executable: https://github.com/smerschjohann/act-cache

As it is an internal package, I had to copy the implementation over. So far it works good.

**Comment by wolfogre** [comment]
I am working on it. I want to use the same tech stack as act, so there is still some work left.

**Comment by smerschjohann** [comment]
Thanks! You do a great job :) I just couldn't wait ;)

**Comment by damccull** [comment]
So how do we use this cache now? I'm using catthehacker/ubuntu:full-latest atm.

**Comment by wolfogre** [comment]
> So how do we use this cache now? I'm using catthehacker/ubuntu:full-latest atm.

You could update the act to the latest version and follow the [usage](https://github.com/actions/cache/blob/main/README.md) of actions/cache.
