### ISSUE TITLE
Support artifacts

### ISSUE THREAD

**Issue by sandorex** [nektos/act#169]
It would be really helpful if artifacts could be supported

**Comment by SteadBytes** [comment]
:+1: For artifacts, or perhaps at the very least produce and explicit warning/error when used. AFAICT a step using the artifact actions will succeed but no artifact will be uploaded/downloaded.

**Comment by cplee** [comment]
Great call, good feature to add.  Anyone have a sample workflow to use?

**Comment by jromero** [comment]
This is use case we have in [`buildpacks/pack`](https://github.com/buildpacks/pack/blob/master/.github/workflows/build.yml). We ultimately want to run test and build always but then only use the artifacts for a release workflow.

The source can be found here:
Upload:
https://github.com/buildpacks/pack/blob/c9745af053eabf812bf2fdab1695488a01022093/.github/workflows/build.yml#L77-L81

Download:
https://github.com/buildpacks/pack/blob/c9745af053eabf812bf2fdab1695488a01022093/.github/workflows/build.yml#L92-L95

**Comment by zaguiini** [comment]
Is there any progress?

**Comment by jromero** [comment]
Typically these artifacts are shipped via the gh API and the referenced by url.

I don't know how other parts, if any, work with mocking or intercepting GH API calls but I would think that is necessary to properly mock this locally. Am I wrong?

**Comment by krailler** [comment]
How works actions/cache? Seems similar no?

**Comment by wyTrivail** [comment]
we also have the same issue while using upload-artifacts,  we got the error 
```
[CI/build]   💬  ::debug::Root artifact directory is /github/workspace/build
[CI/build]   ❗  ::error::Unable to get ACTIONS_RUNTIME_TOKEN env variable
[CI/build]   ❌  Failure - Upload
```

it would be if it can be mocked.

**Comment by wagenet** [comment]
Seems like this should have remained open. It's a pretty big blocker for full use.

**Comment by ayozemr** [comment]
Artifacts if one of those key actions that many workflows use, and bc of that its a blocker for local dev working... Having this along with cache support would make act the tool we all need to fully develop workflows locally, instead of running workflows  to try things and waiting a lot of time

**Comment by ayozemr** [comment]
Still waiting for this :-(

**Comment by CatTheHacker** [comment]
It's a bit complicated since https://github.com/nektos/act/issues/329

**Comment by nicolo-ribaudo** [comment]
Sorry bot, I hate to just :+1: issues

**Comment by CreMindES** [comment]
Sorry bot, I hate to just +1 issues, but it's necessary in this case.

**Comment by Smana** [comment]
Hey, we still need a solution, either an artifact server or a mock.

**Comment by catthehacker** [comment]
@Smana see #329

**Comment by volleynerd** [comment]
> 👍 for supporting artifacts. Or at the very least it could be helpful to produce an explicit warning/error when these actions are used. AFAICT, a step using the artifact actions will succeed but no artifact will be uploaded/downloaded.

The above is not true for me. Running 0.2.23 and seeing actions/upload-artifact fail with error **::error::Unable to get ACTIONS_RUNTIME_TOKEN env variable** 

Agree that this is a great idea to support the goal - for typical workflows that run fine in GH will run in ACT without modification.

**Comment by Qard** [comment]
Developing custom actions is really difficult without this. I hope act will get artifact support eventually.

**Comment by JoshMcCullough** [comment]
I know this feature exists now, but I'm still getting the "unable to get ACTIONS_RUNTIME_TOKEN" error. I wonder if I'm missing something?

I set up the artifact path/port in my `act` call. I'm using act-js.

**Comment by mcascone** [comment]
> I know this feature exists now, but I'm still getting the "unable to get ACTIONS_RUNTIME_TOKEN" error. I wonder if I'm missing something?
> 
> I set up the artifact path/port in my `act` call. I'm using act-js.
> 
> NM, I see this now on the related PR: `--env ACTIONS_RUNTIME_TOKEN=foo` must be set (we do not have authentication implemented)

i set this, using `foo` (probably incorrect), and now I get: 
`Error: authentication required`
