### ISSUE TITLE
Add customizable "network" option.

### ISSUE THREAD

**Issue by ScionOfDesign** [nektos/act#1696]
### Act version

v0.2.43

### Feature description

My workflow has multiple jobs which run in parallel. In GitHub, each runner/job is on its own network. In act, however, the jobs share the same "host" network as can be seen here: https://github.com/nektos/act/blob/master/pkg/runner/run_context.go#L263

The _problem_ is that there are many networking ports being used on the host machine, leading to intermittent port conflicts causing failures.

Passing in a new network option to a container within the workflow doesn't seem to work.

**Comment by ScionOfDesign** [comment]
Ok thanks, that fixes my problem. I didn't realize that:
```yaml
container:
      image: catthehacker/ubuntu:act-latest
 ```
would also override the `--container-options`.
In fact, I thought that `--container-options` **only** applied to steps that had a `container:` attribute.

**Comment by eljohnson92** [comment]
I've tried testing this and it seems to work adding the options to the yaml directly with ACT, but `--network` is not supported by GHA runners. it would be nice if --container-options could work even if a container image was provided
