### ISSUE TITLE
RUNNER_OS is not defined

### ISSUE THREAD

**Issue by djspiewak** [nektos/act#171]
It appears that GitHub added the environment variable, `RUNNER_OS`, as an alias for `${{ runner.os }}` sometime quite recently, and a few actions already depend on it (notably `olafurpg/setup-scala@v5`). Those actions fail within `act`.

**Comment by cplee** [comment]
fixed in https://github.com/nektos/act/commit/a9533b05ce708a84e931d63cb2cd7b795e70bbe2
