### ISSUE TITLE
Conflict: container name already in use

### ISSUE THREAD

**Issue by greg0ire** [nektos/act#174]
When trying to run `act` on https://github.com/doctrine/sql-formatter, I'm getting this output:

```
[Continuous Integration/Static Analysis with Psalm  ] 🚀  Start image=node:12.6-buster-slim
[Continuous Integration/Unit tests-1                ] 🧪  Matrix: map[php-version:7.2]
[Continuous Integration/Unit tests-1                ] 🚀  Start image=node:12.6-buster-slim
[Continuous Integration/Coding Standards            ] 🧪  Matrix: map[php-version:7.2]
[Continuous Integration/Coding Standards            ] 🚀  Start image=node:12.6-buster-slim
[Continuous Integration/Unit tests-2                ] 🧪  Matrix: map[php-version:7.3]
[Continuous Integration/Unit tests-2                ] 🚀  Start image=node:12.6-buster-slim
[Continuous Integration/Unit tests-3                ] 🧪  Matrix: map[php-version:7.4]
[Continuous Integration/Unit tests-3                ] 🚀  Start image=node:12.6-buster-slim
[Continuous Integration/Static Analysis with PHPStan] 🚀  Start image=node:12.6-buster-slim
Error: Error response from daemon: Conflict. The container name "/act-Continuous-Integration-Sta" is already in use by container "a09e515b212dcc32454ee2ddf11e5a8f56556d5179df6af90659f3d0efedde50". You have to remove (or rename) that container to be able to reuse that name.
```

Note how I have a workflow named `Continuous Integration/Static Analysis with Psalm`, and another named `Continuous Integration/Static Analysis with PHPStan`. A fix might be to append a hash of the workflow name to the container name, dunno why it's truncated in the first place though. Is there a limit to the length of docker container names?

**Comment by mwang87** [comment]
I ran into this as well. Basically, there is a fixed length they use for the container name. One solution from my side was to shorten the name of workflow name. Not perfect but does work.

**Comment by greg0ire** [comment]
I think the place where to fix this might be in this piece of code:

https://github.com/nektos/act/blob/4a4bd36cf65b36bb12ddad4d8379cd24b2384885/pkg/runner/run_context.go#L276-L298

**Comment by cplee** [comment]
thanks @albertofem for the PR, merged!

**Comment by displague** [comment]
I encountered the same error message, but it was due to stale images.

I used `docker rm` on the container that was cited in the error message, and then
`docker system prune --volumes --all` to get things back in order.
