### ISSUE TITLE
Docker daemon is not running?

### ISSUE THREAD

**Issue by seed-of-apricot** [nektos/act#176]
I installed the act and can run the action with success.

```node
>act -n
*DRYRUN* [build-test/test] �🚀  Start image=node:12.6-buster-
im
*DRYRUN* [build-test/test]   �🐳  docker run image=node:12.6-
ster-slim entrypoint=["/usr/bin/tail" "-f" "/dev/null"] cmd=[]
*DRYRUN* [build-test/test] ⭐  Run actions/checkout@v2        
*DRYRUN* [build-test/test]   ✅  Success - actions/checkout@v2

*DRYRUN* [build-test/test] ⭐  Run ./
*DRYRUN* [build-test/test]   ✅  Success - ./
```

But when I `act -p`, it says:

```node
>act -p
[build-test/test] �🚀  Start image=node:12.6-buster-slim
Error: error during connect: This error may indicate that the docker daemon is not running.: Post http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/images/create?fromImage=node&tag=12.6-buster-slim: open //./pipe/docker_engine: The system cannot find the file specified.
```

Am I fine to go or do I still need to do something? 🤔

**Comment by bigzoo** [comment]
Facing a similar issue. Running on Windows 10 Build 19041.207, WSL, with Ubuntu 20.04 and installed docker via `sudo apt-get install docker.io`. Running `docker -v` I get version 19.03 but act errors out with the message
```
Error: unable to determine if image already exists for image "node:12.6-buster-slim": Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```
Any suggestions ?

**Comment by bigzoo** [comment]
This is actually a problem with my docker installation, can't get systemctl and the process running correctly and not really related to act in any way.

**Comment by p3palazzo** [comment]
@bigzoo did you find a solution? I have docker running and act outputs the same error you get.

**Comment by jtich** [comment]
Make sure docker is running 😉

**Comment by bigzoo** [comment]
Update, I was able to fix act running on Ubuntu in Windows WSL by installing docker [the wsl way](https://docs.docker.com/docker-for-windows/wsl/)

**Comment by GustavoFenilli** [comment]
> Make sure docker is running 😉

I think the documentation could have a requirements, as it states that it uses the Docker API, but it does not specify that you need an installation of Docker.

**Comment by Delta456** [comment]
Yes please else it will create a lot of confusions.
