### ISSUE TITLE
Support Docker with SSH authentication

### ISSUE THREAD

**Issue by AlexGustafsson** [nektos/act#18]
I noticed remote Docker support was more or less fixed somewhere after #5, but it does not seem to work for hosts that I connect to over SSH. Since Docker 18.09 there's been support to use `docker -H ssh://me@server`. Is there any way that could work with this project as well?

Error I get for reference:
```
Error: error during connect: Post http://alex%40192.168.xx.xx/v1.39/images/create?fromImage=node&tag=11.6.0: dial tcp: lookup alex@192.168.xx.xx: no such host
```

```
macOS 10.13.6 (17G5019)
sample repo from README: https://github.com/cplee/github-actions-demo
```

**Comment by cplee** [comment]
@AlexGustafsson have you tried setting env variable like `DOCKER_HOST=ssh://me@server`

**Comment by SvenDowideit** [comment]
I get a very similar result from setting DOCKER_HOST

```
dow184@TOWER-SL:~/src/github/act$ echo $DOCKER_HOST
ssh://onacitest
dow184@TOWER-SL:~/src/github/act$ docker info | grep onacitest
WARNING: No swap limit support
Name: onacitest
dow184@TOWER-SL:~/src/github/act$ make
go run main.go -ra check
[check] docker build -t check:1f5cf30 /home/dow184/src/github/act/.github/actions/check
Error: error during connect: Post http://onacitest/v1.24/build?buildargs=null&cachefrom=null&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=&labels=null&memory=0&memswap=0&networkmode=&rm=0&shmsize=0&t=check%3A1f5cf30&target=&ulimits=null&version=: dial tcp: lookup onacitest on 127.0.0.53:53: server misbehaving
exit status 1
Makefile:20: recipe for target 'check' failed
make: *** [check] Error 1
```

**Comment by SvenDowideit** [comment]
Actually, I think this is isn't going to work with the current way the code works.

From what I can see, your repository is bind-mounted into the container - which means that it only supports "local" Docker daemons (where Docker for windows and Docker for Mac are considered "local")

**Comment by SvenDowideit** [comment]
playing with it in #19
