### ISSUE TITLE
Error parsing hyphenated variables

### ISSUE THREAD

**Issue by rick-de-water** [nektos/act#181]
I have a variable in my matrix called `cxx-version`, which is parsed as `version` in expressions. This results in the following error:

> time="2020-04-01T13:15:28+02:00" level=error msg="Unable to interpolate string 'cmake -DCMAKE_BUILD_TYPE=${{ matrix.config }} -DLINGO_TEST_CXX_VERSION=${{ matrix.cxx-version }} -DLINGO_WARNINGS_AS_ERRORS=ON -DLINGO_SANITIZE=ON ../source' - [ReferenceError: 'version'* is not defined]"
> | /github/workflow/2: line 2: -DCMAKE_BUILD_TYPE=${{ matrix.config }}: bad substitution

Renaming it to something without a hyphen fixes the error.

The workflow file I used can be found [here](https://github.com/rick-de-water/Lingo/blob/master/.github/workflows/lingo.yml).

**Comment by icarcal** [comment]
@rick-de-water check the discussion at #104

**Comment by rick-de-water** [comment]
The array indexing workaround does the job for now. I'll close this one since it's a duplicate.
