### ISSUE TITLE
Folder is persisted across runs

### ISSUE THREAD

**Issue by Sygmei** [nektos/act#186]
If I create a simple folder inside the cloned repository with the `mkdir some_folder` command and I try to re-run the script, it will fail with the following error :

`mkdir: cannot create directory 'some_folder': File exists`

Is this the expected behaviour ? Is there a way to clean the "cache" ?

**Comment by chrislow** [comment]
Got the same problem. The should be flag for clearing the cache / rebuild the image on very run?

**Comment by cplee** [comment]
there is a volume created for each job.  it _should_ get cleared after each job, but seems there may be situations in which the volume isn't being removed
