### ISSUE TITLE
Bad docs/help: Include --pull=false as a possibility

### ISSUE THREAD

**Issue by dheerajbhaskar** [nektos/act#1896]
### Bug report info

```plain text
Problem: Did know how to turn off the default -p flag

https://github.com/nektos/act/issues/1633#issuecomment-1435718418

> Use `--pull=false`. The reason that this flag now defaults to true is a breaking change in act with older default docker images.
> 
> You have to manually keep uptodate, if you use this flag.

Can we update the help text to show that you can pass false like this? it's not clear in the help text of the command or the README
```

### Command used with act

```sh
`act`

Did know how to turn off the default -p flag
```

### Describe issue

Problem: Did know how to turn off the default -p flag

https://github.com/nektos/act/issues/1633#issuecomment-1435718418

> Use `--pull=false`. The reason that this flag now defaults to true is a breaking change in act with older default docker images.
> 
> You have to manually keep uptodate, if you use this flag.

Can we update the help text to show that you can pass false like this? it's not clear in the help text of the command or the README 

### Workflow content

```yml
not relevant
```

### Relevant log output

```sh
not relevant
```

**Comment by taytzehao** [comment]
@cplee , it seems that this highlights the bigger issue as act has no centralized way of documenting command flags and showing when it can be used.

The closest thing to that is the Example commands section in the ReadMe and a couple more flags scattered throughout the document. It would take a few reads for a user to realize that the `pull` flag is not here. I would wish to propose creating a flags.md file to document them all with a link to it from README.md
