### ISSUE TITLE
`winget`, `scoop`, and `choco` versions are out of date

### ISSUE THREAD

**Issue by adamgranthendry** [nektos/act#1952]
### Bug report info

```plain text
Installing `act` from `winget`, `scoop`, or `choco` downloads version `0.2.26`. The latest release is `0.2.49`.
```

### Command used with act

```sh
N/A
```

### Describe issue

Windows package managers install the latest release of `act`.

### Workflow content

```yml
N/A
```

### Relevant log output

```sh
N/A
```

### Additional information

Please push the latest release to `winget`, `scoop`, and `choco`.

**Comment by adam-grant-hendry** [comment]
Let's keep this going +1
