### ISSUE TITLE
Allow node20 in action.yml as action runtime

### ISSUE THREAD

**Issue by ChristopherHX** [nektos/act#1967]
### Act version

v0.2.49

### Feature description

See https://github.com/actions/runner/releases/tag/v2.308.0

Since act doesn't care about the version behind `node` why not just exec all `node<number>` via `node`?

**Comment by gilzow** [comment]
Just ran into this issue as well where one of the actions in my workflow has updated to node20, but act now reports:

```
The runs.using key in action.yml must be one of: [composite docker node12 node16], got node20
```
and fails the action

**Comment by mahmudz** [comment]
Same issue here

`
Error: The runs.using key in action.yml must be one of: [composite docker node12 node16], got node20
`
OS: Mac 15 Sonoma Beta 7
Act Version: 0.2.50
Docker Version: 4.21.1

**Comment by MichelFR** [comment]
Same issue here, any workaround?
Using in gitea actions

**Comment by mahmudz** [comment]
@MichelFR Whats the procedure?

**Comment by NexZhu** [comment]
@MichelFR Same issue here. Could you explain in detail?

**Comment by teffcz** [comment]
I have same problem with 
"The runs.using key in action.yml must be one of: [composite docker node12 node16 go], got node20" 

running basic CI job for building docker image using:
docker/setup-qemu-action@master
docker/setup-buildx-action@master
docker/login-action@master
docker/build-push-action@master

with docker image ghcr.io/catthehacker/ubuntu:act-20.04, but i tried sereval others (even node:20-bullseye) and nothing helped

from logs it looks it is failing at check docker/setup-qemu-action@master

**Comment by jcarpenter12** [comment]
> > Same issue here, any workaround? Using in gitea actions
> > Edit:
> > Okay found a workaround for now, needed to turn all versions back of the actions
> 
> Can you tell me how to apply this workaround?

I had this issue this morning but the new version of act now supports node20 so it now works after upgrading act, unless I have misunderstood your question
