### ISSUE TITLE
How close to GitHub is this, really?

### ISSUE THREAD

**Issue by dabrahams** [nektos/act#1979]
### Details

Before trying to use act, I really want to know how much of its functionality depends on code GitHub provides, and how much is its authors' best attempt at reverse-engineering GitHub actions from their docs and black-box testing… or is there some alternative I've not considered?  I can't find this information.

I actually think it should go in the README rather than the Wiki, FWIW.

**Comment by GuessWhoSamFoo** [comment]
https://github.com/aweris/gale is another alternative although it has a dependency on `act`.
