### ISSUE TITLE
Tool cache is not in effect

### ISSUE THREAD

**Issue by linhr** [nektos/act#1987]
### Bug report info

```plain text
act version:            0.2.49
GOOS:                   darwin
GOARCH:                 arm64
NumCPU:                 8
Docker host:            DOCKER_HOST environment variable is not set
Sockets found:
	/var/run/docker.sock
Config files:
	.actrc:
		-P ubuntu-latest=catthehacker/ubuntu:act-latest
		-P ubuntu-22.04=catthehacker/ubuntu:act-22.04
		-P ubuntu-20.04=catthehacker/ubuntu:act-20.04
		-P ubuntu-18.04=catthehacker/ubuntu:act-18.04
Build info:
	Go version:            go1.20.6
	Module path:           command-line-arguments
	Main version:          
	Main path:             
	Main checksum:         
	Build settings:
		-buildmode:           exe
		-compiler:            gc
		-ldflags:             -X main.version=0.2.49
		CGO_ENABLED:          1
		CGO_CFLAGS:           
		CGO_CPPFLAGS:         
		CGO_CXXFLAGS:         
		CGO_LDFLAGS:          
		GOARCH:               arm64
		GOOS:                 darwin
Docker Engine:
	Engine version:        24.0.5
	Engine runtime:        runc
	Cgroup version:        2
	Cgroup driver:         cgroupfs
	Storage driver:        overlay2
	Registry URI:          https://index.docker.io/v1/
	OS:                    OrbStack
	OS type:               linux
	OS version:            
	OS arch:               aarch64
	OS kernel:             6.4.8-orbstack-00059-g106c60a3471f
	OS CPU:                8
	OS memory:             9937 MB
	Security options:
		name=seccomp,profile=builtin
		name=cgroupns
```

### Command used with act

```sh
act
```

### Describe issue

The tool cache location has been changed to `/opt/hostedtoolcache` after <https://github.com/nektos/act/pull/103>. However, the named volume `act-toolcache` is still mounted on `/toolcache`. Here is the code:

<https://github.com/nektos/act/blob/0c12273ebaa937c52dea06d91b8985304874ab14/pkg/runner/run_context.go#L124-L127>

Therefore, it seems that the Docker volume for tool cache is not in use. I have attached a sample workflow which uses `actions/setup-node@v3`. In the output we can see that the tool cannot be retrieved from the cache even if the action has been used before.

I figured out that I can work around this issue by adding `--container-options "-v act-toolcache:/opt/hostedtoolcache"` to the command line options, but I wonder if this is a bug that should be fixed in the code.

I'm new to this repository so I may have missed something. BTW, thanks for creating this awesome project!

### Workflow content

```yml
name: Sample Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.17.1'
          cache: 'npm'
```

### Relevant log output

```sh
[Sample Workflow/build]   🐳  docker exec cmd=[node /var/run/act/actions/actions-setup-node@v3/dist/setup/index.js] user= workdir=
[Sample Workflow/build]   💬  ::debug::isExplicit: 18.17.1
[Sample Workflow/build]   💬  ::debug::explicit? true
[Sample Workflow/build]   💬  ::debug::checking cache: /opt/hostedtoolcache/node/18.17.1/arm64
[Sample Workflow/build]   💬  ::debug::not found
| Attempting to download 18.17.1...
```

**Comment by lawndoc** [comment]
It looks like @KnisterPeter tried to address this over a year ago in https://github.com/nektos/act/pull/1494, but the PR has gone stale. Any way we can get this merged?

**Comment by lawndoc** [comment]
I'm currently facing this issue way downstream in Gitea's act runners

**Comment by lawndoc** [comment]
Looks like #1494 was merged, so this issue should be resolved

**Comment by claui** [comment]
Confirming that the v0.2.58 release has fixed this.
