### ISSUE TITLE
Question:  Is it possible to not use a local push.json file?

### ISSUE THREAD

**Issue by awentzel** [nektos/act#216]
Is there a command parameter that can be used instead of creating and managing a GitHub Events file.  In my case `push.json`?

The problem Is that we're not comfortably hosting that file in our repository since it points to local user branches and that will frequently be changing.

The preferred solution would be to supply the git branch name as a parameter.

Example Problem file:
```bash
{
    "push": {
      "head": {
        "ref": "users/foo/update-action"
      },
      "base": {
        "ref": "users/foo/update-action"
      }
    }
  }
```

Example solution where `-b` is git branch name.
```bash
act -j build_local_linux -e "push" -b "users/foo/update-action"
```

**Comment by catthehacker** [comment]
```bash
act push -j build_local_linux --defaultbranch "users/foo/update-action"
```
