### ISSUE TITLE
Job is not ran using runner user

### ISSUE THREAD

**Issue by kenorb** [nektos/act#219]
When running job locally, the action is run using `root`, on GitHub workflow, it's `runner` user:

> `uid=1001(runner) gid=116(docker) groups=116(docker)`

This difference can affect the job results.

**Comment by tobernguyen** [comment]
> Yes I'm experiencing some permission issues when running a global npm command like `yo`. `yo` doesn't have permission to create/modify files in github workspace.

I just found that the problem I'm having is because when act copy working directory from local to the container (via checkout@v2 action), it doesn't chmod the dirs/files to correct owners (user and group), it just keep filers/folders' ownership the same with what is in local.
