### ISSUE TITLE
Support interpolation and ENV lookup in If: conditionals

### ISSUE THREAD

**Issue by torbjornvatn** [nektos/act#224]
I found my self wanting to use ENVs in if conditionals in my build and deployment workflows.
But act doesn't have the ENV map available in RunContext when `EvalBool` evaluates the conditional.

**Comment by torbjornvatn** [comment]
Have made a PR over in #225

**Comment by ethan797979** [comment]
I want to unsubscribe this.




於 星期一, 5月 4, 2020, 21:15，Torbjørn Vatn <notifications@github.com> 寫道：




Have made a PR over in #225

**Comment by ethan797979** [comment]
Please help me to unsubscribe it.




於 星期一, 5月 4, 2020, 21:15，Torbjørn Vatn <notifications@github.com> 寫道：




I found my self wanting to use ENVs in if conditionals in my build and deployment workflows.
But act doesn't have the ENV map available in RunContext when EvalBool evaluates the conditional.
