### ISSUE TITLE
Support running Azure Pipelines

### ISSUE THREAD

**Issue by fwilhe** [nektos/act#244]
Hi @cplee 

this is a suggestion where I would like if it is worth doing it. The basic idea is to extend the scope to also allow execution of [azure yaml pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema%2Cparameter-schema).

Why do I think this would be worth it?

* Azure and GitHub Actions are quite similar in how they work. The yaml format is different, but for simple cases it is "just" a matter of different structure [cf converter tool](https://github.com/samsmithnz/AzurePipelinesToGitHubActionsConverter). The same virtual machine images are used. I think the effort should not be the same as writing a whole new tool for that purpose.
* Azure pipelines already has an on-prem offering that GitHub Actions does not yet have, which is a big factor for corporate adoption. Also, azure seems to be more likely to be adopted by big corporations because of how accepted the "microsoft" brand is (my personal impression).

This could potentially be very useful for developers in such orgs, maybe even a source for new contributors.

Rough list of things that would need to be supported (I did not research this, just off the top of my head):

* Different yaml format needs to be parsed
* Different environment variables need to be set/read
* Probably more

Any opinions?

I can't promise anything, but I would be open to contributing to this feature if it is accepted.

**Comment by cplee** [comment]
This is a great idea @fwilhe - not sure if it helps, but i wrote a blog on the similarities here: https://www.liatrio.com/blog/github-actions
