### ISSUE TITLE
Add support for scheduled workflows

### ISSUE THREAD

**Issue by aaronmeder** [nektos/act#245]
Hi there!

It seems like at the moment act does ignore a workflow that has  an `on: schedule` trigger.

Example trigger:
`on:
    schedule:
      - cron:  '0 */2 * * *'`

It would not list and cannot be run thereafter.

It would be helpful if these could be run too. Any set schedule could just be ignored, in my opinion.

What do you think about it?

Thanks for the great tool!
Aaron

**Comment by cplee** [comment]
Agreed @aaronmeder - this should be added.

**Comment by saliceti** [comment]
The scheduled job does not appear in `act -l` but I can run it fine with `act -j <job_name>`

**Comment by daxmc99** [comment]
Bump, this confused me the first time I used the tool

**Comment by hariso** [comment]
> Bump, this confused me the first time I used the tool

Same here!

**Comment by fharper** [comment]
It would be great to list them also when doing `act -l` no?
