### ISSUE TITLE
Git pull asks for credentials when using actions/checkout@v2

### ISSUE THREAD

**Issue by vibin** [nektos/act#248]
I'm using `actions/checkout@v2` which lets you run authenticated git commands like git pull.

On act, I get a prompt for login when running git pull but this works fine when running real Action. 

When running the real Action, I see `http.https://github.com/.extraheader=AUTHORIZATION: basic ***` in the git config - but this is missing when running with act.

**Comment by cplee** [comment]
dup of #233
