### ISSUE TITLE
Consider publishing act to winget packages repository

### ISSUE THREAD

**Issue by rodrigoscna** [nektos/act#253]
It would be nice to have act installed by just running `winget install act`.

**Comment by cplee** [comment]
Love the idea but I have no experience with `winget`...would love help with this one.

**Comment by rodrigoscna** [comment]
Looks like we need to wait until microsoft/winget-cli/issues/140 gets done.

**Comment by chrpai** [comment]
I'm not familiar with ACT.  Can you provide a link to it for me to investigate?

**Comment by chrpai** [comment]
I'd be willing to contribute a WiX MSI project to encapsulate act.exe as act.msi.  Then we could easily create the WinGet YAML.   We'd just need to get the code integrated into your CICD pipeline.  This should be easy since WiX is FOSS.

**Comment by suchal-riaz** [comment]
BUMP
