### ISSUE TITLE
doesn't seem to work with remote `DOCKER_HOST`

### ISSUE THREAD

**Issue by christopherhesse** [nektos/act#264]
`DOCKER_HOST="<hostname>:2375" docker ps` works fine

`DOCKER_HOST="<hostname>:2375" act` produces the following error:

```
Error: unable to determine if image already exists for image "node:12.6-buster-slim": unable to parse docker host `<hostname>:2375`
```

**Comment by christopherhesse** [comment]
Well I presume this still happens, seems like stale bot should ignore issues with labels like kind/bug

**Comment by christopherhesse** [comment]
@cplee It might be a good idea to have stale bot ignore tagged bugs

**Comment by cplee** [comment]
@christopherhesse bleh...I thought I tried. Obviously I need help with my stale issue action ☹️
