### ISSUE TITLE
Allow loading secrets from a .env file

### ISSUE THREAD

**Issue by patoroco** [nektos/act#279]
Hi,

currently `act` supports passing the secrets using the shell in two ways:

```bash
act -s SECRET=value

or

act -s SECRET
```
In the second option, if the `SECRET` environment variable exists, it will take that value, if not, it will prompt the user each time.

It would be really nice load these values directly from a `.env` file, what do you suggest?

**Comment by MAHDTech** [comment]
You can try this, works for both secrets and standard environment variables.

* Create a file to store the environment variable secrets

```bash
vim ~/.config/act.vault

# Example secret
MY_SECRET=12345
```

* Then run act and load the files with the variables
```bash
act \
    --env-file "${HOME}/.config/act.env" \
    --secret-file "${HOME}/.config/act.vault"
```

👍

**Comment by cplee** [comment]
thanks @MAHDTech!

@patoroco - can we close this?

**Comment by patoroco** [comment]
Oh, actually the @MAHDTech explanation is not a workaround, it's just what I was looking for! Than @MAHDTech!

BTW, the only reference that I've found related to that is this file: https://github.com/nektos/act/blob/2f395475b0ac4f5c0fb3d7c8b97a23d9214ea77b/pkg/runner/testdata/secrets/.actrc#L2

Maybe we could add a small mention to it in the README, what do you think?

**Comment by patoroco** [comment]
> thanks @MAHDTech!
> 
> 
> 
> @patoroco - can we close this?

Done! Thanks
