### ISSUE TITLE
Default user is unhelpful

### ISSUE THREAD

**Issue by sagebind** [nektos/act#28]
By default containers are run using the default user (usually root), which may produce files or artifacts owned by root. Instead we should run the containers under the current user (command line equivalent would be `--user $(id -u)`).

**Comment by cplee** [comment]
@sagebind maybe this should be added as an optional flag.  this was done intentionally to match the description of the GitHub Actions: https://developer.github.com/actions/creating-github-actions/accessing-the-runtime-environment/

> Note: GitHub actions must be run by the default Docker user (root).
