### ISSUE TITLE
[BUG] Can't use yarn

### ISSUE THREAD

**Issue by LKay** [nektos/act#280]
Whenever I try to call any `yarn` command the `act` returns an error and fails to execute: `Failed to replace env in config: ${{ inputs.auth-token }`. I tried to search trough existing issues, over the internet and nothing with this exact error pops up.

**Comment by Sumolari** [comment]
This happened to me, too.

Here's a sample workflow I'm trying to run:

```yml
name: Lint and test

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: NPM or Yarn install with caching
        uses: bahmutov/npm-install@v1.1.0
      - name: Run tests
        uses: Borales/actions-yarn@v2.3.0
        with:
          cmd: test
          auth-token: ${{ secrets.NPM_AUTH_TOKEN }}
```

And I try to run it using:

```bash
act -s NPM_AUTH_TOKEN=<MY_TOKEN_HERE> pull_request
```

Resulting in:

```
[Lint and test/build]   🐳  docker run image=act-borales-actions-yarn-v2-3-0:latest entrypoint=[] cmd=["test"]
yarn run v1.22.4
error An unexpected error occurred: "Failed to replace env in config: ${{ inputs.auth-token }".
info If you think this is a bug, please open a bug report with the information provided in "/github/workspace/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[Lint and test/build]   ❌  Failure - Run tests
```

**Comment by dunklesToast** [comment]
Facing the exact same issue

**Comment by izik1** [comment]
Thirding this with the above error

**Comment by fxnoob** [comment]
Have you guys found a solutions ?

**Comment by fxnoob** [comment]
Have you guys found a solution?

**Comment by Sumolari** [comment]
> Have you guys found a solution?

I didn’t. I ended up not using this tool :(

**Comment by chetbox** [comment]
I had the same problem but resolved it by switching to the `Large` image during `act` first-run.

You can do this be deleting `~/.actrc` then run `act` again.

**Comment by dunklesToast** [comment]
@chetbox yarn is not installed in the "slim" version. You can easily run `npm i -g yarn` as a separate step if you don't want to have 18Gb of Images on your PC :D However I think this is not related to this issue.

**Comment by audishos** [comment]
> I had to use `ubuntu:js-latest` instead of default `ubuntu:act-latest`. Here is where I noticed that the first one includes `yarn` as well: https://hub.docker.com/r/catthehacker/ubuntu.

Thanks for this! Just want to add that this is done with the `-P` or `--platform` flag since this wasn't immediately clear to me. This flag allows you to map the `runs-on` value to an image. Example mapping `ubuntu-latest` to `ubuntu:js-latest`:

```bash
act pull_request -P ubuntu-latest=ghcr.io/catthehacker/ubuntu:js-latest
```

**Comment by uccmen** [comment]
> > I had to use `ubuntu:js-latest` instead of default `ubuntu:act-latest`. Here is where I noticed that the first one includes `yarn` as well: https://hub.docker.com/r/catthehacker/ubuntu.
> 
> Thanks for this! Just want to add that this is done with the `-P` or `--platform` flag since this wasn't immediately clear to me. This flag allows you to map the `runs-on` value to an image. Example mapping `ubuntu-latest` to `ubuntu:js-latest`:
> 
> ```shell
> act pull_request -P ubuntu-latest=ghcr.io/catthehacker/ubuntu:js-latest
> ```

Oddly, this didn't work for me, today. So I had to use `-P ubuntu-latest=node:14` ...

**Comment by sbahman** [comment]
One can replace `.../catthehacker/ubuntu:act-latest` with `.../catthehacker/ubuntu:js-latest` in the `.actrc` file - then one does not need to specify it everytime.

**Comment by dunklesToast** [comment]
> How long does this take to download? I tried this a few times and my jobs hung.

The image is approx. 18GB large. Iirc act does not show the download progress but you can try pulling it via Docker manually and watch the progress there. Act should then use that image without any download steps.

**Comment by jlongman** [comment]
Also, if you're on a non-linux system I recommend doing a `docker pull imagename` outside of `act`.  If your VM runs out of disk space you won't see it otherwise.
