### ISSUE TITLE
BUG - 'fromJson' is not defined ReferenceError

### ISSUE THREAD

**Issue by Demmonius** [nektos/act#281]
Hi everyone,

First of all, thank you for this project it's useful.

I'm using Lighthouse to test my website and then I comment in a PR the report.
I get the report from the _step output_ but I need to "jsonify" it, by using **fromJson** function.

When I use:
```
${{ fromJson(steps.lighthouseCheck.outputs.lighthouseCheckResults).data[0].scores.accessibility }}
```

I get this error: `fromJson isn't defined ReferenceError: 'fromJson' is not defined`.
I also tried **fromJSON** but I got the same error.

This action fully works in Github Action.

Do you know how to fix this?

Thank you :)

**Comment by NicolasBonduel** [comment]
Same issue. I'm commenting to avoid the issue being closed.

**Comment by theowenyoung** [comment]
same problem...
