### ISSUE TITLE
(bug) fromJSON leading to a yaml unmarshal error

### ISSUE THREAD

**Issue by tzusman** [nektos/act#284]
This part of my GitHub Action workflow is confirmed to work on Github, but not through act:

```yaml
strategy:
  matrix: ${{ fromJson(needs.deployments.outputs.deployments) }}
```

```bash
act -l
```

```
Error: yaml: unmarshal errors:
  line 153: cannot unmarshal !!str `${{ fro...` into map[string][]interface {}
```

The `deployments` output looks something like this:
```json
[
  { "region": "us", "key": "value" },
  { "region": "eu", "key": "value2" }
]
```

**Comment by ssbarnea** [comment]
```
Error: yaml: unmarshal errors:
line 70: cannot unmarshal !!str `${{ mat...` into map[string]string
line 74: cannot unmarshal !!str `${{ mat...` into map[string]string
```

This is the first thing I got after reading about act and installing it, and that is more than an a month old.

I run it inside https://github.com/ansible/ansible-lint/blob/master/.github/workflows/tox.yml which does not even have any fromJson in it.

I hope someone looks over it because the act idea is brilliatn, but nobody wants a tool that crashes on first run.

**Comment by vecerek** [comment]
+1

**Comment by vecerek** [comment]
Bump

**Comment by ni4** [comment]
Got the same issue right after installing the act. Both error lines are like of the previous commenters:
`    env: ${{ matrix.env }}`
Not to mention that everything run smoothly via GHA.

**Comment by dsever** [comment]
Any workaround?

**Comment by plmercereau** [comment]
Well I'm still having this issue and it's a blocking one so I guess it shouldn't be closed

**Comment by ShayNehmad-RecoLabs** [comment]
This is also blocking for my workflow when working with the `FromJson` command to develop monorepo workflows:

```yaml
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        package: ${{ fromJson(needs.provide_packages_json.outputs.matrix) }}
```

Error:

```sh
❯ act -l
Error: yaml: unmarshal errors:
  line 88: cannot unmarshal !!str `${{ fro...` into []interface {}
```

**Comment by CatTheHacker** [comment]
@tzusman @ShayNehmad-RecoLabs could any of you provide full workflow that I can debug on?

**Comment by ShayNehmad-RecoLabs** [comment]
@CatTheHacker My example is based on https://tomasvotruba.com/blog/2020/11/16/how-to-make-dynamic-matrix-in-github-actions/

**Comment by lufia** [comment]
I think the cause of this error is that YAML parser expects the `matrix:` a map of array of empty interface. At parsing the workflow, the `matrix:` will not evaluate yet then the parser get an expression as a string. Therefore the parser cannot parse that workflow.

```go
type Strategy struct {
	FailFast    bool                     `yaml:"fail-fast"`
	MaxParallel int                      `yaml:"max-parallel"`
	Matrix      map[string][]interface{} `yaml:"matrix"`
}
// https://github.com/nektos/act/blob/master/pkg/model/workflow.go#L76
```

Would change the Matrix field from `map[string][]interface{}` to `interface{}` and type cast it every use?

**Comment by pablogs9** [comment]
+1
