### ISSUE TITLE
actions/cache@v2 error: Cache Service Url not found, unable to restore cache

### ISSUE THREAD

**Issue by grische** [nektos/act#285]
I am not sure how the cache is meant to work with nektos/act, but when working around bug #257, the cache will always throw a `cache-hit=false` with the following errors:
```
☁  git clone 'https://github.com/actions/cache' # ref=v2
🐳  docker cp src=/home/grische/.cache/act/actions-cache@v2 dst=/actions/
❓   ::save-state name=CACHE_KEY::Linux-2b7ee04efeb2a8c4ea27558750b1c2dee27f1692a30af56727638c98655a2410
💬  ::debug::Resolved Keys:
💬  ::debug::["Linux-2b7ee04efeb2a8c4ea27558750b1c2dee27f1692a30af56727638c98655a2410"]
💬  ::debug::Checking zstd --version
💬  ::debug::*** zstd command line interface 64-bits v1.3.3, by Yann Collet ***
💬  ::debug::getCacheEntry - Attempt 1 of 2 failed with error: Cache Service Url not found, unable to restore cache.
💬  ::debug::getCacheEntry - Attempt 2 of 2 failed with error: Cache Service Url not found, unable to restore cache.
| [warning]getCacheEntry failed: Cache Service Url not found, unable to restore cache.
⚙  ::set-output:: cache-hit=false
```

**Comment by benwinding** [comment]
Happens with `actions/cache@v1` too.

Seems that every test of a github action requires **_all_** npm modules to be installed....

Has anyone found a work around?

**Comment by rafilkmp3** [comment]
still searching anithin better than comment lines to use act

**Comment by quisse** [comment]
The `ACTIONS_CACHE_URL` is missing.

**Comment by benwinding** [comment]
Any progress on this? seems to be linked to #329

**Comment by grische** [comment]
I guess this can be tracked as part of #329

**Comment by BevanR** [comment]
Google search suggestions and results suggest that this is a popular topic and issue;

![image](https://user-images.githubusercontent.com/325176/144964022-2589061f-d5bb-4c2c-a13e-9a257cef909c.png)

![image](https://user-images.githubusercontent.com/325176/144964070-875c26e4-8627-4c14-850b-5b618bf4078b.png)

**Comment by BevanR** [comment]
If you are using nektos/act to develop GHA workflows locally and want to get `actions/cache` working so that you can get faster feedback when you test-run on your changes to GHA workflow yaml files;

1. #329 is a dead end. Do not bother reading the long thread.
   2. It is mostly about artifact upload/download actions, not cache actions.
2. Disable cache actions with `if: ${{ !env.ACT }}`
3. Use act's `--reuse` flag.

I will repeat that last step, because it is a much better solution than trying to get the cache action working locally;

# Use act's `--reuse` flag

From [the docs](https://github.com/nektos/act#flags); ` -r, --reuse     reuse action containers to maintain state`

**Cache saving and restoring becomes unnecessary.**

**Comment by netaskd** [comment]
@BevanR in this case we have to set `name:` field the same for each jobs, that uses `actions/cache`. Otherwise it does not work...

**Comment by guice** [comment]
>  3.  Use act's --reuse flag.
> 
> I will repeat that last step, because it is a much better solution than trying to get the cache action working locally;

As @netaskd as informed us, this only works if each job has the same `jobs.{id}.name:` value, which, as you may expect, not ideal. It would be nice if `--reuse` reused the contain for the whole workflow.

It seems `--reuse` keys on `jobs.{id}.name` for reuse.

**Comment by leumasme** [comment]
I am using a github action developed by someone else in my own action via `uses`. Their action includes `actions/cache`, causing act to fail. I do not need the cache for speeding up actions, is there a way to simply ignore the cache action in subactions to get `act` to work without having to modify the subactions?

**Comment by BevanR** [comment]
@leumasme `--reuse` may work in this scenario; You will still need to modify the sub-actions, but only temporarily to get it to install the cached dependencies once. Then, if the sub-action uses the cache correctly with an appropriate `key`, then it won't attempt to access the cache and will succeed.

**Comment by zhz125** [comment]
I am using [bazelisk](https://github.com/marketplace/actions/setup-bazelisk). I used the exact yml (minus mount cache step) as provided by the website and I got the following errors. Any workaround or future support for bazel? 
```
[Unit tests/test]   💬  ::debug::*** zstd command line interface 64-bits v1.4.4, by Yann Collet ***
[Unit tests/test]   💬  ::debug::getCacheEntry - Attempt 1 of 2 failed with error: Cache Service Url not found, unable to restore cache.
[Unit tests/test]   💬  ::debug::getCacheEntry - Attempt 2 of 2 failed with error: Cache Service Url not found, unable to restore cache.
[Unit tests/test]   ❗  ::error::getCacheEntry failed: Cache Service Url not found, unable to restore cache.
[Unit tests/test]   ❌  Failure - Main bazelbuild/setup-bazelisk@v2
[Unit tests/test] exitcode '1': failure
```

**Comment by adrianruizmora** [comment]
> If you are using nektos/act to develop GHA workflows locally and want to get `actions/cache` working so that you can get faster feedback when you test-run on your changes to GHA workflow yaml files;
> 
>     1. [ACTIONS_RUNTIME_URL, ACTIONS_RUNTIME_TOKEN and ACTIONS_CACHE_URL environment variables are missing. #329](https://github.com/nektos/act/issues/329) is a dead end. Do not bother reading the long thread.
>        
>        * It is mostly about artifact upload/download actions, not cache actions.
> 
>     2. Disable cache actions with `if: ${{ !env.ACT }}`
> 
>     3. Use act's `--reuse` flag.
> 
> 
> I will repeat that last step, because it is a much better solution than trying to get the cache action working locally;
> # Use act's `--reuse` flag
> 
> From [the docs](https://github.com/nektos/act#flags); ` -r, --reuse reuse action containers to maintain state`
> 
> **Cache saving and restoring becomes unnecessary.**

As [netaskd](https://github.com/netaskd) and [guice](https://github.com/guice) have said you need to use the same name for each job that uses actions/cache. What i have done to make it more dynamic is to set the name of jobs like this so i don't have to make changes to test locally or before pushing:
```
build:
    name: ${{ env.ACT || 'build' }} 
    ...
deploy:
    name: ${{ env.ACT || 'deploy' }} 
    ...
```
