### ISSUE TITLE
unexpected behaviour with 'watch'

### ISSUE THREAD

**Issue by davidmoshal** [nektos/act#301]
Firstly, kudos for a great project, and also great article explaining how you reverse engineered github action runners!

However, I'm a bit surprised by the behavior of the '-w' switch.

Expected behavior: editing the workflow yml file would re-run the new workflow.

Actual behavior: editing the workflow yml runs the workflow old workflow, ie: a defined at the time that `act -w` started.

Suggestion: retrigger act if any workflow file was edited.

**Comment by xaviergmail** [comment]
This still appears to be an issue
