### ISSUE TITLE
Unable to find git in your PATH.

### ISSUE THREAD

**Issue by joanofdart** [nektos/act#302]
Trying to run "flutter" throws me said error. Any ideas?
```yml
Unable to find git in your PATH.
```

**Comment by jsg2021** [comment]
The default container used to run jobs is [intentionally small](https://github.com/nektos/act#default-runners-are-intentionally-incomplete). I had to use the full container:
```sh
act -P ubuntu-latest=nektos/act-environments-ubuntu:18.04 push
```
