### ISSUE TITLE
hashFiles documentation says you can supply multiple paths, but act doesn't let you

### ISSUE THREAD

**Issue by doughsay** [nektos/act#324]
I'm not sure how new this is, because I know `hashFiles` used to only allow one path, but the github actions documentation now says you can supply multiple paths: https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#hashfiles

When I try this in `act` though, I get: `[RangeError: expected 1 argument(s); got 3]`

My expression is this: `${{ hashFiles('lib/**/*.ex', 'test/**/*.ex', 'mix.lock') }}`

EDIT: Another interesting point: in `act` you can do `${{ hashFiles('{lib/**/*.ex,test/**/*.ex,mix.lock}') }}`, but github actions will not recognize the multi-glob pattern.

**Comment by langston-barrett** [comment]
This is still an issue.
