### ISSUE TITLE
MODULE_NOT_FOUND on Windows 10 with Linux Containers

### ISSUE THREAD

**Issue by ColinM9991** [nektos/act#331]
Copied from [here](https://github.com/nektos/act/issues/228#issuecomment-657067980)

I am developing on a Windows environment and building in a Linux container for docker, this is what I receive when running `act`.

act has been installed via Chocolatey, and also directly from the latest release.

>[34m[CI Build - Master/build] [0m⭐  Run Setup .NET Core
[34m[CI Build - Master/build] [0m  ☁  git clone 'https://github.com/actions/setup-dotnet' # ref=v1
[34m[CI Build - Master/build] [0m  🐳  docker cp src=act/actions-setup-dotnet@v1 dst=/actions\
[34m|[0m internal/modules/cjs/loader.js:628
[34m|[0m     throw err;
[34m|[0m     ^
[34m|[0m
[34m|[0m Error: Cannot find module '/github/workspace/\actions\actions-setup-dotnet@v1\dist\index.js'
[34m|[0m [90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:625:15)[39m
[34m|[0m [90m    at Function.Module._load (internal/modules/cjs/loader.js:527:27)[39m
[34m|[0m [90m    at Function.Module.runMain (internal/modules/cjs/loader.js:839:10)[39m
[34m|[0m [90m    at internal/main/run_main_module.js:17:11[39m {
[34m|[0m   code: [32m'MODULE_NOT_FOUND'[39m,
[34m|[0m   requireStack: []
[34m|[0m }
[34m[CI Build - Master/build] [0m  ❌  Failure - Setup .NET Core
Error: exit with `FAILURE`: 1

**Comment by archon810** [comment]
Same problem here.

```
C:\Users\Artem Russakovskii\Dropbox\workspace\apkmirror-app-bundles>act
←[34m[Android CI/Lint and Build] ←[0m🚀  Start image=node:12.6-buster-slim
←[34m[Android CI/Lint and Build] ←[0m  🐳  docker run image=node:12.6-buster-slim entrypoint=["/usr/bin/tail" "-f" "/dev/null"] cmd=[]
←[34m[Android CI/Lint and Build] ←[0m  🐳  docker cp src=C:\Users\Artem Russakovskii\Dropbox\workspace\apkmirror-app-bundles/. dst=\github\workspace
←[34m[Android CI/Lint and Build] ←[0m⭐  Run actions/checkout@v1
←[34m[Android CI/Lint and Build] ←[0m  ✅  Success - actions/checkout@v1
←[34m[Android CI/Lint and Build] ←[0m⭐  Run Setup JDK 1.8
←[34m[Android CI/Lint and Build] ←[0m  ☁  git clone 'https://github.com/actions/setup-java' # ref=v1
←[34m[Android CI/Lint and Build] ←[0m  🐳  docker cp src=act/actions-setup-java@v1 dst=/actions\
←[34m|←[0m internal/modules/cjs/loader.js:628
←[34m|←[0m     throw err;
←[34m|←[0m     ^
←[34m|←[0m
←[34m|←[0m Error: Cannot find module '/github/workspace/\actions\actions-setup-java@v1\dist\setup\index.js'
←[34m|←[0m ←[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:625:15)←[39m
←[34m|←[0m ←[90m    at Function.Module._load (internal/modules/cjs/loader.js:527:27)←[39m
←[34m|←[0m ←[90m    at Function.Module.runMain (internal/modules/cjs/loader.js:839:10)←[39m
←[34m|←[0m ←[90m    at internal/main/run_main_module.js:17:11←[39m {
←[34m|←[0m   code: ←[32m'MODULE_NOT_FOUND'←[39m,
←[34m|←[0m   requireStack: []
←[34m|←[0m }
←[34m[Android CI/Lint and Build] ←[0m  ❌  Failure - Setup JDK 1.8
Error: exit with `FAILURE`: 1
```

**Comment by franTarkenton** [comment]
Ditto:

```
[BUILD Package/Build BCDC-SMK container image          ] �  Start image=node:12.6-buster-slim
[BUILD Package/Build BCDC-SMK container image          ]   �  docker run image=node:12.6-buster-slim entrypoint=["/usr/b in/tail" "-f" "/dev/null"] cmd=[]
[BUILD Package/Build BCDC-SMK container image          ] ⭐  Run actions/checkout@v2
[BUILD Package/Build BCDC-SMK container image          ]   ☁  git clone 'https://github.com/actions/checkout' # ref=v2
[BUILD Package/Build BCDC-SMK container image          ]   �  docker cp src=act/actions-checkout@v2 dst=/actions\
| internal/modules/cjs/loader.js:628
|     throw err;
|     ^
|
| Error: Cannot find module '/github/workspace/\actions\actions-checkout@v2\dist\index.js'
|     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:625:15)
|     at Function.Module._load (internal/modules/cjs/loader.js:527:27)
|     at Function.Module.runMain (internal/modules/cjs/loader.js:839:10)
|     at internal/main/run_main_module.js:17:11 {
|   code: 'MODULE_NOT_FOUND',
|   requireStack: []
| }
[BUILD Package/Build BCDC-SMK container image          ]   ❌  Failure - actions/checkout@v2
Error: exit with `FAILURE`: 1
```

**Comment by franTarkenton** [comment]
This issue went away for me when I commented out the `ref` property in the checkout step:

```
   ...
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
      id: checkout
      with:
        # ----- comment out ref seems to resolve this issue for me
        #ref: v2
        fetch-depth: 0

```

**Comment by timheuer** [comment]
Does not resolve for me: 
>❯ act
[Build and Deploy/Build and Deploy] 🚀  Start image=node:12.6-buster-slim
[Build and Deploy/Build and Deploy]   🐳  docker run image=node:12.6-buster-slim entrypoint=["/usr/bin/tail" "-f" "/dev/null"] cmd=[]
[Build and Deploy/Build and Deploy]   🐳  docker cp src=C:\Users\timheuer\Documents\GitHub\aspnet-core-sample-deploy/. dst=\github\workspace
[Build and Deploy/Build and Deploy] ⭐  Run actions/checkout@v2
[Build and Deploy/Build and Deploy]   ✅  Success - actions/checkout@v2
[Build and Deploy/Build and Deploy] ⭐  Run Setup .NET Core SDK ${{ env.NETCORE_VERSION }}
[Build and Deploy/Build and Deploy]   ☁  git clone 'https://github.com/actions/setup-dotnet' # ref=v1
[Build and Deploy/Build and Deploy]   🐳  docker cp src=C:\Users\timheuer\.cache\act/actions-setup-dotnet@v1 dst=/actions\
| internal/modules/cjs/loader.js:628
|     throw err;
|     ^
|
| Error: Cannot find module '/github/workspace/\actions\actions-setup-dotnet@v1\dist\index.js'
|     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:625:15)
|     at Function.Module._load (internal/modules/cjs/loader.js:527:27)
|     at Function.Module.runMain (internal/modules/cjs/loader.js:839:10)
|     at internal/main/run_main_module.js:17:11 {
|   code: 'MODULE_NOT_FOUND',
|   requireStack: []
| }
[Build and Deploy/Build and Deploy]   ❌  Failure - Setup .NET Core SDK ${{ env.NETCORE_VERSION }}
Error: exit with `FAILURE`: 1

**Comment by cdelgadob** [comment]
I'm trying to launch the Azure Login sample, with this definition:

```
on: [push]

name: AzureLoginSample

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: azure/login@v1.1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - run: |
        az webapp list --query "[?state=='Running']"

```

But I get the MODULE_NOT_FOUND error:

```
[AzureLoginSample/build-and-deploy] 🚀  Start image=node:12.6-buster-slim
[AzureLoginSample/build-and-deploy]   🐳  docker run image=node:12.6-buster-slim entrypoint=["/usr/bin/tail" "-f" "/dev/null"] cmd=[]
[AzureLoginSample/build-and-deploy] ⭐  Run azure/login@v1.1
[AzureLoginSample/build-and-deploy]   ☁  git clone 'https://github.com/azure/login' # ref=v1.1
[AzureLoginSample/build-and-deploy]   🐳  docker cp src=act/azure-login@v1.1 dst=/actions\
| internal/modules/cjs/loader.js:628
|     throw err;
|     ^
|
| Error: Cannot find module '/github/workspace/\actions\azure-login@v1.1\lib\main.js'
|     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:625:15)
|     at Function.Module._load (internal/modules/cjs/loader.js:527:27)
|     at Function.Module.runMain (internal/modules/cjs/loader.js:839:10)
|     at internal/main/run_main_module.js:17:11 {
|   code: 'MODULE_NOT_FOUND',
|   requireStack: []
| }
[AzureLoginSample/build-and-deploy]   ❌  Failure - azure/login@v1.1
Error: exit with `FAILURE`: 1

```

**Comment by matfax** [comment]
It might be a path related issue.
`docker cp src=act/arbitrary-linux-image@master dst=/actions\`
Here, the dst will be run in a Linux environment. Linux might confuse the `\` at the end.

**Comment by cdelgadob** [comment]
That's what I think as well, because when I run `act` in the same machine
but from Linux, it works.

**Comment by cdelgadob** [comment]
That's what I think as well, because when I run ```act``` in the same machine
but from Linux, it works.

This line doesn't look goo neither: ```/github/workspace/\actions\azure-login@v1.1\lib\main.js```

**Comment by timheuer** [comment]
Agreed, need to convert posix paths

**Comment by akhilmhdh** [comment]
Hey guys, will this be fixed soon, or is there any work around to this in win 10. Stuck on this for a while : (

**Comment by matfax** [comment]
The workaround is using Ubuntu 20+WSL2 on Win 10, installing Docker, enabling WSL2 for docker, enabling WSL2 integration in docker to Ubuntu 20, and then using act from the Ubuntu environment.
