### ISSUE TITLE
Support composite GitHub actions

### ISSUE THREAD

**Issue by justincy** [nektos/act#339]
A request to support composite GitHub actions: https://docs.github.com/en/actions/creating-actions/creating-a-composite-run-steps-action

**Comment by jsoref** [comment]
Amongst the things to look at: actions/runner#615

**Comment by kungfuchicken** [comment]
+1 on this

**Comment by josh-hogle** [comment]
Any updates on the status of this one?

**Comment by rickstaa** [comment]
Still relevant.

**Comment by dradetsky** [comment]
I also need this feature

**Comment by rudolphmatthias** [comment]
We want to start using composite actions a lot, but also don't want to loose the ability to test locally. This is a really needed feature for us.

**Comment by catthehacker** [comment]
Implemented in #514

**Comment by askb** [comment]
@justincy Is there a readme or docs on what inputs are required for test run locally with the latest nektos/act? Maybe I'm missing some steps.

```
[reusable/reusable_workflow_job]   🐳  docker exec cmd=[bash --noprofile --norc -e -o pipefail /var/run/act/workflow/0] user= workdir=
| inputs.string_required=
[reusable/reusable_workflow_job]   ❌  Failure - Main test required string
```

**Comment by jsoref** [comment]
@askb: this ticket was for composite actions, your workflow appears to be a reusable workflow which was related to #826.

I'd suggest asking in gitter or opening a new ticket with a sample repository.
