### ISSUE TITLE
Is there a way to specify, among multiple workflows, only one of the workflows to be run?

### ISSUE THREAD

**Issue by origliante** [nektos/act#344]
As in the title, it looks impossible from the --help

**Comment by cdb** [comment]
@origliante - I believe you can target a specific workflow file by passing the path directly to that file with the `--workflows` flag, as in `act <event-name> --workflows .github/workflows/file-to-focus-on.yaml`

The code handles both a directory or file in that argument: https://github.com/nektos/act/blob/3eef111e46f42f43e62b64e6cdfbade4fe0935e2/pkg/model/planner.go#L59-L67
