### ISSUE TITLE
zstd missing

### ISSUE THREAD

**Issue by xenoterracide** [nektos/act#345]
```
[Database Migrations/migrations]   💬  ::debug::Unable to locate executable file: zstd. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.
```
this is coming from 
```yml
      - uses: satackey/action-docker-layer-caching@v0.0.8
```

run with
```
act -P ubuntu-latest=nektos/act-environments-ubuntu:18.04 push -j migrations
```

**Comment by tdtm** [comment]
Workaround? https://github.com/nektos/act/issues/257

**Comment by langston-barrett** [comment]
Still active.

**Comment by langston-barrett** [comment]
Still active...

**Comment by catthehacker** [comment]
`zstd` is included in `medium` image for `act`.

**Comment by vysogot** [comment]
`act` version 0.2.52 with `medium` still complaining: `::debug::Unable to locate executable file: zstd. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.`
