### ISSUE TITLE
Feature request: Make --secret-file=.secrets the default behaviour?

### ISSUE THREAD

**Issue by carlthome** [nektos/act#357]
Currently, you have to explicitly configure which secrets to pickup when calling `act`. Similarly to how .env files are automatically read without additional CLI flags, perhaps the same should happen for the proposed .secrets file that's mentioned in the --secret-file help.

My current workaround is to simply commit an .actrc to my repo with `--secret-file=.secrets` set, but I spent a while being confused before realizing this was necessary.

**Comment by carlthome** [comment]
Bump

**Comment by CatTheHacker** [comment]
Bump, very easy to implement, will look at it in few hours.

**Comment by carlthome** [comment]
Nice!
