### ISSUE TITLE
Copying directories from Windows to a Linux container flattens path.

### ISSUE THREAD

**Issue by barweiss** [nektos/act#359]
When copying a directory to the container from a Windows host, the directory structure is flattened.

For example, consider the following directory structure:
```
|   file.txt
\---dir
        file.txt
```

Copying that to a Linux container will produce the following directory structure:

```
'dir\file.txt'
file.txt
```

**Comment by Poselsky** [comment]
Solution wasn't uploaded to the realease yet and had the same issue when running commands with cmd or git bash (git bash makes even some weird artifact to the console).

I found the solution by using Windows 10 (v 2004) **wsl** with ubuntu subsystem and running github action from **wsl**.
