### ISSUE TITLE
Support for local images, without pulling from Docker?

### ISSUE THREAD

**Issue by marccampbell** [nektos/act#37]
Is it possible for an action to reference an image in a "uses" variable that is a Docker format (docker://namespace/image:tag), and have act use the image that's already in the local docker image cache? 

At first look in the code, and trying this, it appears that if the uses is set to a docker:// format, act will always invoke a DockerPullExecutor, which will update the image to the version that's in the registry, not the locally built one.

**Comment by cplee** [comment]
@marccampbell thanks for the suggestion (and PR #38).  I'd like to align with how the docker cli.  Currently, a pull is only done if the image is missing locally.  There is work in progress to add a `--pull` flag to the docker cli to force a pull: https://github.com/docker/cli/pull/1498

Thoughts?

**Comment by marccampbell** [comment]
@cplee that makes sense. Obviously, that will change the default pull behavior for the next release of act. Is there anything additional to consider here?

I'm happy to update #38 to use a `--pull` flag, if nobody else is working on this.
