### ISSUE TITLE
Secrets are logged

### ISSUE THREAD

**Issue by OJFord** [nektos/act#380]
```sh
- uses: action@v1
  with:
    secret: ${{ secret.SO_SECRET }}
```

run as `act push -e t -s SO_SECRET`, logs:

```sh
docker run image=act-ojford-action-v1:latest entrypoint=[] cmd=["hunter2"]
```

where `hunter2` is the secret contents of `$SO_SECRET`.

(I understand that not printing the contents of an _environment variable_ isn't going to make anything any more _secure_ but it's still not ideal to wantonly print secrets in term history.)

(Obligatory 'but thanks for the great tool!' (really :+1:))

**Comment by OJFord** [comment]
Activity.

**Comment by CatTheHacker** [comment]
Could you provide more info/workflow? I'm not able to reproduce that.
