### ISSUE TITLE
What is the expected format of the --secret-file ?

### ISSUE THREAD

**Issue by Roms1383** [nektos/act#396]
It's a bit of a naive question but I wonder if the expected format of the file provided to `--secret-file` is :
*  classic env like :
   ```.env
   SOME_VAR="SOME:SECRET"
   SOME_OTHER_VAR=ANOTHER_SECRET
   ```
*  JSON format :
   ```json
   {
     "SOME_VAR": "SOME:SECRET",
     "SOME_OTHER_VAR": "ANOTHER_SECRET"
   }
   ````

**Comment by cplee** [comment]
@Roms1383 - the file is expected to be like a "classic env" file.  Internally it uses `godotenv`: https://pkg.go.dev/github.com/joho/godotenv

**Comment by Roms1383** [comment]
Thanks!

**Comment by alambike** [comment]
Maybe an example in README would help to clarify this.
