### ISSUE TITLE
clean up changed .git/config user after run

### ISSUE THREAD

**Issue by maxheld83** [nektos/act#41]
When `act` runs with some git action in the root, it appears to set a new `nektos/act` user in the  `.git/config`.
That makes a ton of sense.

However, it'd be nice if `act` could clean up after itself, and revert this change on success or failure, so that I don't muck up my git config.

I think this "problem" only happens in the relatively rare situation where you're running some git actions *directly in your root*.
An example would be (as in my case) when I deploy to GitHub pages from the root: said action then `git init`s stuff right in my repo root, locally, thus overwriting/amending my own `.git/config`.

I just commited a bunch of stuff and was really surprised that I had somehow become `nektos/act` 😸. 

This software is phenomenal, thanks for the generous work @nektos!

(this is somewhat related to #28 I think?)

**Comment by maxheld83** [comment]
oh, and if someone else is so dense as myself as to do this to your commit history, here's how you can fix it: https://stackoverflow.com/questions/4981126/how-to-amend-several-commits-in-git-to-change-author.

Needs `git push --force` at the end.

**Comment by nicolo-ribaudo** [comment]
As a workaround, I'm doing

```
git -c user.name="Name" -c user.email="email@email.com" commit -m "Commit made by different author!"
```

in actions so that I don't need to update the git config for the repo.

**Comment by cplee** [comment]
Would #21 address this issue?  In summary, allow act to run in a temp directory with a fresh checkout of the repo.

**Comment by maxheld83** [comment]
yeah I think it would @cplee because then whatever git commands need to be run inside actions, and whatever changes they would make to `.git/config` would be inside that temp dir.

**Comment by cplee** [comment]
As of `0.2.2`, act no longer runs against a bind mount of local dir...instead a volume is created and workdir is copied into volume
