### ISSUE TITLE
[RFE] Support for podman

### ISSUE THREAD

**Issue by iranzo** [nektos/act#414]
When executing act on a Fedora 33 system it complains it cannot find docker daemon running (which is not needed when using podman).

Please, enable support for it

**Comment by xatier** [comment]
dup w/ #303

**Comment by jedahan** [comment]
Might want to look at something like https://github.com/quay/quay-builder/commit/42d8d5ec7afc09ed6f8fe0f53e31333b170d2451

I'm not familiar with go, but it looks like they built an interface called ContainerClient and wrote two implementations, one for Docker, one for Podman.
