### ISSUE TITLE
secret file path should be absolute

### ISSUE THREAD

**Issue by rgarrigue** [nektos/act#431]
Hi there

I added --secret-file=~/.somewhere/github in my ~/.actrc. It doesn't work since 

```
time="2020-11-25T12:10:50+01:00" level=debug msg="Loading secrets from /home/me/work/stuf/~/somewhere/github"
```

Either make it an absolute path, or try relative then absolute ?

**Comment by rgarrigue** [comment]
And while you're at it, defaulting to ./.secrets, like env is defaulting to ./.env maybe.

**Comment by FoxxMD** [comment]
This is still an issue, please re-open
