### ISSUE TITLE
Act list empty even though an action exists

### ISSUE THREAD

**Issue by RangerMauve** [nektos/act#436]
I'm trying to run [this workflow](https://github.com/digidem/mapeo-mobile/blob/develop/.github/workflows/android.yml) with `act version 0.2.17` but it doesn't seem to be seeing it.

It seems like `act` isn't showing anything when I do a list, but it looks like it sees the YAML file.

```
act --list -v
DEBU[0000] Loading environment from /home/mauve/programming/mapeo-mobile/.env 
DEBU[0000] Loading secrets from                         
DEBU[0000] Loading workflows from '/home/mauve/programming/mapeo-mobile/.github/workflows' 
DEBU[0000] Reading workflow '/home/mauve/programming/mapeo-mobile/.github/workflows/android.yml' 
DEBU[0000] Planning event: push                         
ID  Stage  Name  
```

Is there anything else I should do to debug this scenario?

**Comment by RangerMauve** [comment]
Whoops, looks like I was misunderstanding what `act list` does.  Running `act pull_request` seemed to start the trigger.

**Comment by djsd123** [comment]
I still don't understand what `act --list` is supposed to do???? 😕

**Comment by catthehacker** [comment]
@djsd123 
![image](https://user-images.githubusercontent.com/31106839/131223813-864773fd-7a53-4a7d-a134-2e64de4f6148.png)
