### ISSUE TITLE
I can't use `env.ACT`

### ISSUE THREAD

**Issue by oderwat** [nektos/act#439]
I tried to skip steps but using `if: ${{ !env.ACT }}` did not work. 

I use `if: ${{ env.GITHUB_ACTOR != "nektos/act" }}` for now and defininct something like ACT in `.env` does work too.

Any idea what am I missing here?

**Comment by CatTheHacker** [comment]
`env.ACT` hasn't been released yet and exists only in https://github.com/nektos/act/tree/master
