### ISSUE TITLE
Add default event payloads

### ISSUE THREAD

**Issue by mcolyer** [nektos/act#44]
It would be nice if the default event payloads reflected the example ones provided on developer.github.com. I've pulled together the current set here: https://github.com/mcolyer/actions-toolkit-action/tree/master/fixtures.

I still think it's helpful to have a flag to override the payload (ie `-e`), as sometimes you want to change a specific payload but I figured a default would be helpful.

**Comment by agibralter** [comment]
Ah, I was just surprised by this as well. I forgot my action relied on a payload and it took me a minute to figure out why it blew up. The README seems to suggest the filesystem will be set up with `/github/workflow/event.json` but it's not clear the values will be empty in there.

**Comment by cplee** [comment]
@agibralter in the meantime, you can pass your own event file with `act -e path/to/event.json`

**Comment by agibralter** [comment]
Good to know, thank you @cplee!
