### ISSUE TITLE
Add ability to debug secrets

### ISSUE THREAD

**Issue by dunklesToast** [nektos/act#448]
Is there any way to turn off the Auto-Hide from Secrets in the logs? I get that it's how GitHub does it and it totally makes sense but it would be great if there would be commandline switch to disable the hiding.

**Comment by CatTheHacker** [comment]
I've crafted something quickly that allows to show secrets https://github.com/CatTheHacker/act/releases/tag/insecure-secrets.
![image](https://user-images.githubusercontent.com/31106839/102614046-d190d700-4133-11eb-8a00-9cca199d56c6.png)
