### ISSUE TITLE
Error: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

### ISSUE THREAD

**Issue by afonsomatos** [nektos/act#449]
I did `brew install act`,
but running `act -n` on my repo, I get:

```*DRYRUN* [Push on Master/Run Code Analysis] 🚀  Start image=node:12.6-buster-slim
Error: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

**Comment by CatTheHacker** [comment]
Do you have Docker installed?

**Comment by karolswdev** [comment]
You need a DinD image to work with. Read the documentation and use the ``-P`` switch to replace whichever ``runs_on`` you have to the image that contains DinD.

**Comment by jyejare** [comment]
@afonsomatos What OS are you using to run act ? You need to install docker-engine in your OS first !

**Comment by catthehacker** [comment]
Feel free to ping me if the if you still have issues.
