### ISSUE TITLE
Why is act reading my GITHUB_TOKEN during build?

### ISSUE THREAD

**Issue by jedahan** [nektos/act#455]
It seems the Makefile reads and exports GITHUB_TOKEN during build, which is alarming. Can we make that optional and default off?

**Comment by CatTheHacker** [comment]
Makefile is not mentioned as recommended installation method, so I assume it's used only to release new versions by `act` dev.
You can build `act` with `go build -ldflags "-X main.version=master" main.go` or follow the already described installation options.
