### ISSUE TITLE
Warn that not Apple Silicon compatible

### ISSUE THREAD

**Issue by bencooper222** [nektos/act#458]
I'm guessing you're blocked by Docker in terms of Apple Silicon compatibility. Would you be amenable to a PR warning of that on the README?

**Comment by CatTheHacker** [comment]
[As far as I know, Docker Desktop for Mac already supports Apple Silicon CPUs.](https://www.docker.com/blog/docker-desktop-3-0-0-smaller-faster-releases/)
> And today we have released to our preview users two exciting features that we know a lot of people have been waiting for: Docker Desktop on Apple M1 chips, and GPU support on WSL 2.

**Comment by bencooper222** [comment]
Not reasonable to expect this repo to support a preview feature IMO but good to hear it's coming soon!

**Comment by tylerrasor** [comment]
I've been using the dev preview of docker for about a month now (`Preview5` and now `Preview7`), and it's pretty good.

I downloaded the `x86 v0.2.19` release, and the binary runs fine under Rosetta 2.  I also pulled `master` and `make install` builds fine also using `go 1.16beta1` (although Big Sur put restrictions on `/usr/local/bin` so you have to `sudo`).

The interesting news: @catthehacker is already pushing `arm64` images for `ubuntu:act-latest`, which the docker preview (correctly) pulls down.  I don't know enough about GitHub Actions to know what kind of workers they're running on, but I'd be surprised if they're arm.  So my local testing has diverged (if ever so slightly) from what a real actions run would do.

For example, in testing a job that requires `actions/setup-go@v2`, their action successfully identifies that I'm running an `ubuntu arm64` image and then pulls down `go*linux-arm64.tar.gz`.  If I tried an action that wasn't architecture aware, though, I could see it causing problems.

For the time being, I've done a manual `docker pull catthehacker/ubuntu:act-latest --platform amd64`, which equally works fine.

**Comment by catthehacker** [comment]
@tylerrasor thank you 😸 I'm trying to have the image work on every platform possible (unfortunately, it depends on the platforms provided by `ubuntu` image on DockerHub) as well as work with every action (while still maintaining small size).

GitHub Actions runners are running 64-bit versions of Ubuntu and any other platform is supported via qemu/Docker.

Free to to bother me whenever something doesn't work on those images (https://github.com/catthehacker/docker_images).

**Comment by percy-raskova** [comment]
🔒 **Security Classification Needed**
  
  This issue appears to mention security-related topics but doesn't have a security classification label.
  
  Please add one of the following labels:
  - `security:public` - For non-sensitive security discussions
  - `security:candidate` - For member-only security content
  - `security:cadre` - For highly sensitive security matters
  
  If this issue doesn't actually contain security-sensitive information, you can ignore this message.
