### ISSUE TITLE
`act` unhandled panic

### ISSUE THREAD

**Issue by catthehacker** [nektos/act#487]
Did not found yet where or why it does that, but it would be good to show proper error instead of panic

```yaml
name: workflow
on:
  workflow_dispatch:

jobs:
  job-test:
    strategy:
      fail-fast: false
      matrix:
        container: [foo]
    runs-on: ubuntu-latest
    steps:
      - name: step-in-job
        with:
          args: ${{ matrix.container }}
```

<details>
  <summary>Panic error</summary>

	  panic: runtime error: index out of range [1] with length 0
	  
	  goroutine 50 [running]:
	  github.com/nektos/act/pkg/runner.newRemoteAction(0x0, 0x0, 0x0)
	          C:/Users/cat/go/src/github.com/nektos/act/pkg/runner/step_context.go:399 +0x1b9
	  github.com/nektos/act/pkg/runner.(*githubContext).isLocalCheckout(0xc0005b23c0, 0xc000416480, 0x8)
	          C:/Users/cat/go/src/github.com/nektos/act/pkg/runner/run_context.go:508 +0x65
	  github.com/nektos/act/pkg/runner.(*RunContext).localCheckoutPath(0xc0004165a0, 0xc000005fe0, 0xc0005ca520, 0x17)
	          C:/Users/cat/go/src/github.com/nektos/act/pkg/runner/run_context.go:596 +0xca
	  github.com/nektos/act/pkg/runner.(*RunContext).startJobContainer.func1(0x134be20, 0xc0004a6660, 0x0, 0x0)
	          C:/Users/cat/go/src/github.com/nektos/act/pkg/runner/run_context.go:114 +0xe96
	  github.com/nektos/act/pkg/common.Executor.Then.func1(0x134be20, 0xc0004a6660, 0xc000493560, 0xc0005ede18)
	          C:/Users/cat/go/src/github.com/nektos/act/pkg/common/executor.go:146 +0x189
	  github.com/nektos/act/pkg/common.Executor.Then.func1(0x134be20, 0xc0004a6660, 0xc00022efc0, 0xc0004934d0)
	          C:/Users/cat/go/src/github.com/nektos/act/pkg/common/executor.go:133 +0x53
	  github.com/nektos/act/pkg/common.Executor.Then.func1(0x134be20, 0xc0004a6660, 0x1, 0x1816b60)
	          C:/Users/cat/go/src/github.com/nektos/act/pkg/common/executor.go:133 +0x53
	  github.com/nektos/act/pkg/common.Executor.If.func1(0x134be20, 0xc0004a6660, 0xc0005ca340, 0x13)
	          C:/Users/cat/go/src/github.com/nektos/act/pkg/common/executor.go:154 +0x71
	  github.com/nektos/act/pkg/runner.(*runnerImpl).NewPlanExecutor.func1(0x134be20, 0xc0003facf0, 0xc000005ce0, 0xc0004d7f70)
	          C:/Users/cat/go/src/github.com/nektos/act/pkg/runner/runner.go:79 +0x244
	  github.com/nektos/act/pkg/common.Executor.ChannelError.func1(0x134be20, 0xc0003facf0, 0xc000005ce0, 0x0)
	          C:/Users/cat/go/src/github.com/nektos/act/pkg/common/executor.go:125 +0x4c
	  github.com/nektos/act/pkg/common.NewParallelExecutor.func1.1(0xc000005ca0, 0xc00003b5c0, 0x134be20, 0xc0003facf0)
	          C:/Users/cat/go/src/github.com/nektos/act/pkg/common/executor.go:101 +0x62
	  created by github.com/nektos/act/pkg/common.NewParallelExecutor.func1
	          C:/Users/cat/go/src/github.com/nektos/act/pkg/common/executor.go:100 +0xbe

</details>

**Comment by lufia** [comment]
Related to #402
