### ISSUE TITLE
-P does not work

### ISSUE THREAD

**Issue by hojas** [nektos/act#489]
`act -P ubuntu-18.04=nektos/act-environments-ubuntu:18.04` does not use the Image specified.

**Comment by CatTheHacker** [comment]
Can you provide your workflow and logs or screenshot?

**Comment by ximon18** [comment]
FYI I just hit a similar problem but in my case my workflow actually referenced `ubuntu-latest` so I had to say `act -P ubuntu-latest=...`.

**Comment by hojas** [comment]
![image](https://user-images.githubusercontent.com/4729039/105113339-b123b600-5aff-11eb-8b98-d23598bf2f66.png)

@CatTheHacker
