### ISSUE TITLE
empty git-upload-pack given

### ISSUE THREAD

**Issue by paulbellamy** [nektos/act#49]
As of this afternoon, when running the example gcloud auth workflow (https://github.com/actions/gcloud/tree/master/auth#example-workflow-file), with the errors fixed, I get an error about not being able to clone the repo. Maybe a temporary github error?

```sh
$ GCLOUD_AUTH=$(base64 ~/gcloud.json) act
WARN[0000] unable to get git revision: open /Users/paulbellamy/temp/act-test/.git/refs/heads/master: no such file or directory
WARN[0000] unable to get git repo: section 'remote "origin"' does not exist
[setup-google-cloud] git clone 'https://github.com/actions/gcloud' # ref=master
[setup-google-cloud] Unable to pull refs/heads/master: empty git-upload-pack given
[setup-google-cloud] Unable to resolve master: reference not found
Error: reference not found
```

The first 2 errors are because it is not a real repo, just a minimal test-case directory I created.

Attached is a tarball of a failing repo. Any info would be super helpful, thanks! **Love** the project, btw.

[act-test.tar.gz](https://github.com/nektos/act/files/2953183/act-test.tar.gz)

**Comment by paulbellamy** [comment]
Based on a bit more digging (and running `act -v`), it seems like the cached clone dir in `/var/folders/dn/nkfvgz8n0k51lptgh1m8jfnw0000gn/T/act/actions/gcloud/auth@master/`, was corrupt. I removed that folder, re-ran act, and now it worked.

My only hypothesis is that the clone died, errored, or got <kbd>ctrl-c</kbd>-ed partway through,
 leaving the cloned dir present, but empty.

I've attached a tarball of the corrupt clone dir, in case it's useful.

[auth@master.tar.gz](https://github.com/nektos/act/files/2956107/auth%40master.tar.gz)

**Comment by maxheld83** [comment]
ran into the same problem; same solution worked.

**Comment by cplee** [comment]
As of version `0.2.2`, tempdir is replaced with docker volumes
