### ISSUE TITLE
docker-machine support?

### ISSUE THREAD

**Issue by bjeanes** [nektos/act#5]
Hi,

To work around infuriating Docker performance issues on macOS (Mojave) which have been unaddressed for more than a year, I use https://github.com/codekitchen/dinghy to work around it.

Unfortunately, `act` doesn't seem to abide `DOCKER_HOST`, `DOCKER_CERT_PATH`, `DOCKER_TLS_VERIFY`, `DOCKER_MACHINE_NAME`, etc.

Any chance this could be made to work?

**Comment by cplee** [comment]
Easy fix...on it!  Thanks for calling this out.  Should be in the next release later tonight.

**Comment by bjeanes** [comment]
Woohoo! Can't wait to try it tomorrow 🙏

**Comment by cplee** [comment]
@bjeanes this is now available in [v0.0.4](https://github.com/nektos/act/releases/tag/v0.0.4)
