### ISSUE TITLE
Matching `runs-on` labels for self-hosted runners

### ISSUE THREAD

**Issue by dradetsky** [nektos/act#519]
I'm trying to use act to run some workflows locally. However, for some reason my organization is using self-hosted runners. This means that rather than the more common `runs-on` key such as `runs-on: ubuntu-latest`, my workflow says `runs-on: [self-hosted, Linux, X64, infra]`. I think these are a list of labels s.t. any runner in my org's runner group which has all those labels is a valid candidate for running the workflow.

The problem is that I can't match this with `-P` options. Or at least, it's not clear how I'm supposed to.

I've since learned that a workaround is to write e.g. `act -P self-hosted=catthehacker/ubuntu:act-latest`, but this is counterintuitive and you should probably add a line of documentation.

**Comment by catthehacker** [comment]
Could you explain how is this counterintuitive and what we can do to fix that?
It's mentioned in README and `act --help`:
```
  -P, --platform stringArray   custom image to use per platform (e.g. -P ubuntu-18.04=nektos/act-environments-ubuntu:18.04)
```

**Comment by ap0ught** [comment]
as a new user I ran into this same thing. 
the error message I get is this.
[main.yml/A job to say hello] 🚧  Skipping unsupported platform 'self-hosted'

My first instinct is to find a way to alias self-hosted with ubuntu-latest
If this taught me how to alias or mentioned I could run with the -P option the error would be less negative.

**Comment by catthehacker** [comment]
In my opinion `act` usage is quite well documented in `README.md` file. If you feel like something is unclear please share your thoughts or submit PR.
