### ISSUE TITLE
mirror filesystem permissions

### ISSUE THREAD

**Issue by amn41** [nektos/act#52]
firstly, thanks for this amazing tool! absolutely love it and it's making my iteration speed so much faster.

I have an action which runs fine locally using `act`, but fails when executed by github due to (it seems) a file permission error.

My dockerfile is very simple:
```
FROM alekzonder/puppeteer
ADD puppeteer-config.json /app
RUN npm install mermaid.cli
ENTRYPOINT ["/app/node_modules/.bin/mmdc", "-p", "/app/puppeteer-config.json"]
CMD ["--help"]
```

my action looks like this:

```
action "mermaid" {
uses = "./action-mermaid"
args = "-i gantt.mmd -o gantt-tmp.png -w 1884 -H 450"
}
```

this runs absolutely fine if I do `act mermaid`, but on github I get an error writing to the file:

`Error: EACCES: permission denied, open 'gantt-tmp.png'`

However, I've created a ticket with GitHub support since this may just be a bug on their end. The same issue exists if I direct the output to an absolute path like `/github/home/gantt-tmp.png`, `/github/workspace/gantt-tmp.png` , and it doens't matter whether the output file exists or not.

**Comment by cplee** [comment]
not applicable after github actions v2 release
