### ISSUE TITLE
Enhancement: Authentication to docker registry

### ISSUE THREAD

**Issue by KnisterPeter** [nektos/act#527]
## Describe feature

It would be nice to create an authenticated docker api client to pull images from other registries which require authentication.
I think it might be good enough to add the authentication information found in `~/.docker/config.json` into the pull command.

https://github.com/nektos/act/blob/e6fcfed458dbccd640e093bffd0fc258d6ce0e6e/pkg/container/docker_pull.go#L55

The `ImagePullOptions` seems to allow this:
https://github.com/moby/moby/blob/46cdcd206c56172b95ba5c77b827a722dab426c5/api/types/client.go#L253-L258

**Comment by catthehacker** [comment]
Not state, will make PR that today/tomorrow.
