### ISSUE TITLE
Multibyte password not supported

### ISSUE THREAD

**Issue by vishal-biyani** [nektos/act#53]
When testing actions locally, if your password is a token or certificate string then the action aborts:

```
$ act 
Provide value for 'CERTIFICATE_AUTHORITY': *********************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************
2019/03/20 16:36:38 abort
```

This is mostly due to an issue [here](https://github.com/nektos/act/blob/18427728ae409904154955014df236e01e37b2e2/actions/action.go#L36) - as the gopass does not support multi-byte characters! But this prevents local testing where secret is bigger string as is the case here.

**Comment by maxheld83** [comment]
this solution might help: https://github.com/nektos/act/pull/66

**Comment by cplee** [comment]
workarounds:
* set secret through env variable: `act -s CERTIFICATE_AUTHORITY=$(cat mycert.key)`
* set secret in `~/.actrc`
