### ISSUE TITLE
Issue:  crash

### ISSUE THREAD

**Issue by jleonard-r7** [nektos/act#535]
## Act version

0.2.17

```none

```

## Expected behaviour

Does not crash.

## Actual behaviour

Crashes.

10:32 $ act 
panic: runtime error: comparing uncomparable type map[string]interface {}

goroutine 1 [running]:
github.com/nektos/act/pkg/model.commonKeysMatch(0xc000181500, 0xc0000aeba0, 0x4)
	/private/tmp/act-20201115-3464-1rimm85/act-0.2.17/pkg/model/workflow.go:198 +0x139
github.com/nektos/act/pkg/model.(*Job).GetMatrixes(0xc0000e5680, 0xc0000a5040, 0x6, 0xc0000e5680)
	/private/tmp/act-20201115-3464-1rimm85/act-0.2.17/pkg/model/workflow.go:180 +0x4b5
github.com/nektos/act/pkg/runner.(*runnerImpl).NewPlanExecutor(0xc00043b2c0, 0xc00043a4a0, 0x5)
	/private/tmp/act-20201115-3464-1rimm85/act-0.2.17/pkg/runner/runner.go:66 +0x52c
github.com/nektos/act/cmd.newRunCommand.func1(0xc0000aa000, 0x1e40218, 0x0, 0x0, 0x0, 0x0)
	/private/tmp/act-20201115-3464-1rimm85/act-0.2.17/cmd/root.go:202 +0x89c
github.com/spf13/cobra.(*Command).execute(0xc0000aa000, 0x1e40218, 0x0, 0x0, 0xc0000aa000, 0x1e40218)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:762 +0x47c
github.com/spf13/cobra.(*Command).ExecuteC(0xc0000aa000, 0x0, 0x0, 0x8)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x2fe
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800
github.com/nektos/act/cmd.Execute(0x19e8680, 0xc0003d8100, 0x19bf8b0, 0x6)
	/private/tmp/act-20201115-3464-1rimm85/act-0.2.17/cmd/root.go:57 +0xadb
main.main()
	/private/tmp/act-20201115-3464-1rimm85/act-0.2.17/main.go:33 +0x175

## Workflow and/or repository

<details>
  <summary>workflow</summary>

```none
name: example workflow

on: [push]

jobs:
  [...]
```

</details>

## Steps to reproduce

1. act

## `act` output

10:32 $ act 
panic: runtime error: comparing uncomparable type map[string]interface {}

goroutine 1 [running]:
github.com/nektos/act/pkg/model.commonKeysMatch(0xc000181500, 0xc0000aeba0, 0x4)
	/private/tmp/act-20201115-3464-1rimm85/act-0.2.17/pkg/model/workflow.go:198 +0x139
github.com/nektos/act/pkg/model.(*Job).GetMatrixes(0xc0000e5680, 0xc0000a5040, 0x6, 0xc0000e5680)
	/private/tmp/act-20201115-3464-1rimm85/act-0.2.17/pkg/model/workflow.go:180 +0x4b5
github.com/nektos/act/pkg/runner.(*runnerImpl).NewPlanExecutor(0xc00043b2c0, 0xc00043a4a0, 0x5)
	/private/tmp/act-20201115-3464-1rimm85/act-0.2.17/pkg/runner/runner.go:66 +0x52c
github.com/nektos/act/cmd.newRunCommand.func1(0xc0000aa000, 0x1e40218, 0x0, 0x0, 0x0, 0x0)
	/private/tmp/act-20201115-3464-1rimm85/act-0.2.17/cmd/root.go:202 +0x89c
github.com/spf13/cobra.(*Command).execute(0xc0000aa000, 0x1e40218, 0x0, 0x0, 0xc0000aa000, 0x1e40218)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:762 +0x47c
github.com/spf13/cobra.(*Command).ExecuteC(0xc0000aa000, 0x0, 0x0, 0x8)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x2fe
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800
github.com/nektos/act/cmd.Execute(0x19e8680, 0xc0003d8100, 0x19bf8b0, 0x6)
	/private/tmp/act-20201115-3464-1rimm85/act-0.2.17/cmd/root.go:57 +0xadb
main.main()
	/private/tmp/act-20201115-3464-1rimm85/act-0.2.17/main.go:33 +0x175

**Comment by mumoshu** [comment]
@jleonard-r7 I believe this is fixed via #415 and v0.2.18. Could you try again with v0.2.18 or greater?

**Comment by jleonard-r7** [comment]
I installed via homebrew so am at the mercy of the package maintainers.
