### ISSUE TITLE
System has not been booted with systemd as init system (PID 1). Can't operate

### ISSUE THREAD

**Issue by juebanlin** [nektos/act#548]
macos 15.7
act version 0.2.20

Setting up docbook-utils (0.6.14-3.3) ...
| Setting up asciidoc-dblatex (9.0.0~rc1-1) ...
| Processing triggers for tex-common (6.13) ...
| Running updmap-sys. This may take some time... done.
| Running mktexlsr /var/lib/texmf ... done.
| Building format(s) --all.
|       This may take some time... done.
| System has not been booted with systemd as init system (PID 1). Can't operate.
| Failed to create bus connection: Host is down

**Comment by catthehacker** [comment]
Could you provide more details? Docker containers do not use services based on `systemd`, so anything relying on that will fail.

**Comment by juebanlin** [comment]
> Could you provide more details? Docker containers do not use services based on `systemd`, so anything relying on that will fail.

thanks
