### ISSUE TITLE
Issue: If expressions fails in act but works on Github

### ISSUE THREAD

**Issue by vegidio** [nektos/act#565]
## Act version

```none
act version 0.2.20
```

## Expected behaviour

act would run all steps of my workflow.

## Actual behaviour

act didn't run and threw the error message "[build/build]   ❌  Error in if: expression - build"

## Workflow and/or repository

<details>
  <summary>workflow</summary>

```none
name: test

on:
  push:
    branches:
      - master

jobs:
  test:
    if: "!contains(github.event.head_commit.message, '[skip-ci]') && !contains(github.event.head_commit.message, '👀')"
    runs-on: ubuntu-latest

    steps:
      - name: Test
        run: echo "Test"
```

</details>

## Steps to reproduce

1. Save the workflow that I shared above
2. Run `act`

## `act` output

<details>
  <summary>Log</summary>

```none
DEBU[0000] Loading environment from /home/vegidio/Development/Source/js-resume/.env 
DEBU[0000] Loading secrets from /home/vegidio/Development/Source/js-resume/.secrets 
DEBU[0000] Loading workflows from '/home/vegidio/Development/Source/js-resume/.github/workflows' 
DEBU[0000] Reading workflow '/home/vegidio/Development/Source/js-resume/.github/workflows/build.yml' 
DEBU[0000] Reading workflow '/home/vegidio/Development/Source/js-resume/.github/workflows/test.yml' 
DEBU[0000] Planning job: test                           
DEBU[0000] Loading slug from git directory '/home/vegidio/Development/Source/js-resume/.git' 
DEBU[0000] Found revision: 5b2befdd9f84d2f6e5705fb94bc3e46a83c056ed 
DEBU[0000] Loading revision from git directory '/home/vegidio/Development/Source/js-resume/.git' 
DEBU[0000] Found revision: 5b2befdd9f84d2f6e5705fb94bc3e46a83c056ed 
DEBU[0000] HEAD points to '5b2befdd9f84d2f6e5705fb94bc3e46a83c056ed' 
DEBU[0000] HEAD matches refs/heads/master               
DEBU[0000] using github ref: refs/heads/master          
DEBU[0000] context env => map[ACT:true]                 
[test/test]   ❌  Error in if: expression - test
```

</details>

**Comment by miigotu** [comment]
What if you remove the double quotes?

**Comment by jsoref** [comment]
The expression thing at least for me explicitly objects to the `!`. Wrapping it in `${{ ... }}` makes everyone happy. I reported it as #598

**Comment by vegidio** [comment]
> What if you remove the double quotes?
> 
> This works for me here at least:
> 
> `if: success() && steps.prepare.outputs.version == 'master' && github.event_name != 'pull_request'`

It doesn't work without the double quotes on Github.

**Comment by miigotu** [comment]
> > What if you remove the double quotes?
> > 
> > This works for me here at least:
> > 
> > `if: success() && steps.prepare.outputs.version == 'master' && github.event_name != 'pull_request'`
> 
> It doesn't work without the double quotes on Github.
zhoDEQo5uTV9xb@

**Comment by vegidio** [comment]
@miigotu This is not the same example that I shared here.

Even if this example that you shared works for you, my point in this issue is to show that a workflow that works on Github with double quotes, doesn't work with act. And since act is supposed to mimic the same behaviour of Github Actions then it's a bug.

**Comment by miigotu** [comment]
I was replying specifically to that comment, correcting that GitHub does work without the quotes. If you provide inaccurate information, new bugs could be introduced.
