### ISSUE TITLE
Issue: 

### ISSUE THREAD

**Issue by Disturbing** [nektos/act#568]
## Act version

act version 0.2.20

## Expected behaviour

When running an act, I expect all repo files to be there when actions/checkout is ran

## Actual behaviour

Some files are missing for some reason.

## Workflow and/or repository

C
Cannot share the repo as it's private. But there a 755 bash file called hermit in ./bin in the repo. It does not exist when running on act, but exists on github.com

    steps:
    - uses: actions/checkout@v2
    - run: cd ./bin && ls
    - run: ./bin/hermit env >> $GITHUB_ENV

## `act` output

[ci/cd/ci     ] ⭐  Run cd ./bin && ls
| README.hermit.md  aws		 go	golangci-lint  hermit.hcl  protoc
| activate-hermit   aws_completer  gofmt	goreleaser     make
[ci/cd/ci     ]   ✅  Success - cd ./bin && ls
[ci/cd/ci     ] ⭐  Run ./bin/hermit env >> $GITHUB_ENV
| /github/workflow/4: line 1: ./bin/hermit: No such file or directory
[ci/cd/ci     ]   ❌  Failure - ./bin/hermit env >> $GITHUB_ENV

**Comment by Disturbing** [comment]
If i use --bind it works fine.

**Comment by jsoref** [comment]
1. Does this problem happen with v0.2.21 ?
2. Can you create a public action with a shell script that just does:
    ```sh
    #!/bin/sh
    echo hello
    ```

**Comment by Disturbing** [comment]
i think act was not shutdown correctly and was attaching itself to an old directory after i used --bind once. I'll share more if i figure out how to repo it, but at the moment i deleted the mounted directories / storage in docker and it resolved my issue.
