### ISSUE TITLE
Enhancement: Bring docker image and paths in line with latest runner model

### ISSUE THREAD

**Issue by JustinGrote** [nektos/act#582]
## Describe feature
The Actions runner has the following differences now from act, Act should be brought in line to ensure a more robust test environment:
1. Activity occurs under the `runner` user, not root. Actions that work in act with root privileges will fail in the runner
2. The /github folder no longer exists, all activity happens in the runner home directory
3. github/workspace has moved to `~/work/RepositoryName/RepositoryName`

**Comment by JustinGrote** [comment]
I'd be willing to invest time in a PR if there was a reasonable chance of it being accepted.

**Comment by catthehacker** [comment]
There is already a PR for changing path where repository is checked out (#567)
As for the `runner` user, I already have basic docker image ready but didn't get further than that yet.
https://github.com/catthehacker/docker_images/blob/e4dbf909324ccd7c9ff3ddedc0daa5e4bd266186/linux/ubuntu/runner/Dockerfile
I can also help with PR.

**Comment by catthehacker** [comment]
Will close this in favour of already opened issue(s) mentioned above.
