### ISSUE TITLE
Issue: cgo: exec gcc: exec: "gcc": executable file not found in $PATH

### ISSUE THREAD

**Issue by zhoub** [nektos/act#592]
## Act version

0.2.17

## Expected behaviour

Should be fine as Github Action on web

## Actual behaviour

```
| # github.com/mattn/go-sqlite3
| cgo: exec gcc: exec: "gcc": executable file not found in $PATH
```

## Workflow and/or repository

<details>
  <summary>workflow</summary>

```none
name: Go

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Install
      run: go mod vendor

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
```

</details>

## `act` output

<details>
  <summary>Log</summary>

```none

```

</details>

**Comment by catthehacker** [comment]
Please provide full log from `act`.

**Comment by catthehacker** [comment]
Most likely you used image that doesn't include `gcc`. Please refer to https://github.com/nektos/act#runner, https://github.com/nektos/act#default-runners-are-intentionally-incomplete and https://github.com/nektos/act#use-an-alternative-runner-image.
