### ISSUE TITLE
Enhancement: Follow XDG base directories

### ISSUE THREAD

**Issue by pgronkievitz** [nektos/act#599]
## Describe feature
Act is now using `$HOME/.actrc`. In my opinion it shouldn't clutter home directory and should be in `$XDG_CONFIG_HOME/actrc` or `$XDG_CONFIG_HOME/act/config`

**Comment by superrnovae** [comment]
I'm sorry for the necrobump, act saves all actions in the XDG_CONFIG_HOME, but it keep creating .actrc in my home directory.

**Comment by superrnovae** [comment]
> I'm unsure what does that mean as we don't use `XDG_CONFIG_HOME` for anything but config

I'm sorry, I meant to type XDG_CACHE_HOME/act

> create $XDG_CONFIG_HOME/.actrc file and it shouldn't make it in home

Thanks, this seems to have worked.
