### ISSUE TITLE
Getting "no space left on device" errors

### ISSUE THREAD

**Issue by sarahs** [nektos/act#60]
Thanks for this project @nektos, it's a super useful tool. 

It worked great for me for a while, but now I'm getting `Unhandled rejection Error: ENOSPC: no space left on device` errors when my `npm ci` action runs.

I added `df -h` to my workflow file to see what's going on, and it shows I've used 100% of space in `/github/home`:

<img width="537" alt="Screen Shot 2019-04-30 at 10 59 17 AM" src="https://user-images.githubusercontent.com/821071/56974039-12417400-6b3c-11e9-9679-ea0e1d38a9a4.png">

But doing an `ls -a` in that dir shows it's empty. I've cleared every cache I can think of, removed `node_modules` before install, and ran `docker system prune -af`, but still get the error.

I asked the Actions folks and they think it might be related to `act`, since I only get the error locally and not when running the workflow in a PR.

Thanks for any advice!

**Comment by thedarkwriter** [comment]
I can confirm the behavior with NPM with Act and what is interesting is follow on installations work no errors talking about no space left on device:
`
...
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
Downloading and installing node v10.14.1...
Downloading https://nodejs.org/dist/v10.14.1/node-v10.14.1-linux-x64.tar.xz...
######################################################################## 100.0%
Computing checksum with sha256sum
Checksums matched!
tar: bin/node: Wrote only 6656 of 10240 bytes
tar: lib/node_modules/npm/appveyor.yml: Cannot write: No space left on device
tar: lib/node_modules/npm/.travis.yml: Cannot write: No space left on device
tar: lib/node_modules/npm/changelogs/CHANGELOG-3.md: Cannot write: No space left on device
...
then
Downloading https://nodejs.org/dist/v10.14.1/node-v10.14.1.tar.xz...
###################                                                       26.5%
curl: (23) Failed writing body (265 != 16366)
Binary download from https://nodejs.org/dist/v10.14.1/node-v10.14.1.tar.xz failed, trying source.
grep: /github/home/.nvm/.cache/src/node-v10.14.1/node-v10.14.1.tar.xz: No such file or directory
Provided file to checksum does not exist.

2019-06-06-15-205299500  Installing GCP SDK ...

deb http://packages.cloud.google.com/apt cloud-sdk-bionic main
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1326  100  1326    0     0   7325      0 --:--:-- --:--:-- --:--:--  7325
OK
Hit:1 http://archive.ubuntu.com/ubuntu bionic InRelease
Get:2 http://packages.cloud.google.com/apt cloud-sdk-bionic InRelease [6372 B]
Get:3 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Get:4 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Get:5 http://packages.cloud.google.com/apt cloud-sdk-bionic/main amd64 Packages [75.3 kB]
Hit:6 http://archive.ubuntu.com/ubuntu bionic-backports InRe
`

**Comment by thedarkwriter** [comment]
Looks like anything that unpacks or copies to /github/home will hit that error 
cp: error writing './static/app/account/views/user-reviews.directive.html': No space left on device

**Comment by maxheld83** [comment]
yup, same problem.

The only fix I got is to go nuclear:

- `rm -rf  ~/Library/Containers/com.docker.docker/Data/vms/0/Docker.qcow2`
- restart the docker daemon
- download all upstream images from scratch

**Warning: this is a destructive action; be careful**

**Comment by thedarkwriter** [comment]
@maxheld83 I was considering remapping home on the fly away from /github/home (though I know that's shimming away from how actions actually work). If that doesn't work I will likely try your nuke.

**Comment by cplee** [comment]
Latest release of act (`0.2.2`) is using docker volumes rather than bind mounts.

**Comment by ureciocais** [comment]
Hi, I'm getting "no space left on device" on v0.2.35
Using this image: catthehacker/ubuntu:full-latest

**Comment by liudmylaru** [comment]
hi! @ureciocais according message above from cplee act >= 0.2.2 is using volumes, you can try clean that space (used by volumes) with this command "docker volume prune --force". For me - it helped. I am using act v0.2.40, and image "nektos/act-environments-ubuntu:18.04". Had the same error.

**Comment by thinhnkworks** [comment]
✅ I solved the problem on my Macbook M3 Pro
My configuration:
`act version: 0.2.68`
`docker version: 27.2.0`
I fixed this problem by adding more spaces to Docker

Here is how I did that:
Go to Docker Desktop -> Settings -> Resources -> Change virtual disk limit to 200GB (previously I used 64GB)

**Comment by bilogic** [comment]
> Here is how I did that: Go to Docker Desktop -> Settings -> Resources -> Change virtual disk limit to 200GB (previously I used 64GB)

Any idea how to do this on the CLI?
