### ISSUE TITLE
Unable to parse and validate if there is an action on a schedule in the workflow

### ISSUE THREAD

**Issue by HoughIO** [nektos/act#61]
I have an action that runs on a schedule.

`act` fails to run if it's present in the main.workflow file.

Example output:
```
Error: unable to parse and validate
  Line 21: Workflow `WORKFLOW' has unknown `on' value `schedule(0 9 * * *)'
  Line 133: Workflow `WORKFLOW2' has unknown `on' value `schedule(0 16 * * 2)'
```

Following this documentation for chrons:
https://developer.github.com/actions/managing-workflows/creating-and-cancelling-a-workflow/#scheduling-a-workflow

I can remove these for testing and add them back, but thought I would raise an issue.

Thanks for making this tool!

**Comment by olizilla** [comment]
I just hit this too.

**Comment by dahlia** [comment]
Currently `act` vendors [v1.0.0] the [GitHub Actions' official workflow-parser][1], which didn't support [schedule expressions][2] yet.  It would be fixed if we change `act` to vendor https://github.com/actions/workflow-parser/commit/ca95f9c491c6adc6f126bbc5dbe39d77a5b6d2a4 or later than that.

[v1.0.0]: https://github.com/actions/workflow-parser/tree/v1.0.0
[1]: https://github.com/actions/workflow-parser
[2]: https://github.com/actions/workflow-parser/pull/43

**Comment by creatorrr** [comment]
@dahlia seems to work locally, happy to make a PR unless @nektos has it planned in an upcoming release?

**Comment by cplee** [comment]
doesn't apply after release of github actions v2
