### ISSUE TITLE
Issue: unable to get git repo: section "remote \"origin\"" does not exist 

### ISSUE THREAD

**Issue by johannesanchez** [nektos/act#615]
## Act version
act version 0.2.21

```none

```

## Expected behaviour
$ sudo act -n
*DRYRUN* [Deploy CloudFormation Stack - Beanstalk,S3/deploy] 🚀  Start image=node:12.20.1-buster-slim
*DRYRUN* [Deploy CloudFormation Stack - Beanstalk,S3/deploy]   🐳  docker run image=node:12.20.1-buster-slim platform=linux/amd64 entrypoint=["/usr/bin/tail" "-f" "/dev/null"] cmd=[]
*DRYRUN* [Deploy CloudFormation Stack - Beanstalk,S3/deploy] ⭐  Run Checkout
*DRYRUN* [Deploy CloudFormation Stack - Beanstalk,S3/deploy]   ✅  Success - Checkout
*DRYRUN* [Deploy CloudFormation Stack - Beanstalk,S3/deploy] ⭐  Run Configure AWS credentials
*DRYRUN* [Deploy CloudFormation Stack - Beanstalk,S3/deploy]   ☁  git clone 'https://github.com/aws-actions/configure-aws-credentials' # ref=v1

## Actual behaviour
$ sudo act
? Please choose the default image you want to use with act:

  - Large size image: +20GB Docker image, includes almost all tools used on GitHub Actions (IMPORTANT: currently only ubuntu-18.04 platform is available)
  - Medium size image: ~500MB, includes only necessary tools to bootstrap actions and aims to be compatible with all actions
  - Micro size image: <200MB, contains only NodeJS required to bootstrap actions, doesn't work with all actions

Default image and other options can be changed manually in ~/.actrc (please refer to https://github.com/nektos/act#configuration for additional information about file structure) Micro
WARN[0032] unable to get git repo: section "remote \"origin\"" does not exist 
[Deploy CloudFormation Stack - Beanstalk,S3/deploy] 🚀  Start image=node:12.20.1-buster-slim
WARN[0032] unable to get git repo: section "remote \"origin\"" does not exist 

## Workflow and/or repository

<details>
  <summary>workflow</summary>

```none
name: example workflow

on: [push]

jobs:
  [...]
```

</details>

## Steps to reproduce
1. Install act
curl https://raw.githubusercontent.com/nektos/act/master/install.sh | sudo bash

2. act in dry-run mode 
act -n 

## `act` output

<details>
  <summary>Log</summary>

```none

```

</details>

**Comment by catthehacker** [comment]
Hi, please correct the issue.
Missing remote is only a warning.
