### ISSUE TITLE
Issue: 

### ISSUE THREAD

**Issue by spielhoelle** [nektos/act#634]
## Act version

```none
act version 0.2.20
```

## Expected behaviour
`act -l` should show available jobs while using `on: [repository_dispatch]` without invoking explicit trigger. With `act repository_dispatch` it works

## Actual behaviour
`act -l` is not showing available jobs when using `on: [repository_dispatch]` and not infers the only event in my workflow.

## Workflow and/or repository

<details>
  <summary>workflow</summary>

```none
name: deploy
on: [repository_dispatch] # doesn't work. `on: [push, repository_dispatch`]` works
jobs:
  deploy-remote-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Event Information
        run: |
          echo "Event '${{ github.event.action }}' received from '${{ github.event.client_payload.repository }}'" 
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Run playbook
        if: github.event.action == 'trigger_deploy'
        uses: saubermacherag/ansible-playbook-docker-action@v1.3
  [...]
```

</details>

## `act` output

<details>
  <summary>Log</summary>

```none
$ act -l
ID  Stage  Name  
```

</details>

**Comment by catthehacker** [comment]
The behaviour is correct.
https://github.com/nektos/act#commands
You can use `--detect-event` to not type specific event in `act`
https://github.com/nektos/act#flags

**Comment by spielhoelle** [comment]
Cool, didn't filter that out of the docs. Thank you
