### ISSUE TITLE
Enhancement: Secrets Exec Support

### ISSUE THREAD

**Issue by RichiCoder1** [nektos/act#636]
## Describe feature
Support for the ability specify a command to exec, who's stdout is then read as if it was a `.secrets` file.

We use a lot of dynamic tools to upsert some special values into GitHub Secrets by reading a special file in the repo. It'd be super helpful to be able to just execute a script as part of the `act` run like below to dynamically retrieve and populate those secrets.

```bash
# .actrc
--secret-exec .github/get_secrets
```

#### Alternatives
Just run
```bash
.github/get_secrets > .secrets
act
# rm .secrets
```

**Comment by catthehacker** [comment]
`sh`/`bash`/`zsh`:
```bash
act -s SOMETHING="$(.github/get_secrets)"
```
`fish`:
```fish
act -s SOMETHING=(.github/get_secrets)
```
