### ISSUE TITLE
[Build] Issue: MacOS Github Docker Install Times are crazy

### ISSUE THREAD

**Issue by JustinGrote** [nektos/act#641]
MacOS Tests can take nearly a half hour to run, most of that is a very variable amount of time to install docker. Recommend disabling it until a more stable method can be defined (use cache action after docker is installed maybe?)

https://github.com/nektos/act/runs/2444025568?check_suite_focus=true

**Comment by catthehacker** [comment]
I'm aware of this but this is a problem with GitHub Actions, their macOS runners are just 😿 I'm working on getting self-hosted mac to have it as runner

**Comment by catthehacker** [comment]
Got install time below 5 minutes, currently trying to polish the install

**Comment by catthehacker** [comment]
![image](https://user-images.githubusercontent.com/31106839/116429973-af783580-a846-11eb-8afc-40db713d6454.png)
😉

**Comment by catthehacker** [comment]
I think this is quite ok-ish time for tests.

**Comment by JustinGrote** [comment]
Yep well into the "good enough" category, thanks!
