### ISSUE TITLE
[Build] Should the test* Github Action workflows changed to workflow_dispatch?

### ISSUE THREAD

**Issue by JustinGrote** [nektos/act#644]
I keep seeing these test workflows run on all actions but they appear to have been experiments rather than any kind of testing or gatekeeping check. Should they be switched to manual triggers so they aren't running all the time or is there a benefit I'm not seeing here?
![image](https://user-images.githubusercontent.com/15258962/116451993-0e6f8780-a812-11eb-9ccb-d80e08118700.png)

**Comment by catthehacker** [comment]
Nope, they should be running all the time. Those are generated by tests and are verifying behaviour between `act` and GitHub Actions:
- `test-if.yml` in `run_context_test.go`
- `test-expressions.yml` in `expression_test.go`
- `test-composite.yml` was added due to [misunderstanding](https://github.com/nektos/act/pull/514#pullrequestreview-622854385) but it does no harm

**Comment by JustinGrote** [comment]
Apparently i only spot checked test-composite. All good!

**Comment by JustinGrote** [comment]
@catthehacker  sorry, I reviewed the test and I don't see where it's actually being verified, it just writes out the test
![image](https://user-images.githubusercontent.com/15258962/116453676-044e8880-a814-11eb-8801-9312f16d9e3f.png)

And the resulting workflow isn't in the list of checks for PRs. Are you manually reviewing them or what am I missing?

**Comment by catthehacker** [comment]
if you run `act` in `act/` it will verify it ;)

**Comment by JustinGrote** [comment]
Fair...

**Comment by catthehacker** [comment]
> @catthehacker sorry, I reviewed the test and I don't see where it's actually being verified, it just writes out the test
> ![image](https://user-images.githubusercontent.com/15258962/116453676-044e8880-a814-11eb-8801-9312f16d9e3f.png)
> 
> And the resulting workflow isn't in the list of checks for PRs. Are you manually reviewing them or what am I missing?
> ![image](https://user-images.githubusercontent.com/15258962/116453925-4677ca00-a814-11eb-9bfc-de57bae481c3.png)

@JustinGrote

Actually, no, I thought good that we tested them both in `act` and GHA. Sorry, it's already late and my brain is switching off slowly after work 😄 
https://github.com/nektos/act/blob/f56b21f6c3549b347413d338dfdd0d238eb534b6/pkg/runner/run_context_test.go#L138
https://github.com/nektos/act/blob/f56b21f6c3549b347413d338dfdd0d238eb534b6/pkg/runner/expression_test.go#L187
