### ISSUE TITLE
Issue: Can't find .yml in subdirectory

### ISSUE THREAD

**Issue by davetapley** [nektos/act#646]
## Act version

```none
0.2.21
```

## Expected behaviour

`act -l` will find `.yml`s which are nested in subdirectories below `.github/workflows/`
(e.g. `.github/workflows/foo/bar.yml`).

## Actual behaviour

`.yml`s which are nested in subdirectories are not found

## Workflow and/or repository

N/A

## Steps to reproduce

1. Have `.yml`s which are nested in subdirectories below `.github/workflows/` which contain default event
2. Run `act -l`

## `act` output

_this output intentionally left blank_ 😁

**Comment by davetapley** [comment]
I think here is the problem?

https://github.com/nektos/act/blob/f56b21f6c3549b347413d338dfdd0d238eb534b6/pkg/model/planner.go#L66

**Comment by catthehacker** [comment]
@davetapley #648 will fix the issue
