### ISSUE TITLE
Enhancement: working with git worktree

### ISSUE THREAD

**Issue by Steph0** [nektos/act#657]
## Describe feature

For a working act workflow, when you are using `git worktree` ACT does not work. It does not fill repository data, certainly because it does not follow links in `.git` file in a git worktree.

If there is a workaround, i'd take it! :)

Example:
```
WARN[0000] unable to get git repo: unable to find git repo
WARN[0000] unable to get git revision: unable to find git repo
WARN[0000] unable to get git ref: unable to find git repo
WARN[0000] unable to get git repo: unable to find git repo
WARN[0000] unable to get git revision: unable to find git repo
WARN[0000] unable to get git ref: unable to find git repo
```

```
$ cat .git
gitdir: /home/xxx/yyy/zzz.git/worktrees/dev
```

**Comment by lvlrt** [comment]
@catthehacker Thanks for creating this tool, I've made a PR for this feature
#829

**Comment by catthehacker** [comment]
Thank @cplee, I'm just trying to maintain it 🐱‍💻

**Comment by lvlrt** [comment]
@cplee thx!

**Comment by Steph0** [comment]
Awesome @lvlrt, thanks 🤩

**Comment by mattalexx** [comment]
Just got bit by this one. Is there a timeline for merging the PR?

**Comment by catthehacker** [comment]
No, because it doesn't work
