### ISSUE TITLE
Issue: actions copied into _actions do interfer with project

### ISSUE THREAD

**Issue by KnisterPeter** [nektos/act#669]
## Act version

```none
act version 0.2.21
```

## Expected behaviour

If a project has workflows and uses act to execute them, there should be no need to change the project configuration.

## Actual behaviour

Act copies the actions used in a workflow into the `$HOME/_actions` folder.
If typescript project contains a `tsconfig.json` like below, and the actions in `_actions` are written in typescript, a build will fail.

```json
{
  "compilerOptions": {
    "rootDir": "./src"
  }
}
```

The compiler does take the `_action/**/*.ts` files into account, but they are not part of the `rootDir`.
It would be better to have the `_actions` outside of the projects home.

**Comment by papb** [comment]
In my case, I have a lint workflow that is trying to lint source code from actions:

```
_actions/actions-setup-node@v1/jest.config.js:2:1
✖    2:1   Expected indentation of 1 tab but found 2 spaces.                         indent
✖    3:1   Expected indentation of 1 tab but found 2 spaces.                         indent
```
