### ISSUE TITLE
Custom event.json

### ISSUE THREAD

**Issue by helaili** [nektos/act#7]
Do you have any plans for allowing users to provide a custom event.json file?

**Comment by cplee** [comment]
@helaili I hadn't considered, but great idea!  How would you want to use it?  Something like `act -e my-event.json`?

**Comment by helaili** [comment]
Yes, that would be ✨

**Comment by cplee** [comment]
this is now available in [v0.0.4](https://github.com/nektos/act/releases/tag/v0.0.4)
