### ISSUE TITLE
Issue: <shortly describe issue>

### ISSUE THREAD

**Issue by IgorGanapolsky** [nektos/act#705]
## Act version
0.2.22

## Expected behaviour
Should be able to run `act`

## Actual behaviour
> Error: Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

## Workflow and/or repository
<details>
  name: Development Workflow

# Triggers the workflow on push or pull request to develop branch
on:
  push:
    branches:
      - 'develop'
  pull_request:
    branches:
      - 'develop'

# Where will they run
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build the project
        run: ./gradlew build

      - name: Run Unit Tests
        run: ./gradlew test

</details>

## Steps to reproduce
Run the above GH Actions yml script.

**Comment by catthehacker** [comment]
The issue seems to be with your Docker daemon rather than `act`.

https://github.com/moby/moby/issues/32270#issuecomment-340709035
