### ISSUE TITLE
don't set GITHUB_SHA when working tree is unclean

### ISSUE THREAD

**Issue by maxheld83** [nektos/act#71]
it appears that even when the working tree is unclean, act sets the `GITHUB_SHA` env var to whatever the last  git commit on that branch was.

This seems friendly, but can lead to some pretty unexpected behavior, because AFAIK act *actually* runs with the unclean working tree, so the `GITHUB_SHA` is actually kind of wrong.

In any kind of situation where you're referencing something via `GITHUB_SHA` this can get weird (e.g. I am `FROM:`ing Docker images in the version of the `GITHUB_SHA`).

I think it would be safer behavior to either:
- don't set a `GITHUB_SHA` when the working tree is unclean
- do not allow act to run on an unclean working tree (safest of them all maybe, because that's how github actions actually works, it never runs on unclean trees).

**Comment by themightychris** [comment]
In the spirit of act, it would be nice if you could run it against working trees, act could do something like this:

```bash
export GIT_INDEX_FILE="$(git rev-parse --git-dir)/index.act"
git reset HEAD
git add --all
WORK_TREE_HASH=$(git write-tree)
export GITHUB_SHA=$(git commit-tree -p HEAD -m "snapshot working tree" ${WORK_TREE_HASH})
```

**Comment by themightychris** [comment]
hey bot, this is still a good idea! And it has concrete implementation notes
