### ISSUE TITLE
Have to delete action container in order to run new changes

### ISSUE THREAD

**Issue by 20k-ultra** [nektos/act#715]
I'm unable to find any flag or mention of making act rebuild the action image. I am forced to delete the image which is very time consuming and misses out on layer caching.

Is there a way to tell act to run my action and build the image every time ?

**Comment by catthehacker** [comment]
Currently there isn't

**Comment by josecelano** [comment]
`act` generates the docker image with this a command like this:

```
docker build -t act-github-actions-your-action:latest --platform  /home/your-repo/.github/actions/your-action
```

I used to delete the image before running the job with:

```
docker image rm act-github-actions-your-action
```

That forces the docker to re-build the docker image. It worked for me but for some reason, it's not working anymore.

**Comment by 20k-ultra** [comment]
I forgot to include some context that I think is important...I'm using act to actually develop an action not workflow. I think act is intended for action users to test their workflow which explains why you don't have a way to rebuild the docker image everytime.

So to be clear, I am working on an action which is a docker container that I was using act to then trigger. I'm doing this because Github does not offer any other sane way of developing actions that I know of. Since act couldn't rebuild the container I just made a npm run command to load some env vars from a env file which allowed the octokit module to be populated with the context and webhook data just like when running it via act/github.com.
