### ISSUE TITLE
respect local and global gitignore

### ISSUE THREAD

**Issue by maxheld83** [nektos/act#72]
I have a project which creates local `*.so` on compilation.
These are never git commited (naturally). They appear to be gitignored because of a system (default?) `.gitignore`.

It would be good if `act` could similarly respect any local or global/default `.gitignore`s.

Otherwise, this can lead to thorny problems, in this case, a bad ELF header.

Perhaps act should simply commit whatever is on the working tree as a first step, maybe in a tempdir and run from there.
By relying on the local `git add/commit` we'd automatically respect whatever `.gitignore` action was in place

**Comment by cplee** [comment]
duplicates #50
