### ISSUE TITLE
Fallback to a default `runs-on` tag when `self-hosted` is defined

### ISSUE THREAD

**Issue by dimisjim** [nektos/act#741]
## Expected behaviour

act should still work, even when the self-hosted runs-on tag is used. 

The action runs locally anyway, so it doesn't really make much sense for ack to fail when it detects the `self-hosted` flag.

It would be nice then for ack to ask for a preferred platform when it detects the `self-hosted` tag.

## Actual behaviour

Getting this output instead:

```
[myAwesomeWorkflow/myAwesomeJob] 🚧  Skipping unsupported platform 'self-hosted'
[myAwesomeWorkflow/myAwesomeJob] 🚧  Skipping unsupported platform 'dynamic'
```

**Comment by catthehacker** [comment]
You can run `self-hosted` with `-P`

```powershell
cat [7.1.3] ~/../../../../act git: upstream ≣
❯❯❯ go run main.go -W .\.github\workflows\self-hosted.yml
[self-hosted.yml/lint] 🚧  Skipping unsupported platform 'self-hosted'

cat [7.1.3] ~/../../../../act git: upstream ≣ +1 ~0 -0 ! 
❯❯❯ go run main.go -W .\.github\workflows\self-hosted.yml -P self-hosted=catthehacker/ubuntu:act-latest
[self-hosted.yml/lint] 🚀  Start image=catthehacker/ubuntu:act-latest
Error: unable to determine if image already exists for image "catthehacker/ubuntu:act-latest" (): Error response from daemon: Bad response from Docker engine
exit status 1
```

**Comment by catthehacker** [comment]
Like example above

**Comment by florian30491** [comment]
Hi @catthehacker,

according to the GitHub documentation (https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#choosing-self-hosted-runners) the runner should just be called when all labels are matching the runner description:

> When you specify an array of labels, jobs will be queued on runners that have all the labels that you specify.

Is there a possibility to define that the docker container is with the labels `[self-hosted, linux]` ?

**Comment by ChristopherHX** [comment]
> runner should just be called when all labels are matching the runner description:

Correct, but this is not github actions and act matches one of multiple labels to select the target image. You can call it a bug.

> Is there a possibility to define that the docker container is with the labels [self-hosted, linux] ?

I think the answer is no.

You can do both, until someone adds support for that:
- `act -P self-hosted=catthehacker/ubuntu:act-latest`
- `act -P linux=catthehacker/ubuntu:act-latest`

My _act clone_ correctly handles multiple labels ( https://github.com/ChristopherHX/runner.server#troubleshooting ) also it uses an action/runner agent to run your steps
- `gharun -P self-hosted,linux=catthehacker/ubuntu:act-latest` _order of the labels and case of the labels are irrelevant_
