### ISSUE TITLE
[Apple Silicon] Failure 255   

### ISSUE THREAD

**Issue by AndreiCalazans** [nektos/act#742]
## System information

- Operating System: macOS
- Architecture: arm64 (64-bit) 
- Apple M1: yes
- Docker version:  Server Version: 20.10.6
- Docker image used in `act`: catthehacker/ubuntu:act-latest
- `act` version: act version 0.2.23

## Expected behaviour

I expected to be able to use act with a Silicon Mac

## Actual behaviour

Running `act` in the command line outputs:

```
Docker Image CI/build] 🚀  Start image=catthehacker/ubuntu:act-latest
[Docker Image CI/build]   🐳  docker run image=catthehacker/ubuntu:act-latest platform= entrypoint=["/usr/bin/tail" "-f" "/dev/null"] cmd=[]
[Docker Image CI/build]   🐳  docker exec cmd=[mkdir -m 0777 -p /var/run/act] user=root
[Docker Image CI/build] ⭐  Run Login to DockerHub
INFO[0000]   ☁  git clone 'https://github.com/docker/login-action' # ref=v1
[Docker Image CI/build]   🐳  docker cp src=/Users/andreicalazans/.cache/act/docker-login-action@v1/ dst=/var/run/act/actions/docker-login-action@v1/
[Docker Image CI/build]   🐳  docker exec cmd=[mkdir -p /var/run/act/actions/docker-login-action@v1/] user=
[Docker Image CI/build]   🐳  docker exec cmd=[node /var/run/act/actions/docker-login-action@v1/dist/index.js] user=
| /lib64/ld-linux-x86-64.so.2: No such file or directory
[Docker Image CI/build]   ❌  Failure - Login to DockerHub
Error: exit with `FAILURE`: 255


```

## Steps to reproduce

On a M1 Mac:

1) brew install act
2) act

**Comment by catthehacker** [comment]
Can you try running it again with `--container-architecture linux/amd64`?

**Comment by catthehacker** [comment]
Also it seems you leaked your API password

**Comment by AndreiCalazans** [comment]
Would you be kind enough to delete the revision history. I don't seem to have that option 
![Screen Shot 2021-06-22 at 16 18 12](https://user-images.githubusercontent.com/20777666/122986171-74d9d780-d375-11eb-9c77-819ed1bcadaf.png)

**Comment by AndreiCalazans** [comment]
And thank you. The `--container-architecture linux/amd64` works

I learned a lesson to validate what I'm copying and pasting.🤦‍♂️

**Comment by catthehacker** [comment]
Since you are using Apple with M1 CPU which is `arm64`, it tries to use `arm64` CPU architecture so you need to specify manually the platform.
I will remove `arm64` or try to make it show some useful information regarding Apple M1/arm64
