### ISSUE TITLE
Enhancement: Allow for spawning a shell on failure

### ISSUE THREAD

**Issue by fugkco** [nektos/act#755]
Would be nice to get act to a spawn a shell on error to investigate what might be going wrong.

Something along the lines of:

```
$ act --shell-on-error
...
root@host:/tmp/testing#
```

**Comment by catthehacker** [comment]
You can use `docker exec -ti <container> <executable>` to run shell or anything else in it

**Comment by fugkco** [comment]
Cool. Thanks! Only after I raised this feature request did I realise that act doesn't clean up the containers after the run.

**Comment by catthehacker** [comment]
Since we support running multiple workflows and matrixes at the same time I don't think it would be good to implement this (at least for now) as we would have to do lots of weird things and the way it would work at most would be confusing to users.
Closing for now
