### ISSUE TITLE
problem with secret file and docker socket

### ISSUE THREAD

**Issue by orcutt989** [nektos/act#759]
`image` catthehacker/ubuntu:full-20.04
`act version` 0.2.23

If I put `--secret-file ~/path/to/.env` in the `~/.actrc` and do a `act pull_request`, act doesn't seem to be able to parse it. However if I do a `act --secret-file .env` it parses the secrets fine.

When I attempt to do an `npm install` I get a

```bash
[Pulumi/Preview] ⭐  Run npm install
[Pulumi/Preview]   🐳  docker exec cmd=[bash --noprofile --norc -e -o pipefail /Users/username/src/currentdirectory/workflow/3] user=
| npm WARN checkPermissions Missing write access to /Users/username/src/currentdirectory
| npm WARN currentdirectory@ No repository field.
| npm WARN currentdirectory@ No license field.
|
| npm ERR! code EACCES
| npm ERR! syscall access
| npm ERR! path /Users/username/src/currentdirectory
| npm ERR! errno -13
| npm ERR! Error: EACCES: permission denied, access '/Users/username/src/currentdirectory'
| npm ERR!  [Error: EACCES: permission denied, access '/Users/username/src/currentdirectory'] {
| npm ERR!   errno: -13,
| npm ERR!   code: 'EACCES',
| npm ERR!   syscall: 'access',
| npm ERR!   path: '/Users/username/src/currentdirectory'
| npm ERR! }
| npm ERR!
| npm ERR! The operation was rejected by your operating system.
| npm ERR! It is likely you do not have the permissions to access this file as the current user
| npm ERR!
| npm ERR! If you believe this might be a permissions issue, please double-check the
| npm ERR! permissions of the file and its containing directories, or try running
| npm ERR! the command again as root/Administrator.
|
| npm ERR! A complete log of this run can be found in:
| npm ERR!     /home/runner/.npm/_logs/2021-07-20T21_14_10_144Z-debug.log
[Pulumi/Preview]   ❌  Failure - npm install
Error: exit with `FAILURE`: 243
```

I'm hoping to not have to `sudo npm install` as this is not something that needs to be done in GitHub actions.

If I do a `act -b --secret-file .env pull_request` it gets further, but then I get a docker socket problem when I run Pulumi. I've already confirmed with @catthehacker that it is not an image problem.

```
error: time="2021-07-20T18:25:01Z" level=error msg="failed to dial gRPC: cannot connect to the Docker daemon. Is 'docker daemon' running on this host?: dial unix /var/run/docker.sock: 
```

Thanks!

**Comment by catthehacker** [comment]
`act` doesn't handle non-root users well *yet*, and since full image is using `runner` user just like GitHub Actions it breaks in many places

**Comment by orcutt989** [comment]
Gotcha! What are some possible workarounds that don't involve me changing the current workflow files from what GitHub Actions uses

**Comment by catthehacker** [comment]
as for the bind `-b`, it doesn't work because macOS uses a VM and operates it via TCP instead of UNIX socket and `DOCKER_*` envvars are not forwarded to container.
Currently there is no workaround for any of those issues

**Comment by orcutt989** [comment]
Ok so temporarily I could just throw in a run su - into my local ci files?

**Comment by catthehacker** [comment]
that should work

**Comment by orcutt989** [comment]
Argh didnt work. Act just hangs at
```
[Pulumi/Preview]   🐳  docker exec cmd=[bash --noprofile --norc -e -o pipefail /Users/username/src/currentdirectory/workflow/0] user=
```

**Comment by orcutt989** [comment]
`su -` is waiting for password.  `sudo su` should switch `runner` to `root`, but act also hangs on this as well if i add a `run: sudo su`

**Comment by orcutt989** [comment]
I switched to the medium image `catthehacker/ubuntu:act-latest` and that seems to user the root user, but now it doesnt seem like my `npm install` is working.

**Comment by orcutt989** [comment]
Nevermind it was because `aws` wasn't installed in the medium image.
