### ISSUE TITLE
YAML syntax support

### ISSUE THREAD

**Issue by thalesvon** [nektos/act#76]
Hey guys, as GitHub announced the new syntax for workflow, is there an expectation of act to support this as well?

[Github Action YAML](https://help.github.com/en/articles/migrating-github-actions-from-hcl-syntax-to-yaml-syntax)

**Comment by acaloiaro** [comment]
FYI this is duplicating https://github.com/nektos/act/issues/74. You all may want to merge these together.

**Comment by WoLfulus** [comment]
I'd love this too. Just started working with GitHub actions and I started with yaml directly

**Comment by cplee** [comment]
see #74
