### ISSUE TITLE
Actions Container image is misinterpreted when using own registry with short oci url

### ISSUE THREAD

**Issue by FloThinksPi** [nektos/act#795]
## System information

- Operating System: MacOS
- Architecture: x64 (64-bit)
- Apple M1:  no 
- Docker version: 20.10.8
- `act` version: act version 0.2.24

## Expected behaviour

Pulls the correct image

## Actual behaviour

Adds docker.io to the image which already has a private repo specified and thus the url is invalid.

## Workflow and/or repository

<details>
  <summary>workflow</summary>

```none
jobs:
  myjob:
    runs-on: [self-hosted, linux]
    name: test job
    container:
      image: myregistry:50000/ubuntu:20.04
```

</details>

## Steps to reproduce

Create workflow with custom container image in job step(see workflow file above).
Watch pull fail.

## `act` output

If i just do a act without verbose i get:
```
[Run database tests/Run psql db tests] 🚀  Start image=myregistry:50000/ubuntu:20.04
Error: invalid reference format
```
So image pull URL looks fine. 

However if i do act -vvv  on the same workflow i get:
```
[Run database tests/Run psql db tests]   🐳  docker pull myregistry:50000/ubuntu:20.04
DEBU[0000] Image exists? false                          
[Run database tests/Run psql db tests] pulling image 'docker.io/myregistry:50000/ubuntu:20.04' ()
DEBU[0000] invalid reference format                     
```
So here one can see it puts a docker.io in front of the already complete OCI Resource URL.
Then it fails as this obviously is not allowed.

**Comment by FloThinksPi** [comment]
It seems to work if i use:
`myrepo:50000/library/ubuntu:20.04` 
Then the correct image is pulled.

I think act has some logic in it that interprets `myrepo:50000/ubuntu:20.04` as `myrepo:50000` beeing the username and `ubuntu` beeing the image and `20.04` beeing the tag. So it appends docker.io as registry url then. 

However Docker pull on `myrepo:50000/ubuntu:20.04` works as expected though and pulls the right image. So i think it is actually wanted to pull the image that the container runtime would pull. So to interpret `myrepo:50000` as url and not as username in that case.

**Comment by catthehacker** [comment]
https://github.com/nektos/act/blob/6e5bd2472875e217b48d5abd4b103a7c20b33127/pkg/container/docker_pull.go#L100-L109

**Comment by catthehacker** [comment]
Not stale, will fix that this weekend
