### ISSUE TITLE
Didn't work with YAML

### ISSUE THREAD

**Issue by kusmayadi** [nektos/act#80]
It didn't work with the new yaml syntax (https://help.github.com/en/github/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions). 

When running `act -f .github/workflows/main.yml -l`, I got: 

```
Error: unable to parse
  Line 1: illegal char
```

**Comment by finalspy** [comment]
Isn't it a duplicate of #74 and #76 ?
