### ISSUE TITLE
exec: "node": executable file not found in $PATH: unknown

### ISSUE THREAD

**Issue by GabrieleCalarota** [nektos/act#834]
## System information

- Operating System:
- Architecture:
- Apple M1:
- Docker version:
- Docker image used in `act`:
- `act` version:

## Workflow and/or repository

https://github.com/SquisEat/pull-request-comment-trigger
<details>
  <summary>workflow</summary>

```none
name: Pull Request Comment Trigger Example
on:
  pull_request:
    types: [opened]
  issue_comment:
    types: [created]

jobs:

  eyes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: "pull-request-comment-trigger"

      - name: Setup NodeJS 14
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - uses: ./
        id: check
        with:
          trigger: 'look'
          prefix_only: 'true'
          reaction: rocket
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      - run: 'echo Found it!'
        if: steps.check.outputs.triggered == 'true'
```

</details>

## `act` output

<details>
  <summary>Log</summary>

```none
DEBU[0002] Removing /home/gabriele/.cache/act/actions-setup-node@v1/.gitignore before docker cp 
[Pull Request Comment Trigger Example/eyes]   🐳  docker cp src=/home/gabriele/.cache/act/actions-setup-node@v1 dst=/actions/
[Pull Request Comment Trigger Example/eyes] Exec command '[mkdir -p /actions/]'
DEBU[0002] Writing tarball /tmp/act446402006 from /home/gabriele/.cache/act/actions-setup-node@v1 
DEBU[0002] Stripping prefix:/home/gabriele/.cache/act/ src:/home/gabriele/.cache/act/actions-setup-node@v1 
[Pull Request Comment Trigger Example/eyes] Extracting content from '/tmp/act446402006' to '/actions/'
DEBU[0002] executing remote job container: [node /actions/actions-setup-node@v1/dist/index.js] 
[Pull Request Comment Trigger Example/eyes] Exec command '[node /actions/actions-setup-node@v1/dist/index.js]'
| OCI runtime exec failed: exec failed: container_linux.go:380: starting container process caused: exec: "node": executable file not found in $PATH: unknown
[Pull Request Comment Trigger Example/eyes]   ❌  Failure - Setup NodeJS 14
DEBU[0003] exit with `FAILURE`: 126                     
DEBU[0003] exit with `FAILURE`: 126                     
DEBU[0003] exit with `FAILURE`: 126                     
Error: exit with `FAILURE`: 126
```

</details>

**Comment by catthehacker** [comment]
Please follow the template.

**Comment by ChristopherHX** [comment]
> act version: 0.3.2

Thats odd, this version of act isn't even released yet (act still has version 0.2.x)

Please follow the template and provide the **full** log, not only the part you provided. Your provided log is missing the important part of the log, e.g. which docker image it used to ran your steps.
> Use `act` with `-v`/`--verbose` and paste output from your terminal in code block below

**act requires that the executing docker image has node installed and in `$PATH`**, unlike actions/runner which doesn't require it.

Also which commandline did you use to run act?
`act ...`

_It isn't common to ping a maintainer within 24h after opening an issue_

**Comment by GabrieleCalarota** [comment]
> > **act requires that the executing docker image has node installed and in `$PATH`**, unlike actions/runner which doesn't require it.
> 
> How do I do this? There's no doc in the README.md about this! I think this is the key point here, I've looked on google. I have no clue on this.
> 
> > Also which commandline did you use to run act?
> > `act ...`
> 
> `act -v issue_comment`



> Thats odd, this version of act isn't even released yet (act still has version 0.2.x)

Updated 0.2.14

**Comment by catthehacker** [comment]
Current act release is v0.2.24 (https://github.com/nektos/act/releases/tag/v0.2.24)
I recommend using latest version since each version we fix a lot of issues and improve experience
Latest versions for available package managers can be seen in [README.md](https://github.com/nektos/act/blob/master/README.md)

**Comment by catthehacker** [comment]
So everything works now?
