### ISSUE TITLE
Issue: proper workflow fails on Git config and pull with 'exit with FAILURE'

### ISSUE THREAD

**Issue by datapolitical** [nektos/act#844]
Having solved the issue below (the secrets needed to be in .secrets), I've encountered a slightly different one that I can tell has to do with the GITHUB_TOKEN as I've seen others write about related issues.

With the same commands as below, I'm now getting this response:
```
git config --local user.name datapolitical
git config --local user.email datapolitical@gmail.com
git pull --ff-only origin main

' to 'workflow/3' 
DEBU[0090] Writing entry to tarball workflow/3 len:128  
[Build and Deploy to Github Pages/get_data] Extracting content to '/Users/chris/Documents/GitHub/chrisfnicholson'
[Build and Deploy to Github Pages/get_data]   🐳  docker exec cmd=[bash --noprofile --norc -e -o pipefail /Users/chris/Documents/GitHub/chrisfnicholson/workflow/3] user=
[Build and Deploy to Github Pages/get_data] Exec command '[bash --noprofile --norc -e -o pipefail /Users/chris/Documents/GitHub/chrisfnicholson/workflow/3]'
| Warning: Permanently added the RSA host key for IP address 'XXX.XXX.XXX.XXX' to the list of known hosts.
| git@github.com: Permission denied (publickey).
| fatal: Could not read from remote repository.
| 
| Please make sure you have the correct access rights
| and the repository exists.
DEBU[0091] exit with `FAILURE`: 1                       
```

What's the recommended solution here? I have a valid SSH key for the repo on my local machine. Do I need to specify that somewhere? I obviously don't have a GitHub token and I'd prefer not to generate yet another PAT unless I have to (that's why I use GITHUB_TOKEN) in the repo in the first place. But if that's the ideal solution, I can.

Thanks!

---
I'm running an action which crashes which runs fine on GIthub but fails in act when it reaches this step:

      - name: setup git config
        run: |
          git config --local user.name ${{ secrets.USERNAME_GITHUB }}
          git config --local user.email ${{ secrets.EMAIL }}
          git pull --ff-only origin main

## System information

    - Operating System: Mac
    - Architecture: x64 (64-bit) 
    - Apple M1:  no
    - Docker version: 20.10.6
    - Docker image used in `act`: medium
    - `act` version: act version 0.2.24

## Expected behaviour

The action should run just as it does on the server

## Actual behaviour

the action exits with error 1

## Workflow and/or repository

workflow: https://github.com/datapolitical/chrisfnicholson.github.io/blob/main/.github/workflows/build-jekyll.yml

## Steps to reproduce

1. Clone example repo
2. create .env file with email and GitHub username secrets

## `act` output

<details>
  <summary>Log</summary>

[Build and Deploy to Github Pages/get_data] ⭐  Run setup git config
DEBU[0118] Evaluating 'secrets['USERNAME_GITHUB']' instead of 'secrets.USERNAME_GITHUB' 
DEBU[0118] Evaluating 'secrets['EMAIL']' instead of 'secrets.EMAIL' 
DEBU[0118] Wrote command '
git config --local user.name 
git config --local user.email 
git pull --ff-only origin main

' to 'workflow/3' 
DEBU[0118] Writing entry to tarball workflow/3 len:92   
[Build and Deploy to Github Pages/get_data] Extracting content to '/Users/chris/Documents/GitHub/chrisfnicholson'
[Build and Deploy to Github Pages/get_data]   🐳  docker exec cmd=[bash --noprofile --norc -e -o pipefail /Users/chris/Documents/GitHub/chrisfnicholson/workflow/3] user=
[Build and Deploy to Github Pages/get_data] Exec command '[bash --noprofile --norc -e -o pipefail /Users/chris/Documents/GitHub/chrisfnicholson/workflow/3]'
DEBU[0119] exit with `FAILURE`: 1                       
[Build and Deploy to Github Pages/get_data]   ❌  Failure - setup git config
DEBU[0119] exit with `FAILURE`: 1                       
DEBU[0119] exit with `FAILURE`: 1                       
DEBU[0119] exit with `FAILURE`: 1                       
DEBU[0119] exit with `FAILURE`: 1                       
DEBU[0119] exit with `FAILURE`: 1                       
Error: exit with `FAILURE`: 1

</details>

**Comment by rmunn** [comment]
Does the stale bot provide *any* benefit, other than forcing people to add meaningless comments to keep issues open? IMHO it's a net negative, creating more work and issue spam and producing almost no positive results.

**Comment by CHarnel** [comment]
I've encountered something similar (maybe):
trying to run https://github.com/tj-actions/changed-files action and I have `.secrets` file with PAT in `GITHUB_TOKEN` key. In the same repo another git-related actions work properly (e.g.: https://github.com/stefanzweifel/git-auto-commit-action). And it works on GitHub Actions.
Log:
```
[rollout-prod/rollout] ⭐ Run Main # "Calculating the previous and current SHA..."
bash $GITHUB_ACTION_PATH/diff-sha.sh
[rollout-prod/rollout]   🐳  docker exec cmd=[bash --noprofile --norc -e -o pipefail /var/run/act/workflow/changes-composite-changed-files-diff-sha.sh] user= workdir=
[rollout-prod/rollout]   ❓  ::group::changed-files-diff-sha
[rollout-prod/rollout]   💬  ::debug::Resolving repository path: /Users/.../projects/.../.
| Verifying git version...
| Valid git version found: (2.38.0)
| Running on a push event...
[rollout-prod/rollout]   💬  ::debug::Getting HEAD SHA...
| Warning: Permanently added the RSA host key for IP address '...' to the list of known hosts.
| git@github.com: Permission denied (publickey).
| fatal: Could not read from remote repository.
| 
| Please make sure you have the correct access rights
| and the repository exists.
[rollout-prod/rollout]   ❌  Failure - Main # "Calculating the previous and current SHA..."
bash $GITHUB_ACTION_PATH/diff-sha.sh
[rollout-prod/rollout] exitcode '128': failure
[rollout-prod/rollout]   ⚙  ::set-output:: unknown_files=
[rollout-prod/rollout]   ⚙  ::set-output:: all_modified_files=
[rollout-prod/rollout]   ⚙  ::set-output:: any_modified=
[rollout-prod/rollout]   ⚙  ::set-output:: only_modified=
[rollout-prod/rollout]   ⚙  ::set-output:: only_deleted=
[rollout-prod/rollout]   ⚙  ::set-output:: deleted_files=
[rollout-prod/rollout]   ⚙  ::set-output:: all_old_new_renamed_files=
[rollout-prod/rollout]   ⚙  ::set-output:: any_changed=
[rollout-prod/rollout]   ⚙  ::set-output:: other_deleted_files=
[rollout-prod/rollout]   ⚙  ::set-output:: added_files=
[rollout-prod/rollout]   ⚙  ::set-output:: renamed_files=
[rollout-prod/rollout]   ⚙  ::set-output:: all_changed_files=
[rollout-prod/rollout]   ⚙  ::set-output:: only_changed=
[rollout-prod/rollout]   ⚙  ::set-output:: any_deleted=
[rollout-prod/rollout]   ⚙  ::set-output:: other_changed_files=
[rollout-prod/rollout]   ⚙  ::set-output:: other_modified_files=
[rollout-prod/rollout]   ⚙  ::set-output:: copied_files=
[rollout-prod/rollout]   ⚙  ::set-output:: modified_files=
[rollout-prod/rollout]   ⚙  ::set-output:: type_changed_files=
[rollout-prod/rollout]   ⚙  ::set-output:: unmerged_files=
[rollout-prod/rollout]   ⚙  ::set-output:: all_changed_and_modified_files=
[rollout-prod/rollout]   ❌  Failure - Main Check for changes
[rollout-prod/rollout] exitcode '128': failure
```
