### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by fatbasstard** [nektos/act#867]
## Describe feature
Specifically requiring the `working-directory` fix (https://github.com/nektos/act/pull/772).

Can we get a new release?

**Comment by cplee** [comment]
Just released `v0.2.25` 🎉

**Comment by edmondo1984** [comment]
The working-directory fix is not respected on my Macbook. Is this a known problem / should I open a new issue?

```sh
| OCI runtime exec failed: exec failed: container_linux.go:380: starting container process caused: chdir to cwd ("/Users/me/Development/private/my-project/tooling/deployment/terraform") set in config.json failed: no such file or directory: unknown
[Deploy/Deploy to AWS]   ❌  Failure - terraform init
Error: exit with `FAILURE`: 126
❯ ls /Users/me/Development/private/my-project/tooling/deployment/terraform
job.tf                   outputs.tf               terraform.tfstate        vars.tf
locals.tf                provider.tf              terraform.tfstate.backup
```

**Comment by mimartin12** [comment]
> The working-directory fix is not respected on my Macbook. Is this a known problem / should I open a new issue?
> 
> ```shell
> | OCI runtime exec failed: exec failed: container_linux.go:380: starting container process caused: chdir to cwd ("/Users/me/Development/private/my-project/tooling/deployment/terraform") set in config.json failed: no such file or directory: unknown
> [Deploy/Deploy to AWS]   ❌  Failure - terraform init
> Error: exit with `FAILURE`: 126
> ❯ ls /Users/me/Development/private/my-project/tooling/deployment/terraform
> job.tf                   outputs.tf               terraform.tfstate        vars.tf
> locals.tf                provider.tf              terraform.tfstate.backup
> ```

@edmondo1984  try with the `-b` command, that worked for me.

**Comment by sushi30** [comment]
I am also hitting this issue on WSL2 with Ubuntu 20.04 and Docker on Windows. Adding `-b` is not solving.
