### ISSUE TITLE
Enhancement: Show a downloading line item when retrieving images

### ISSUE THREAD

**Issue by jsoref** [nektos/act#869]
## Describe feature

Using `act version 0.2.24`.

I see:
```
[Test ci/ci] 🧪  Matrix: map[python-version:3.7]
[Test ci/ci] 🚀  Start image=ghcr.io/catthehacker/ubuntu:full-18.04
```

I'm sure that if I used `act -v`, I'd get a download progress arrow.

Instead, it'd be nice if I saw:
```
[Test ci/ci] 🧪  Matrix: map[python-version:3.7]
[Test ci/ci] ⬇️  Downloading image=ghcr.io/catthehacker/ubuntu:full-18.04
```

Then once the image arrived, the current output could be shown:
```
[Test ci/ci] 🧪  Matrix: map[python-version:3.7]
[Test ci/ci] ⬇️  Downloading image=ghcr.io/catthehacker/ubuntu:full-18.04
[Test ci/ci] 🚀  Start image=ghcr.io/catthehacker/ubuntu:full-18.04
```

**Comment by catthehacker** [comment]
I thought I already fixed that but apparently it does not show the message, huh...
https://github.com/nektos/act/blob/11f6ee37a660be806cdb89d9a217d7093ddb30b4/pkg/container/docker_run.go#L136

**Comment by catthehacker** [comment]
Should be available in next release
