### ISSUE TITLE
Enhancement: Alternate or unified API to accomodate Gitlab

### ISSUE THREAD

**Issue by drschwabe** [nektos/act#874]
This maybe not necessarily a feature since perhaps the initiatve would be better spearheaded as sep project entirely (and perhaps hosted on Gitlab) but anyway the idea is to offer an 'act' equivalent but for Gitlab's CI/CD jobs/pipeline API 

I love act and nothing wrong with Github Actions, but when a project comes up and is hosted on Gitlab that kinda makes this tool & expertise around it unavailable.

**Comment by catthehacker** [comment]
GitLab runner allows local execution of CI/CD (it's not hard to set up), I'm not aware if it has dry-run but there isn't much priority to pursue this.

**Comment by drschwabe** [comment]
Okay cool, thanks for clarifying - I will look into setting up GitLab runner

**Comment by drschwabe** [comment]
related discussion: 

https://stackoverflow.com/questions/32933174/use-gitlab-ci-to-run-tests-locally

**Comment by catthehacker** [comment]
Although once all our issues with GitHub are fixed, this can be reconsidered :)

**Comment by mon-jai** [comment]
+1 for this.
