### ISSUE TITLE
Consider using actions/runner

### ISSUE THREAD

**Issue by cplee** [nektos/act#88]
(from [PR #84](https://github.com/nektos/act/pull/84#issuecomment-589245950))

@marcosnils
> Seems like you did an amazing work and effort to implements all this features. The way what I thought about implementing this local runner is to actually use the open source runner (https://github.com/actions/runner) that already has all the logic on how to run and process the workflow yaml files. I'd love to know if you thought about that approach and if so, the main reasons why you chose to implement it yourself. If you believe we can use the open source runner instead, I already did some work around that that I'd like to share.

@cplee 
> I did look at it as my first approach. Ran it locally and captured the API traffic back to GitHub from the runner. The API is very chatty, verbose....and undocumented. Lots of references to VSTS in the API payloads 🤯Looked much more difficult to simulate the API between the runner and GH so I went the direction I did. Would love to hear more about your learnings and I'm happy to reconsider!

@marcosnils
> I haven't checked in detail, but I only saw that the listener can be invoked in something that's called local run (https://github.com/actions/runner/blob/6c70d53eead402ba5d53676d6ed649a04e219c9b/src/Misc/layoutroot/run.sh#L23-L27). I was hoping that option could actually help running stuff locally without having to interact with the VSTS or GH API. Seems like you have better understanding about the runner internals and it might be a dead end?

@cplee
> Looks like it has potential...that's the right idea. Can't find any details on how that works though... 🤔

@marcosnils
> Maybe @TingluoHuang can help us here?

**Comment by ethan797979** [comment]
傳自 iPhone 版的 Yahoo奇摩電子信箱


於 星期五, 4月 24, 2020, 08:06，github-actions[bot] <notifications@github.com> 寫道：




Closed #88.

**Comment by marcosnils** [comment]
What??? @cplee this got closed very strangely

**Comment by torbjornvatn** [comment]
@cplee here's a dockerified version of the local runner that might be interesting to consider https://github.com/myoung34/docker-github-actions-runner
