### ISSUE TITLE
Enhancement: node16 runner

### ISSUE THREAD

**Issue by BeeeQueue** [nektos/act#910]
## Describe feature

The `node16` has finally been added

https://github.com/actions/runner/releases/tag/v2.285.0
https://github.com/actions/runner/issues/772
https://github.com/actions/runner/pull/1439

Currently I get this error when trying to run (after changing the image used to `node:16-buster-slim`):
`Error: The runs.using key in action.yml must be one of: [composite docker node12], got node16`

**Comment by catthehacker** [comment]
`node16` is not available on whole GHA yet

**Comment by BeeeQueue** [comment]
Then we can wait until it is 😄

**Comment by catthehacker** [comment]
I've already added `node16` to the `act` rewrite that has been discussed on our Gitter if anyone wants to test `node16`
https://github.com/catthehacker/act-fork/tree/cat/wip%2Factionlint

TODO tasks for `act`:
- [ ] add `node16` to supported actions
- [ ] add NodeJS 16.x to `medium` image, change `micro` image to Node 16.x as GHA runners switch to it as well (https://github.com/actions/virtual-environments/issues/4446)
- [ ] add logic to `act` to use Node 16/12 for `node16`/`node12` respectively, `micro` image will have to run with single version

**Comment by josecelano** [comment]
Hi, I'm getting that error:

```
Error: The runs.using key in action.yml must be one of: [composite docker node12], got node16
```

I'm running act with:

```
docker pull node:16-buster-slim
act -P ubuntu-latest:node:16-buster-slim - p -w ./.github/workflows/test.yml -j hello_world_job
```

I have created this [sample repo](https://github.com/josecelano/gh-action-sample-node-16) to reproduce the error.

Is this already working @catthehacker? I see there are two pending tasks above but the PR was merged.

**Comment by catthehacker** [comment]
> Is this already working @catthehacker?

It is, but most likely you are using v0.2.25 which doesn't have that change

**Comment by NickLiffen** [comment]
👋 any thought on when:

> [ ] add NodeJS 16.x to medium image

Is going to be completed. I am using the medium image and node16 but getting this error, it would be great if this was supported 💯 ❤️

**Comment by BeeeQueue** [comment]
Installing the latest master build with `go install github.com/nektos/act@master` works for me, I can run my actions with `using: node16`

**Comment by NickLiffen** [comment]
Really 🤔 

[This](https://github.com/NickLiffen/csenv/blob/main/Dockerfile#L54) is how I am installing it.

E.G

```
curl https://raw.githubusercontent.com/nektos/act/master/install.sh | sudo bash
```

I re-build my environment every night to pull the latest and greatest. 

I don't have `go` installed (and don't really want to install go just for the sake of pulling this down).

I just double-checked and it doesn't work for me. 🤔 (Something Codespaces is meant to solve haha)

**Comment by BeeeQueue** [comment]
From what I can tell from reading the install script it downloads binaries from the releases, but the changes have not been released yet, hence having to install from master

For me personally installing go just to build tools from source code has been worth it instead of downloading binaries and setting that up, despite not actually developing anything in go. But if you're using codespaces I can see why that would be less desirable

**Comment by NickLiffen** [comment]
> But if you're using codespaces I can see why that would be less desirable

100%! If I was on my local machine I would so install Go and get this done, but it's more _overhead_ on my system having to install Go when it actually isn't needed. Local machine 100% I would install from Go, but as no other Go is indeed I would rather not if possible ❤️ 

> but the changes have not been released yet

Ah okay this explains it 😄 Do we know when the changes may get released? 👀

**Comment by catthehacker** [comment]
You can get latest build from https://github.com/nektos/act/actions/runs/1773288141

**Comment by NickLiffen** [comment]
Hey @catthehacker, correct, but that doesn't work with this script. 

https://github.com/nektos/act/blob/master/install.sh

It would be great if it could be generally available :)

**Comment by BorzdeG** [comment]
> It is, but most likely you are using v0.2.25 which doesn't have that change

@catthehacker  This is the latest version available through homebrew and is listed as release in the repository.

**Comment by catthehacker** [comment]
> > It is, but most likely you are using v0.2.25 which doesn't have that change
> 
> @catthehacker This is the latest version available through homebrew and is listed as release in the repository.

That is correct, though I don't understand what's your point?
Not everything in `master` branch is released instantly as a new version
We even have instructions added about how to install latest commit with homebrew
https://github.com/nektos/act#homebrew-linuxmacos

**Comment by BorzdeG** [comment]
You wrote that in version 0.2.25 there is no node16 support yet. What version is it in?

Act latest release - 0.2.25 : https://github.com/nektos/act/releases/latest

Here is the brew output:
```
➜ brew upgrade
Running `brew update --preinstall`...
==> Auto-updated Homebrew!
Updated Homebrew from 423f34dee to 82550edf6.
Updated 3 taps (homebrew/cask-versions, homebrew/core and homebrew/cask).
==> Updated Formulae
Updated 36 formulae.
==> Updated Casks
Updated 37 casks.


➜ brew info act
act: stable 0.2.25 (bottled), HEAD
Run your GitHub Actions locally 🚀
https://github.com/nektos/act
/usr/local/Cellar/act/0.2.25 (5 files, 21.1MB) *
  Poured from bottle on 2021-11-26 at 11:20:11
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/act.rb
```

**Comment by catthehacker** [comment]
> What version is it in?

None, there is no version released yet with that change

**Comment by BorzdeG** [comment]
And when is the release planned?

**Comment by calvinchengx** [comment]
@BorzdeG 

use `brew install act --HEAD`

**Comment by catthehacker** [comment]
> And when is the release planned?

https://github.com/nektos/act/releases/tag/v0.2.26
