### ISSUE TITLE
Issue: actions/checkout doesn't copy git tracked but gitignored files

### ISSUE THREAD

**Issue by jsoref** [nektos/act#912]
The general behavior of `.gitignore` doesn't prevent files that are tracked from being checked out. It just prevents from from being updated or added.

I'd expect that act not copy over untracked files matched by `.gitignore`, but I'd expect it to include tracked files that are matched by `.gitignore`.

## System information

- Operating System: Linux & macOS
- Architecture: x64
- Apple M1: no
- Docker version: on macOS: 20.10.8 (not sure about the version used by GHA)
- Docker image used in `act`: catthehacker/ubuntu:act-latest
- `act` version: 0.2.25

## Expected behaviour

Files listed in `.gitignore` should be present in the checked out repository

## Actual behaviour

Files listed in `.gitignore` are not present

## Workflow and/or repository

https://github.com/jsoref/ignored/commit/bfbee7f061955141522839cbb6abf690678adfb0
https://github.com/jsoref/ignored/runs/4398686247?check_suite_focus=true

https://github.com/jsoref/ignored/commit/5e20813c26869ea46a07a4ec03481c911377979c
https://github.com/jsoref/ignored/runs/4398859601?check_suite_focus=true

## Steps to reproduce

1. Push https://github.com/jsoref/ignored/commit/bfbee7f061955141522839cbb6abf690678adfb0 to a GitHub repo
2. Check the action log
3. Push https://github.com/jsoref/ignored/commit/5e20813c26869ea46a07a4ec03481c911377979c to the GitHub repo
4. Check the action log

## `act` output

<details>
  <summary>Log</summary>

```none
[What do I have/Introspection] Skipping local actions/checkout because workdir was already copied
```

</details>

**Comment by catthehacker** [comment]
Have you tried `--use-gitignore=false`?

**Comment by jsoref** [comment]
Yes, it would work, see the second commit/run.

But I shouldn't need to

**Comment by catthehacker** [comment]
Right, we can't change behaviour because it will break functionality for other people

**Comment by jsoref** [comment]
I see three possible behaviors:
1. Copy all files
2. Copy all files not matching `.gitignore`
3. Copy all files except non tracked files matched by `.gitignore`

The current default is 2. The flag gets 1. I'm looking for 3.

The distinction between 2 and 3 is imo a bug, hence this bug.

**Comment by jsoref** [comment]
Please tag

**Comment by jsoref** [comment]
It's still a thing...

**Comment by jsoref** [comment]
It's still a thing...
