### ISSUE TITLE
Error when building from source

### ISSUE THREAD

**Issue by pjmartorell** [nektos/act#96]
I have the following error when building from source:
```
> make build
?   	github.com/nektos/act	[no test files]
?   	github.com/nektos/act/cmd	[no test files]
ok  	github.com/nektos/act/pkg/common	(cached)	coverage: 44.6% of statements
ok  	github.com/nektos/act/pkg/container	(cached)	coverage: 60.3% of statements
ok  	github.com/nektos/act/pkg/model	(cached)	coverage: 11.1% of statements
ok  	github.com/nektos/act/pkg/runner	21.891s	coverage: 78.5% of statements
go run -mod=vendor main.go -ra build
Error: unknown shorthand flag: 'a' in -a
exit status 1
make: *** [Makefile:24: build] Error 1
```
Am I missing something?

**Comment by fennecdjay** [comment]
Just ran in the same issue.
I ran `go build` and installed locally (I have ~/bin in my path).
seems to work.

Hope it helps.

**Comment by pjmartorell** [comment]
> Just ran in the same issue.
> I ran `go build` and installed locally (I have ~/bin in my path).
> seems to work.
> 
> Hope it helps.

Thanks, I finally did the same.

**Comment by fennecdjay** [comment]
What finally worked for me was
``` sh
alias act='/path/to/act/binary -P ubuntu-latest=nektos/act-environments-ubuntu:18.04
```

**Comment by pjmartorell** [comment]
in my case I compiled main.go, renamed it to `act`, `chown root:root` and moved it to `/usr/local/bin`, which is in my PATH
