### ISSUE TITLE
Enhancement: add validate command to validate your workflow 

### ISSUE THREAD

**Issue by developer-guy** [nektos/act#960]
## Describe feature

Recently, I found a cool project called [action-validator](https://github.com/mpalmer/action-validator), thanks to @mpalmer, it seems very useful to me when I want to check my workflow whether it is valid before sending it over to the repository. So, I thought it'd be nice if we moved that logic into the act itself.

What are your thoughts?

**Comment by catthehacker** [comment]
You can use https://github.com/rhysd/actionlint for that
