### ISSUE TITLE
Issue: default environment variables doesn't follow recent documents

### ISSUE THREAD

**Issue by ethinx** [nektos/act#970]
## System information
    - Operating System: macOS
    - Architecture: x64 (64-bit)
    - Apple M1: no
    - Docker version: 20.10.12
    - Docker image used in `act`: < can be omitted if it's included in log >
    - `act` version: 0.2.25

## Expected behaviour
There is a github env called `GITHUB_REF_NAME`

## Actual behaviour
`env.GITHUB_REF_NAME` is not set

check https://github.com/nektos/act/blob/master/pkg/runner/run_context.go, it seems that the supported env in `act` is not the same to the recent documentation: https://docs.github.com/en/actions/learn-github-actions/environment-variables#default-environment-variables

## Workflow and/or repository
Get  `${{ env.GITHUB_REF_NAME }}` in steps

## Steps to reproduce
Get  `${{ env.GITHUB_REF_NAME }}` in steps

**Comment by thiskevinwang** [comment]
+1 — Would be nice to have `echo ${GITHUB_REF_NAME}` behave similar to `echo ${GITHUB_REF}`

Thanks for this great tool by the way 🙏

**Comment by ChristopherHX** [comment]
_On my low priority backlog_

**Comment by hashibot-web** [comment]
@ChristopherHX I'd be happy to open a PR for this.

Is it pretty much adding an additional line here?
https://github.com/nektos/act/blob/3f2469bf5385b90da5f6a5d9922ccf9c9d7274a6/pkg/runner/run_context.go#L626

```diff
  env["GITHUB_REF"] = github.Ref
+ env["GITHUB_REF_NAME"] = github.RefName
```

**Comment by thiskevinwang** [comment]
@ChristopherHX I'd be happy to open a PR for this.

Is it pretty much adding an additional line here?
https://github.com/nektos/act/blob/3f2469bf5385b90da5f6a5d9922ccf9c9d7274a6/pkg/runner/run_context.go#L626

```diff
  env["GITHUB_REF"] = github.Ref
+ env["GITHUB_REF_NAME"] = github.RefName
```

**Comment by ChristopherHX** [comment]
This also needs to be added there
https://github.com/nektos/act/blob/3f2469bf5385b90da5f6a5d9922ccf9c9d7274a6/pkg/model/github_context.go#L20
Populated here based on github.ref without `refs/heads/` or `refs/tags/`.
https://github.com/nektos/act/blob/3f2469bf5385b90da5f6a5d9922ccf9c9d7274a6/pkg/runner/run_context.go#L552
I already do this in my act replacement backed by the official actions/runner:
https://github.com/ChristopherHX/runner.server/blob/565a185a74614b6ab7b520f355d458706c148793/src/Runner.Server/Controllers/MessageController.cs#L939-L940
