### ISSUE TITLE
Issue: act differs from GitHub action for pull_request

### ISSUE THREAD

**Issue by matthewberryman** [nektos/act#974]
## System information

- Operating System: macOS 12.2
- Architecture: x64
- Apple M1: no
- Docker version: 20.10.12, build e91ed57
- Docker image used in `act`: ghcr.io/catthehacker/ubuntu   act-latest   1358e4e6441f
- `act` version: HEAD-4f8da0a

## Expected behaviour

The same as GitHub: if a clean merge can be made, make the merge (for checking purposes, before actual merge is committed to the GitHub repo) and run the workflow on that.

## Actual behaviour

act only works on the checked out branch

## Workflow and/or repository

https://github.com/matthewberryman/eslint-example/pull/2

## Steps to reproduce

```
git clone -b feature/2 https://github.com/matthewberryman/eslint-example
cd eslint-example
act -v --defaultbranch master pull_request
```

## `act` output
time="2022-01-30T16:56:07+11:00" level=debug msg="Loading environment from /Users/matthew/AtC/eslint-example/.env"
time="2022-01-30T16:56:07+11:00" level=debug msg="Loading secrets from /Users/matthew/AtC/eslint-example/.secrets"
time="2022-01-30T16:56:07+11:00" level=debug msg="Loading workflows from '/Users/matthew/AtC/eslint-example/.github/workflows'"
time="2022-01-30T16:56:07+11:00" level=debug msg="Loading workflows recursively"
time="2022-01-30T16:56:07+11:00" level=debug msg="Found workflow 'node.js.yml' in '/Users/matthew/AtC/eslint-example/.github/workflows/node.js.yml'"
time="2022-01-30T16:56:07+11:00" level=debug msg="Reading workflow '/Users/matthew/AtC/eslint-example/.github/workflows/node.js.yml'"
time="2022-01-30T16:56:07+11:00" level=debug msg="Correcting if statements '/Users/matthew/AtC/eslint-example/.github/workflows/node.js.yml'"
time="2022-01-30T16:56:07+11:00" level=debug msg="Planning event: pull_request"
time="2022-01-30T16:56:07+11:00" level=debug
time="2022-01-30T16:56:07+11:00" level=debug msg="Loading slug from git directory '/Users/matthew/AtC/eslint-example/.git'"
time="2022-01-30T16:56:07+11:00" level=debug msg="Found revision: cee1b709c78186fdad1ebcc0b390d4bfe5558a40\n"
time="2022-01-30T16:56:07+11:00" level=debug msg="expression 'success()' evaluated to 'true'"
[Node.js CI/build] 🧪  Matrix: map[node-version:16.x]
[Node.js CI/build] 🚀  Start image=ghcr.io/catthehacker/ubuntu:act-latest
time="2022-01-30T16:56:07+11:00" level=debug msg="Loading slug from git directory '/Users/matthew/AtC/eslint-example/.git'"
time="2022-01-30T16:56:07+11:00" level=debug msg="Found revision: cee1b709c78186fdad1ebcc0b390d4bfe5558a40\n"
[Node.js CI/build]   🐳  docker pull image=ghcr.io/catthehacker/ubuntu:act-latest platform= username= forcePull=false
[Node.js CI/build]   🐳  docker pull ghcr.io/catthehacker/ubuntu:act-latest
time="2022-01-30T16:56:07+11:00" level=debug msg="Image exists? true"
[Node.js CI/build]   🐳  docker create image=ghcr.io/catthehacker/ubuntu:act-latest platform= entrypoint=["/usr/bin/tail" "-f" "/dev/null"] cmd=[]
[Node.js CI/build] Created container name=act-Node-js-CI-build id=8b2b01164438acb2b9354fc7fa572fbea24806c2c484bcc6d1d4800cedab17f9 from image ghcr.io/catthehacker/ubuntu:act-latest (platform: )
[Node.js CI/build] ENV ==> [RUNNER_TOOL_CACHE=/opt/hostedtoolcache RUNNER_OS=Linux RUNNER_TEMP=/tmp]
[Node.js CI/build]   🐳  docker run image=ghcr.io/catthehacker/ubuntu:act-latest platform= entrypoint=["/usr/bin/tail" "-f" "/dev/null"] cmd=[]
[Node.js CI/build] Starting container: 8b2b01164438acb2b9354fc7fa572fbea24806c2c484bcc6d1d4800cedab17f9
[Node.js CI/build] Started container: 8b2b01164438acb2b9354fc7fa572fbea24806c2c484bcc6d1d4800cedab17f9
[Node.js CI/build]   🐳  docker exec cmd=[mkdir -m 0777 -p /var/run/act] user=root workdir=
[Node.js CI/build] Exec command '[mkdir -m 0777 -p /var/run/act]'
[Node.js CI/build] Working directory '/Users/matthew/AtC/eslint-example'
[Node.js CI/build]   🐳  docker cp src=/Users/matthew/AtC/eslint-example/. dst=/Users/matthew/AtC/eslint-example
[Node.js CI/build]   🐳  docker exec cmd=[mkdir -p /Users/matthew/AtC/eslint-example] user= workdir=
[Node.js CI/build] Exec command '[mkdir -p /Users/matthew/AtC/eslint-example]'
[Node.js CI/build] Working directory '/Users/matthew/AtC/eslint-example'
time="2022-01-30T16:56:07+11:00" level=debug msg="Writing tarball /var/folders/v2/l6swlq550135qvfk797r6gdm0000gn/T/act3979627919 from /Users/matthew/AtC/eslint-example/."
time="2022-01-30T16:56:07+11:00" level=debug msg="Stripping prefix:/Users/matthew/AtC/eslint-example/ src:/Users/matthew/AtC/eslint-example/."
[Node.js CI/build] Extracting content from '/var/folders/v2/l6swlq550135qvfk797r6gdm0000gn/T/act3979627919' to '/Users/matthew/AtC/eslint-example'
time="2022-01-30T16:56:07+11:00" level=debug msg="Writing entry to tarball workflow/event.json len:2"
time="2022-01-30T16:56:07+11:00" level=debug msg="Writing entry to tarball workflow/envs.txt len:0"
time="2022-01-30T16:56:07+11:00" level=debug msg="Writing entry to tarball workflow/paths.txt len:0"
[Node.js CI/build] Extracting content to '/var/run/act/'
time="2022-01-30T16:56:07+11:00" level=debug msg="Loading slug from git directory '/Users/matthew/AtC/eslint-example/.git'"
time="2022-01-30T16:56:07+11:00" level=debug msg="Found revision: cee1b709c78186fdad1ebcc0b390d4bfe5558a40\n"
time="2022-01-30T16:56:07+11:00" level=debug msg="expression 'success()' evaluated to 'true'"
time="2022-01-30T16:56:07+11:00" level=debug msg="Loading slug from git directory '/Users/matthew/AtC/eslint-example/.git'"
time="2022-01-30T16:56:07+11:00" level=debug msg="Found revision: cee1b709c78186fdad1ebcc0b390d4bfe5558a40\n"
time="2022-01-30T16:56:08+11:00" level=debug msg="Loading slug from git directory '/Users/matthew/AtC/eslint-example/.git'"
time="2022-01-30T16:56:08+11:00" level=debug msg="Found revision: cee1b709c78186fdad1ebcc0b390d4bfe5558a40\n"
[Node.js CI/build] setupEnv => map[ACT:true AGENT_TOOLSDIRECTORY:/opt/hostedtoolcache CI:true DEBIAN_FRONTEND:noninteractive DEPLOYMENT_BASEPATH:/opt/runner GITHUB_ACTION:0 GITHUB_ACTIONS:true GITHUB_ACTION_PATH: GITHUB_ACTION_REF: GITHUB_ACTION_REPOSITORY: GITHUB_ACTOR:nektos/act GITHUB_API_URL:https://api.github.com GITHUB_BASE_REF: GITHUB_ENV:/var/run/act/workflow/envs.txt GITHUB_EVENT_NAME:pull_request GITHUB_EVENT_PATH:/var/run/act/workflow/event.json GITHUB_GRAPHQL_URL:https://api.github.com/graphql GITHUB_HEAD_REF: GITHUB_JOB:build GITHUB_PATH:/var/run/act/workflow/paths.txt GITHUB_REF:refs/pull/%!s(<nil>)/merge GITHUB_REPOSITORY:matthewberryman/eslint-example GITHUB_REPOSITORY_OWNER:matthewberryman GITHUB_RETENTION_DAYS:0 GITHUB_RUN_ID:1 GITHUB_RUN_NUMBER:1 GITHUB_SERVER_URL:https://github.com GITHUB_SHA:cee1b709c78186fdad1ebcc0b390d4bfe5558a40 GITHUB_TOKEN: GITHUB_WORKFLOW:Node.js CI GITHUB_WORKSPACE:/Users/matthew/AtC/eslint-example IMAGE_OS:ubuntu20 ImageOS:ubuntu20 LSB_OS_VERSION:2004 LSB_RELEASE:20.04 PATH:/opt/hostedtoolcache/node/14.18.3/x64/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin RUNNER_PERFLOG:/dev/null RUNNER_TRACKING_ID: RUNNER_USER:root RUN_TOOL_CACHE:/opt/hostedtoolcache USER:root]
[Node.js CI/build] ⭐  Run actions/checkout@v2
time="2022-01-30T16:56:08+11:00" level=debug msg="Loading slug from git directory '/Users/matthew/AtC/eslint-example/.git'"
time="2022-01-30T16:56:08+11:00" level=debug msg="Found revision: cee1b709c78186fdad1ebcc0b390d4bfe5558a40\n"
[Node.js CI/build] Skipping local actions/checkout because workdir was already copied
[Node.js CI/build]   ✅  Success - actions/checkout@v2
time="2022-01-30T16:56:08+11:00" level=debug msg="Loading slug from git directory '/Users/matthew/AtC/eslint-example/.git'"
time="2022-01-30T16:56:08+11:00" level=debug msg="Found revision: cee1b709c78186fdad1ebcc0b390d4bfe5558a40\n"
time="2022-01-30T16:56:08+11:00" level=debug msg="expression 'success()' evaluated to 'true'"
time="2022-01-30T16:56:08+11:00" level=debug msg="Loading slug from git directory '/Users/matthew/AtC/eslint-example/.git'"
time="2022-01-30T16:56:08+11:00" level=debug msg="Found revision: cee1b709c78186fdad1ebcc0b390d4bfe5558a40\n"
time="2022-01-30T16:56:08+11:00" level=debug msg="Loading slug from git directory '/Users/matthew/AtC/eslint-example/.git'"
time="2022-01-30T16:56:08+11:00" level=debug msg="Found revision: cee1b709c78186fdad1ebcc0b390d4bfe5558a40\n"
[Node.js CI/build] setupEnv => map[ACT:true AGENT_TOOLSDIRECTORY:/opt/hostedtoolcache CI:true DEBIAN_FRONTEND:noninteractive DEPLOYMENT_BASEPATH:/opt/runner GITHUB_ACTION:1 GITHUB_ACTIONS:true GITHUB_ACTION_PATH: GITHUB_ACTION_REF: GITHUB_ACTION_REPOSITORY: GITHUB_ACTOR:nektos/act GITHUB_API_URL:https://api.github.com GITHUB_BASE_REF: GITHUB_ENV:/var/run/act/workflow/envs.txt GITHUB_EVENT_NAME:pull_request GITHUB_EVENT_PATH:/var/run/act/workflow/event.json GITHUB_GRAPHQL_URL:https://api.github.com/graphql GITHUB_HEAD_REF: GITHUB_JOB:build GITHUB_PATH:/var/run/act/workflow/paths.txt GITHUB_REF:refs/pull/%!s(<nil>)/merge GITHUB_REPOSITORY:matthewberryman/eslint-example GITHUB_REPOSITORY_OWNER:matthewberryman GITHUB_RETENTION_DAYS:0 GITHUB_RUN_ID:1 GITHUB_RUN_NUMBER:1 GITHUB_SERVER_URL:https://github.com GITHUB_SHA:cee1b709c78186fdad1ebcc0b390d4bfe5558a40 GITHUB_TOKEN: GITHUB_WORKFLOW:Node.js CI GITHUB_WORKSPACE:/Users/matthew/AtC/eslint-example IMAGE_OS:ubuntu20 ImageOS:ubuntu20 LSB_OS_VERSION:2004 LSB_RELEASE:20.04 PATH:/opt/hostedtoolcache/node/14.18.3/x64/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin RUNNER_PERFLOG:/dev/null RUNNER_TRACKING_ID: RUNNER_USER:root RUN_TOOL_CACHE:/opt/hostedtoolcache USER:root]
[Node.js CI/build] ⭐  Run npm install
time="2022-01-30T16:56:08+11:00" level=debug msg="Wrote command \n\nnpm install\n\n to 'workflow/1'"
time="2022-01-30T16:56:08+11:00" level=debug msg="Writing entry to tarball workflow/1 len:13"
[Node.js CI/build] Extracting content to '/var/run/act'
[Node.js CI/build]   🐳  docker exec cmd=[bash --noprofile --norc -e -o pipefail /var/run/act/workflow/1] user= workdir=
[Node.js CI/build] Exec command '[bash --noprofile --norc -e -o pipefail /var/run/act/workflow/1]'
[Node.js CI/build] Working directory '/Users/matthew/AtC/eslint-example'
[Node.js CI/build]   | npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
[Node.js CI/build]   | 
[Node.js CI/build]   | > core-js-pure@3.20.3 postinstall /Users/matthew/AtC/eslint-example/node_modules/core-js-pure
[Node.js CI/build]   | > node -e "try{require('./postinstall')}catch(e){}"
[Node.js CI/build]   | 
[Node.js CI/build]   | added 184 packages from 92 contributors and audited 184 packages in 7.772s
[Node.js CI/build]   | 
[Node.js CI/build]   | 52 packages are looking for funding
[Node.js CI/build]   |   run `npm fund` for details
[Node.js CI/build]   | 
[Node.js CI/build]   | found 0 vulnerabilities
[Node.js CI/build]   | 
[Node.js CI/build]   ✅  Success - npm install
time="2022-01-30T16:56:17+11:00" level=debug msg="Loading slug from git directory '/Users/matthew/AtC/eslint-example/.git'"
time="2022-01-30T16:56:17+11:00" level=debug msg="Found revision: cee1b709c78186fdad1ebcc0b390d4bfe5558a40\n"
time="2022-01-30T16:56:17+11:00" level=debug msg="expression 'success()' evaluated to 'true'"
time="2022-01-30T16:56:17+11:00" level=debug msg="Loading slug from git directory '/Users/matthew/AtC/eslint-example/.git'"
time="2022-01-30T16:56:17+11:00" level=debug msg="Found revision: cee1b709c78186fdad1ebcc0b390d4bfe5558a40\n"
time="2022-01-30T16:56:17+11:00" level=debug msg="Loading slug from git directory '/Users/matthew/AtC/eslint-example/.git'"
time="2022-01-30T16:56:17+11:00" level=debug msg="Found revision: cee1b709c78186fdad1ebcc0b390d4bfe5558a40\n"
[Node.js CI/build] setupEnv => map[ACT:true AGENT_TOOLSDIRECTORY:/opt/hostedtoolcache CI:true DEBIAN_FRONTEND:noninteractive DEPLOYMENT_BASEPATH:/opt/runner GITHUB_ACTION:2 GITHUB_ACTIONS:true GITHUB_ACTION_PATH: GITHUB_ACTION_REF: GITHUB_ACTION_REPOSITORY: GITHUB_ACTOR:nektos/act GITHUB_API_URL:https://api.github.com GITHUB_BASE_REF: GITHUB_ENV:/var/run/act/workflow/envs.txt GITHUB_EVENT_NAME:pull_request GITHUB_EVENT_PATH:/var/run/act/workflow/event.json GITHUB_GRAPHQL_URL:https://api.github.com/graphql GITHUB_HEAD_REF: GITHUB_JOB:build GITHUB_PATH:/var/run/act/workflow/paths.txt GITHUB_REF:refs/pull/%!s(<nil>)/merge GITHUB_REPOSITORY:matthewberryman/eslint-example GITHUB_REPOSITORY_OWNER:matthewberryman GITHUB_RETENTION_DAYS:0 GITHUB_RUN_ID:1 GITHUB_RUN_NUMBER:1 GITHUB_SERVER_URL:https://github.com GITHUB_SHA:cee1b709c78186fdad1ebcc0b390d4bfe5558a40 GITHUB_TOKEN: GITHUB_WORKFLOW:Node.js CI GITHUB_WORKSPACE:/Users/matthew/AtC/eslint-example IMAGE_OS:ubuntu20 ImageOS:ubuntu20 LSB_OS_VERSION:2004 LSB_RELEASE:20.04 PATH:/opt/hostedtoolcache/node/14.18.3/x64/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin RUNNER_PERFLOG:/dev/null RUNNER_TRACKING_ID: RUNNER_USER:root RUN_TOOL_CACHE:/opt/hostedtoolcache USER:root]
[Node.js CI/build] ⭐  Run npm run lint
time="2022-01-30T16:56:17+11:00" level=debug msg="Wrote command \n\nnpm run lint\n\n to 'workflow/2'"
time="2022-01-30T16:56:17+11:00" level=debug msg="Writing entry to tarball workflow/2 len:14"
[Node.js CI/build] Extracting content to '/var/run/act'
[Node.js CI/build]   🐳  docker exec cmd=[bash --noprofile --norc -e -o pipefail /var/run/act/workflow/2] user= workdir=
[Node.js CI/build] Exec command '[bash --noprofile --norc -e -o pipefail /var/run/act/workflow/2]'
[Node.js CI/build] Working directory '/Users/matthew/AtC/eslint-example'
[Node.js CI/build]   | 
[Node.js CI/build]   | > eslint-example@1.0.0 lint /Users/matthew/AtC/eslint-example
[Node.js CI/build]   | > eslint .
[Node.js CI/build]   | 
[Node.js CI/build]   | Warning: React version was set to "detect" in eslint-plugin-react settings, but the "react" package is not installed. Assuming latest React version for linting.
[Node.js CI/build]   ✅  Success - npm run lint
[Node.js CI/build] Removed container: 8b2b01164438acb2b9354fc7fa572fbea24806c2c484bcc6d1d4800cedab17f9
[Node.js CI/build]   🐳  docker volume rm act-Node-js-CI-build
time="2022-01-30T16:56:20+11:00" level=debug msg="Loading slug from git directory '/Users/matthew/AtC/eslint-example/.git'"
time="2022-01-30T16:56:20+11:00" level=debug msg="Found revision: cee1b709c78186fdad1ebcc0b390d4bfe5558a40\n"

**Comment by catthehacker** [comment]
This is expected behaviour
