### ISSUE TITLE
Enhancement: explain how to install on Windows "the normal way"

### ISSUE THREAD

**Issue by Pomax** [nektos/act#976]
## Describe feature

The universal Windows installation procedure is "download the .exe or .msi installer, and run that". Chocolatey might be popular in some circles, but is very far from a universal tool (unlike a third party manager like homebrew for mac).

Can the readme be updated with instructions on how to install `act` without a third party manager?

**Comment by ChristopherHX** [comment]
Isn't this the same as https://github.com/nektos/act#manual-download, that how I always do it on windows.

**Comment by Pomax** [comment]
probably, but referencing that in the section on "how to install on windows" would be a great idea. A little bit of information discoverability goes a long way =)

**Comment by catthehacker** [comment]
Those instructions have been there for long time. Additionally I've expanded them a little bit in wiki: https://github.com/nektos/act/wiki/Installation#other-install-options
