### ISSUE TITLE
Issue: No newline after the `Provide value for '<secret>'`

### ISSUE THREAD

**Issue by stdedos** [nektos/act#979]
## System information

- Operating System: Ubuntu
- Architecture:
- Apple M1:
- Docker version:
- Docker image used in `act`:
- `act` version:

## Expected behaviour

There seems to be no newline after the `Provide value for '<secret>'` prompt

## `act` output

<details>
  <summary>Log</summary>

```none
PASTE YOUR LOG HERE
```

</details>

**Comment by stdedos** [comment]
Closed as ??? 😕

**Comment by catthehacker** [comment]
I have no idea what is the issue here also incomplete template

**Comment by stdedos** [comment]
> I have no idea what is the issue here ...

It's pretty obvious if you read the title:
> No newline after the `Provide value for '<secret>'`

or the issue:
> There seems to be no newline after the `Provide value for '<secret>'` prompt

or, visually:
```console
$ act --detect-event -s secrat --reuse
Provide value for 'SECRAT': WARN[0001] Cannot parse container options: --user 1001  
[Action] 🧪  Matrix: map[a:b c:d]
```

I am not sure what remains to be explained

---

> ... also incomplete template

Apologies, but I do not have an `Apple M1:` chip to fill the template with 😕 

Also, another bug: You capitalize a secret's name when you shouldn't (notice that I gave `-s secrat`, you typed `SECRAT`).
https://docs.github.com/en/actions/security-guides/encrypted-secrets#naming-your-secrets

**Comment by catthehacker** [comment]
> Also, another bug: You capitalize a secret's name when you shouldn't (notice that I gave `-s secrat`, you typed `SECRAT`).

Not a bug

> Secret names are not case-sensitive.

From the documentation you linked. We convert all secrets and envvars to upper case so they don't collide. On GitHub it also allows only uppercase secrets and envvars.
