### ISSUE TITLE
Issue: Installation fails with "unknown revision v0.20.6" (for k8s.io/apiserver@v0.20.6)

### ISSUE THREAD

**Issue by sschuberth** [nektos/act#987]
## System information

- Operating System: Fedora 34
- Architecture: x64 (64-bit)
- Apple M1: no
- Docker version: 20.10.12
- Docker image used in `act`: n/a
- `act` version: latest

## Expected behaviour

Installation should succeed via `go install github.com/nektos/act@latest`.

## Actual behaviour

Installation fails with

```
$ go install github.com/nektos/act@latest
go: downloading github.com/nektos/act v0.2.25
go install github.com/nektos/act@latest: github.com/nektos/act@none updating to
        github.com/nektos/act@v0.2.25 requires
        github.com/containerd/containerd@v1.5.5 requires
        k8s.io/apiserver@v0.20.6: reading k8s.io/apiserver/go.mod at revision v0.20.6: unknown revision v0.20.6
```

## Workflow and/or repository

n/a

## Steps to reproduce

See above.

## `act` output

n/a

**Comment by catthehacker** [comment]
Can you show output of `go env`?
That revision still exists (https://github.com/kubernetes/apiserver/tree/v0.20.6) and I have no issues installing `act`

**Comment by sschuberth** [comment]
Please see:

```
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/sebastian/.cache/go-build"
GOENV="/home/sebastian/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/sebastian/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/sebastian/go"
GOPRIVATE=""
GOPROXY="direct"
GOROOT="/usr/lib/golang"
GOSUMDB="off"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/golang/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16.13"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build4134731451=/tmp/go-build -gno-record-gcc-switches"
```

**Comment by sschuberth** [comment]
> GOMOD="/dev/null"

This looks a bit suspicious, or? Sorry, I've close to no experience with Go.

**Comment by catthehacker** [comment]
`GOPROXY="https://proxy.golang.org,direct" GOSUMDB="sum.golang.org" go install github.com/nektos/act@latest` should work

**Comment by catthehacker** [comment]
Is there a reason why you won't use pre-built binaries?

**Comment by sschuberth** [comment]
> Is there a reason why you won't use pre-built binaries?

No, and that's what I did now as a fallback; but installing via Go seemed more natural to me as a developer.

**Comment by sschuberth** [comment]
> `GOPROXY="https://proxy.golang.org,direct" GOSUMDB="sum.golang.org" go install github.com/nektos/act@latest` should work

Mind giving me a hint what this does exactly / why it's necessary in my case?

**Comment by catthehacker** [comment]
> > `GOPROXY="https://proxy.golang.org,direct" GOSUMDB="sum.golang.org" go install github.com/nektos/act@latest` should work
> 
> Mind giving me a hint what this does exactly / why it's necessary in my case?

Some distributions remove default `GOPROXY` / `GOSUMDB` because of privacy reasons, as Go services are hosted by Google.
`GOPROXY` - hosts a copy of module repositories or proxies connection in case if it's not cached
`GOSUMDB` - records checksums for modules and in case something changed in the source of module, it will error on mismatch

**Comment by sschuberth** [comment]
Thanks. Do you think it's worth updating the official installation instructions with these settings? Or is this too much of an edge case?

**Comment by catthehacker** [comment]
> Do you think it's worth updating the official installation instructions with these settings? Or is this too much of an edge case?

Instruction is meant for people who already deal with Go or have it installed (I use it to compare behaviour between versions and when developing). I would prefer to have `act` packaged in Fedora and it's derivatives otherwise.
